### ISSUE TITLE
ingress creation should fail if static ip annotation does not exist

### ISSUE THREAD

**Issue by prameshj** [kubernetes/ingress-gce#1005]
The current handling of the static ip annotation can cause ingress VIP to change somewhat unexpectedly.

https://github.com/kubernetes/ingress-gce/blob/master/pkg/loadbalancers/forwarding_rules.go#L152-L167
If annotation "kubernetes.io/ingress.global-static-ip-name" is specified with a non-existed IP, a new static IP is created by the controller.
Now, if a static address is created with the "kubernetes.io/ingress.global-static-ip-name" value that was specified, the forwarding rule eventually gets updated with the new IP address.

The better behavior would be to fail the ingress creation in the first place if the static IP was not present.

**Comment by omaskery** [comment]
Is this definitely a bug and not some sort of feature request? I had assumed this was intended behaviour. We previously relied on this behaviour (until we encountered this issue: https://issuetracker.google.com/154202236 [requires sign-in]).

Perhaps there should be some annotation required to explicitly request that a static IP is generated? :slightly_smiling_face:

**Comment by bowei** [comment]
cc: @spencerhance

**Comment by prameshj** [comment]
@omaskery Is it possible to create a staticip and use that name in the annotation? I see we create a staticIP if you also use HTTP and HTTPS - https://github.com/kubernetes/ingress-gce/blob/fbce6b58a83e61cad547779dc364f408a18f74e5/pkg/loadbalancers/l7.go#L177

**Comment by omaskery** [comment]
@prameshj yes, I was speaking from an experience of a very unusual (and undesirable) edge case. I don't think it's worth considering here, I feel that my comment here was premature.

Since omitting the `kubernetes.io/ingress.global-static-ip-name` annotation also generates a static IP automatically, I no longer have anything against your suggestion :)

Disregard my comment from above!

**Comment by prameshj** [comment]
Thanks for confirming! Here is the PR with the fix - https://github.com/kubernetes/ingress-gce/pull/1080

**Comment by spencerhance** [comment]
@prameshj Can we close this since the PR has merged?

**Comment by prameshj** [comment]
Yes, closing since the fix has been merged.
