### ISSUE TITLE
Healthcheck configuration behavior

### ISSUE THREAD

**Issue by lechuk47** [kubernetes/ingress-gce#1009]
Hi All, 

I'm trying to configure a HTTP(s) Load balancer through a GKE Ingress and I'm finding some strange things. The GCP documentation states that if a readynessProbe is configured the LB healthcheck will pick up its configuration, but I'm observing a strange behavior:  

* The readynessProbe configuration is not used in the HC if the readynessProbe port is not the same as the port configured in the servicePort attribute of the backend in the Ingress

* Although the default service check port shown in the console is 80, the healtcheck request is thrown to the servicePort configured in the backend of the ingress. 

Is that the behavior shuold I expect?  

Thanks in advance.

**Comment by rramkumar1** [comment]
> * The readynessProbe configuration is not used in the HC if the readynessProbe port is not the same as the port configured in the servicePort attribute of the backend in the Ingress

That's correct. See https://cloud.google.com/kubernetes-engine/docs/concepts/ingress#health_checks

> * Although the default service check port shown in the console is 80, the healtcheck request is thrown to the servicePort configured in the backend of the ingress.

Not sure I understand what you mean here. Can you elaborate a bit?

**Comment by bowei** [comment]
Ref: https://github.com/kubernetes/ingress-gce/pull/1029

**Comment by MTCoster** [comment]
Apologies for the potentially dumb question, but does this behaviour mean that [this configuration](https://stackoverflow.com/q/60405567/1813169) would not work?
