### ISSUE TITLE
Add release tags for v1.6.2, v1.7.3 and v1.8.2

### ISSUE THREAD

**Issue by skmatti** [kubernetes/ingress-gce#1038]
v1.6, v1.7 and v1.8 had been updated with a bugfix related to enabling access logs for backends associated with an Ingress. https://github.com/kubernetes/ingress-gce/pull/1023, https://github.com/kubernetes/ingress-gce/pull/1035 and https://github.com/kubernetes/ingress-gce/pull/1044

Corresponding release tags needs be created on respective branches.

@rramkumar1 @MrHohn 

cc: @spencerhance

**Comment by MrHohn** [comment]
Acked, I will go ahead and push the tags.

**Comment by MrHohn** [comment]
Okay I have pushed the tags. Feel free to reopen if more steps are needed :)
