### ISSUE TITLE
BUG > Internal Load Balancer attempts to use regional cert

### ISSUE THREAD

**Issue by kuwas** [kubernetes/ingress-gce#1047]
# Description

## Current Behavior

* Attempting to use internal load balancer with an existing certificate will lead the controller to attempt to mount a "regional" certificate, but it cannot find the certificate since it is global.

```
      "kubernetes.io/ingress.class": "gce-internal"
      "ingress.gcp.kubernetes.io/pre-shared-cert": "default-sandbox"
```

```
googleapi: Error 404: The resource 'projects/<redacted>/regions/us-central1/sslCertificates/default-sandbox' was not found, notFound
```

## Expected Behavior

* Internal load balancer should use certificate without issues

**Comment by spencerhance** [comment]
@kuwas The internal http load balancer actually only supports regional certificates: \([docs\)](https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balance-ingress#https_between_client_and_load_balancer) so this is expected behavior
