### ISSUE TITLE
OpenAPI v2 schema not published for BackendConfig

### ISSUE THREAD

**Issue by jpbetz** [kubernetes/ingress-gce#1055]
BackendConfig CRDs are non-structural because they do not have pruning enabled (note in the CRD that`preserveUnknownFields: true`). See https://v1-17.docs.kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#publish-validation-schema-in-openapi-v2.

How to reproduce:

- curl `<apiserver-url>/openapi/v2`
- Look for the definition "com.google.cloud.v1beta1.BackendConfig". The entry just defines the type as "object".

Pruning can be manually enabled by setting `preserveUnknownFields: false` in the BackendConfig CRD. Once enabled, `/openapi/v2` returns the full schema.

I don't see any reason why pruning needs to be disabled for BackendConfig. It might be worth upgrading to the CRD v1 API at the same time?

**Comment by rramkumar1** [comment]
@skmatti
