### ISSUE TITLE
Reverse certificate dependencies

### ISSUE THREAD

**Issue by CapoD** [kubernetes/ingress-gce#1068]
Improvement idea: Create a managed certificates annotation that allows to specify selectors for the certificates that need to be associated with the ingress.

Problem: Certificates have to be specified on Ingress by naming them explicitly in the corresponding annotation via `networking.gke.io/managed-certificates: cert1,cert2,.....`
However, this makes it hard to deploy applications independently, since you can create separate DNS records pointing to the LB and separate certificates, but eventually you have to touch the Ingress to register the names of these certificates.

I do not know if the idea is feasible, but I would love to discuss different approaches for this problem.

**Comment by rramkumar1** [comment]
@CapoD This is an interesting idea although something that is hard to support in the current Ingress API without fundamental changes to the spec.

I would suggest making a FR for the new Gateway API which is still in development and is the next generation of Ingress.

Ref: https://github.com/kubernetes-sigs/service-apis
