### ISSUE TITLE
How to setup minReadySeconds/terminationGracePeriodSeconds with NEG?

### ISSUE THREAD

**Issue by axot** [kubernetes/ingress-gce#1072]
According to the [document](https://cloud.google.com/kubernetes-engine/docs/how-to/container-native-load-balancing#align_rollouts), 
> You should configure your workloads' minReadySeconds and terminationGracePeriodSeconds values to be 60 seconds or higher to ensure that the service is not disrupted due to workload rollouts.

In my test, even use a much less `minReadySeconds/terminationGracePeriodSeconds`, there are no impact at the view of response latency. Use `minReadySeconds/terminationGracePeriodSeconds:60` will slow down our development deploy progress. How to tuning the value of minReadySeconds? Why not 10 or 20 but 60 seconds?

Thanks,

**Comment by freehan** [comment]
Please check with the note on the top of this section: https://cloud.google.com/kubernetes-engine/docs/how-to/container-native-load-balancing#align_rollouts

For versions with pod readiness feedback enabled. `minReadySeconds` is no longer needed. But `terminationGracePeriodSeconds` is still required if the rolling update needs to be seammless.
