### ISSUE TITLE
Feature request: Add support header-based routing and query parameter-based routing

### ISSUE THREAD

**Issue by sho-abe** [kubernetes/ingress-gce#1088]
Since 4/23, Goole Cloud external HTTP (S) load balancer supports header-based routing and query parameter-based routing.
I'd like to use this feature by ingress-gce as well.

FYI: 
 * https://cloud.google.com/load-balancing/docs/release-notes#April_23_2020
 * https://cloud.google.com/load-balancing/docs/https/setting-up-traffic-management#http-header-based-routing
 * https://cloud.google.com/load-balancing/docs/https/setting-up-traffic-management#query-parameter-routing

**Comment by sho-abe** [comment]
This feature is very useful because it allows Ingress to route traffic by headers and queries without Istio.
/remove-lifecycle stale

**Comment by idaned** [comment]
Any news on this?

**Comment by mark-church** [comment]
Hi there, header-based routing is coming to GKE through the [GKE Gateway controller](https://cloud.google.com/kubernetes-engine/docs/concepts/gateway-api). All four [GatewayClasses support header-based routing](https://cloud.google.com/kubernetes-engine/docs/how-to/gatewayclass-capabilities#httproute). Query-parameter routing is not yet supported but is likely going to come on the roadmap. Note that the Gateway controller is still in Preview.

**Comment by AlamBeg** [comment]
> Hi there, header-based routing is coming to GKE through the [GKE Gateway controller](https://cloud.google.com/kubernetes-engine/docs/concepts/gateway-api). All four [GatewayClasses support header-based routing](https://cloud.google.com/kubernetes-engine/docs/how-to/gatewayclass-capabilities#httproute). Query-parameter routing is not yet supported but is likely going to come on the roadmap. Note that the Gateway controller is still in Preview.

HI @mark-church 

Is there any support on query parameter-based routing in the gke-ingress controller?
Our requirement is to validate a parameter in the header if that parameter is **True** route the traffic to a specific pod and if that parameter is **False**, route the traffic to another pod. 

Any specific ingress rules are available or supports on GKS?


Thanks in advance.
Alam
