### ISSUE TITLE
Ingress stuck in "Creating ingress" state

### ISSUE THREAD

**Issue by dhdersch** [kubernetes/ingress-gce#1095]
Hello,

I have a GKE Cluster (version 1.15.11-gke.11) for which I am creating an ingress. The ingress using the following:

- Global Static IP Address
- neg
- Managed Certificate

However, the ingress is stuck in "creating ingress" state. `kubectl describe` shows no events. I have 0 insight into why this isn't working. Furthermore, no Load Balancer is created for the Ingress. Note that creating a normal service with type LoadBalancer does successfully create a cloud load balancer.

I have checked, and HTTP Load Balancing is enabled for the cluster. I'm at a loss for what could be happening. I have even tried creating a simpler Ingress (with no neg, static IP address or cert) and that does not create a Load Balancer either (though it does not get stuck in "creating ingress").

**Comment by rramkumar1** [comment]
@dhdersch We have had multiple customers report similar issues. It's likely that for some reasons to do with the GKE Master, your GKE Ingress controller isn't actually running.

We are working with other GKE teams on how this can be mitigated. Stay tuned.

**Comment by rramkumar1** [comment]
@dhdersch What version is your GKE cluster? We are trying to identify if this is affecting a certain version.

**Comment by dhdersch** [comment]
@rramkumar1  1.15.11-gke.11

**Comment by rramkumar1** [comment]
@dhdersch I think we resolved your issue? I saw your GCP support case as well.

**Comment by dhdersch** [comment]
@rramkumar1 Yes, thanks.
