### ISSUE TITLE
docs: creating HTTP LB and adding GKE services as backends after the fact

### ISSUE THREAD

**Issue by naseemkullah** [kubernetes/ingress-gce#1122]
There is a good amount of docs for streamlining the creation of an HTTP LB via an ingress resource in GKE.

However it can be desirable to add GKE backends (be it NEGs or IGs) to an already existing HTTP LB  (as to not have the HTTP LB's lifecycle so tightly tied to the GKE ingress and to provide more flexibility) and there seems to be a lack of documentation for this approach. 

Could documentation be added on how to add GKE services to a pre existing HTTP LB?

cc @bowei

**Comment by bowei** [comment]
Documentation is more appropriate for non-Ingress repo:

https://cloud.google.com/kubernetes-engine/docs/how-to/standalone-neg

**Comment by naseemkullah** [comment]
Could you please link the more appropriate non-ingress repo @bowei ?

**Comment by naseemkullah** [comment]
Could you please link the more appropriate non-ingress repo @bowei ?

**Comment by naseemkullah** [comment]
Do you mean to say that the feedback button at the top right of https://cloud.google.com/kubernetes-engine/docs/how-to/standalone-neg should be used to issue this request?

**Comment by bowei** [comment]
Not trying to be flip and closing your issue abruptly, but dealing with Google Cloud specific stuff is not as appropriate to do in this repo -- is there something that the above page is missing?

**Comment by naseemkullah** [comment]
My apologies for opening this in the wrong repo.

I'm just looking for a place to talk about the lack of documentation and request that some be added. Would the feedback button be the appropriate place?

The only info I've gotten on the subject are in this slack convo https://kubernetes.slack.com/archives/C09R1TL6A/p1588378391280800?thread_ts=1588267265.268900&cid=C09R1TL6A

and this blog post: https://blog.jetstack.io/blog/container-native-multi-cluster-glb/

But would be great to have some GCP docs on such a thing.
