### ISSUE TITLE
Update GKE Version Mapping

### ISSUE THREAD

**Issue by inductor** [kubernetes/ingress-gce#1153]
On README.md, the current version mapping is this

       * 1.9.6-gke.2+ -> 0.9.7
       * 1.9.7-gke.5+ -> 0.9.7
       * 1.10.4-gke.0+ -> v1.1.1
       * 1.10.5-gke.1+ -> v1.2.2
       * 1.10.5-gke.3+ -> v1.2.3
       * 1.10.6-gke.2+ -> v1.3.0
       * 1.10.7-gke.1+ -> v1.3.2
       * 1.11.2-gke.4+ -> v1.3.3
       * 1.11.3-gke.14+ -> v1.4.0
       * 1.11.6-gke.2+ -> v1.4.1
       * 1.11.6-gke.6+ -> v1.4.2
       * 1.11.7-gke.7+ -> v1.4.3
       * 1.12.5-gke.10+ -> v1.5.0
       * 1.12.6-gke.7+ -> v1.5.1
       * 1.12.7-gke.16+ -> v1.5.2
       * 1.13.7-gke.5+ -> v1.6.0
       * 1.14.10-gke.31+ -> 1.6.2
       * 1.15.4-gke.21+ -> 1.7.2
       * 1.15.9-gke.22+ -> 1.7.3
       * 1.15.11-gke.15+ -> 1.7.4
       * 1.16.8-gke.3+ -> 1.9.1
       * 1.16.8-gke.17+ -> 1.9.2
       * 1.17.5-gke.0+ -> 1.9.2

It does not include the latest verision 1.9.5 and I think old versions such as `1.9.6-gke.2+ -> 0.9.7` should be deleted.

**Comment by rramkumar1** [comment]
@skmatti

**Comment by inductor** [comment]
@skmatti @rramkumar1 ping

**Comment by skmatti** [comment]
Some of the ingress versions do not have an existing GKE version yet. I will update the mapping as soon as they are released(around mid next week).
