### ISSUE TITLE
Generate CRD files for IDE autocompletion-support

### ISSUE THREAD

**Issue by Dominik-K** [kubernetes/ingress-gce#1163]
[IntelliJ supports autocompletion for CRDs when linking to an URL with the CRD](https://www.jetbrains.com/help/idea/kubernetes.html#crd).

Would be nice if we could directly link to the generated CRDs in this repo, for the `BackendConfig` CRD & the others in the making (`FrontendConfig` or `NEG`) :-)

**Comment by Dominik-K** [comment]
Will be obsolete when the [Kubernetes plugin of IntelliJ supports reading CRDs from the K8s-cluster itself](https://youtrack.jetbrains.com/issue/IDEA-232365).

**Comment by rramkumar1** [comment]
@skmatti
