### ISSUE TITLE
Internal Ingress stuck at creating stage

### ISSUE THREAD

**Issue by akshatgit** [kubernetes/ingress-gce#1189]
## Issue
I followed this [doc](https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balance-ingress) for creating internal ingress in GKE. 

But the ingress is stuck at the creation stage. I have two subnets in my VPC(backend-subnet and proxy-only-subnet) and addon for HTTP load balancing is enabled.

**Comment by rramkumar1** [comment]
@spencerhance FYI

@akshatgit Are there any events on your Ingress? If so, can you please paste it here.

**Comment by akshatgit** [comment]
Hi @rramkumar1 , I don't see any events.

**Comment by spencerhance** [comment]
Hi @akshatgit Can you send me an email with your GCP project ID, cluster name and location?  I can take a look at your cluster.

**Comment by akshatgit** [comment]
Sending mail

**Comment by bukito-ops** [comment]
Are there any updates? Because we have the same issue when following the instructions in https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balance-ingress.

Our GKE version is 1.15.12-gke.2.

**Comment by bukito-ops** [comment]
According to https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features, it works fine after create a cluster of version 1.16.11-gke.5.

**Comment by akshatgit** [comment]
@bukito-ops did it work for you?

**Comment by spencerhance** [comment]
Hi @akshatgit,

Sorry for the delay.  It looks like your cluster is not running a new enough version to use internal-ingress.  The cluster must be at version 1.16.5 and above.

**Comment by akshatgit** [comment]
Thanks @spencerhance  for clearing the issue. We can close it.
