### ISSUE TITLE
Traefik 2 with Global Static IP in gcloud

### ISSUE THREAD

**Issue by yra-wtag** [kubernetes/ingress-gce#1190]
Currently Traefik 2 is exposed using a L4 regional LB in gcloud. You can only add regional IPs for service type LoadBalancer in gcloud. However due to future possibility of moving the cluster resources in different region we need a Global Static IP.

Currently i see two scenario to make this happen

1. Use a Global TCP LB with the service and assign a static IP to it. Currently there is no tutorial on GCP to do this. Additionally it says it is not possible, Service LoadBalancers IPs needs to be regional IP. We are currently confused as Google does support Global TCP LB why it does not support with GKE Service. There no way to interface a Global TCP LB to a GKE service too.

2. Create a separate service of type Nodeport for traefik. Then expose this Nodeport Service using ingress-gce using a Global Static IP. Using this we instantly loose access to TCP and UDP services of Traefik as ingress-gce can only create a L7 HTTP(S) LB. which can only terminate http. We also lose a lot of other traefik features such as this https://github.com/kubernetes/ingress-gce/issues/699

what do you guys propose for exposing a Traefik like service to the internet in Google Cloud, in a scalable future-proof way? I have read a lot of different documentation both in gcp and here. Did not find something concrete. If you guys dont have any answers can you please point me towards a source for this. Thanks

**Comment by rramkumar1** [comment]
@yra-wtag Does [this](https://cloud.google.com/kubernetes-engine/docs/how-to/standalone-neg#use_with) help?

**Comment by yra-wtag** [comment]
@rramkumar1 Thanks. I studied it. It seemed that a lot of engineering is needed for that solution and cant really be said kubernetes like. However if thats the best solution Google has right now then we can give it a go. Is there any place in Google GKE where we can request these features to work more natively? Thanks again for your help.

**Comment by rramkumar1** [comment]
cc @markchurch for the feature request.

**Comment by rramkumar1** [comment]
cc @mark-church for the feature request.
