### ISSUE TITLE
Can't deploy ingress-nginx-internal on GKE Cloud 

### ISSUE THREAD

**Issue by 3j0s** [kubernetes/ingress-gce#1205]
Greetings!

I use GKE version 1.17.9-gke.600  <- I was working on 1.16 event that it didn't work for Google recomendation I upgrade to new version.

According with the documentation I'll try to deploy **ingress-gce** using **terraform helm provider** as follow:

`resource "helm_release" "ingress-nginx-internal" {
  name          = "ingress-nginx-internal"
  chart           = "gce-ingress"
  repository   = "https://kubernetes-charts.storage.googleapis.com"
  namespace = kube-system
  replace       = "true"

  values = [
    yamlencode(
    {
       nameOverride = "gke-cloud"
       controller = {
           images = {
               tag = "v1.5.2" <- trying to make it work 'cause I used 1.4.0 previously and it still didn't work
           }
       }
       rbac = {
         create = "true"
       }
       serviceAccount = {
         create = "true"
         name   = var.service_account_name
      }
      config = {
         fullname            = "internal-ingress-gce"
         tokenURL          = "nil"
         projectID           = var.project
         network             = var.network <-  enpoint network like: projects/_project_id_/global/networks/_network_uid_
         subnetwork       = var.subnetwork <- cidr_block
         nodeTags           = var.nodetags <- private
         nodeInstancePrefix = var.nodeinstanceprefix <- setting with the "name" before "main-pool"
      }
      secretKey = "gce-key" <- name of my secrets, the json name is key.json, just in case 
    })]
}
`
And this is the error that I got for logs:

`
I0803 17:21:24.621977       1 main.go:68] Starting GLBC image: "v1.4.0", cluster name ""
I0803 17:21:24.622129       1 main.go:69] Latest commit hash: "11515a06125fa1dfa8f767a938cf512a0a924425"
I0803 17:21:24.622135       1 main.go:71] argv[0]: "/glbc"
I0803 17:21:24.622139       1 main.go:71] argv[1]: "--gce-ratelimit=ga.Operations.Get,qps,10,100"
I0803 17:21:24.622144       1 main.go:71] argv[2]: "--gce-ratelimit=alpha.Operations.Get,qps,10,100"
I0803 17:21:24.622148       1 main.go:71] argv[3]: "--gce-ratelimit=ga.BackendServices.Get,qps,1.8,1"
I0803 17:21:24.622153       1 main.go:71] argv[4]: "--gce-ratelimit=ga.HealthChecks.Get,qps,1.8,1"
I0803 17:21:24.622157       1 main.go:71] argv[5]: "--gce-ratelimit=alpha.HealthChecks.Get,qps,1.8,1"
I0803 17:21:24.622161       1 main.go:71] argv[6]: "--verbose"
I0803 17:21:24.622165       1 main.go:71] argv[7]: "--default-backend-service=kube-system/ingress-nginx-internal-gke-cloud"
I0803 17:21:24.622180       1 main.go:71] argv[8]: "--sync-period=600s"
I0803 17:21:24.622184       1 main.go:71] argv[9]: "--running-in-cluster=true"
I0803 17:21:24.622188       1 main.go:71] argv[10]: "--use-real-cloud=true"
I0803 17:21:24.622192       1 main.go:71] argv[11]: "--config-file-path=/etc/gce/gce.conf"
I0803 17:21:24.622197       1 main.go:71] argv[12]: "--healthz-port=8086"
I0803 17:21:24.622202       1 main.go:74] Flags = {APIServerHost: ClusterName: ConfigFilePath:/etc/gce/gce.conf DefaultSvcHealthCheckPath:/healthz DefaultSvc:kube-system/ingress-nginx-internal-gke-cloud DefaultSvcPortName:http DeleteAllOnQuit:false GCERateLimit:{specs:[ga.Operations.Get,qps,10,100 alpha.Operations.Get,qps,10,100 ga.BackendServices.Get,qps,1.8,1 ga.HealthChecks.Get,qps,1.8,1 alpha.HealthChecks.Get,qps,1.8,1] isSet:true} GCEOperationPollInterval:1s HealthCheckPath:/ HealthzPort:8086 Features:0x2be50b0 InCluster:true IngressClass: KubeConfigFile: ResyncPeriod:10m0s Verbose:true Version:false WatchNamespace: NodePortRanges:{ports:[30000-32767] isSet:false} EnableBackendConfig:false NegGCPeriod:2m0s LeaderElection:{LeaderElectionConfiguration:{LeaderElect:true LeaseDuration:{Duration:15s} RenewDeadline:{Duration:10s} RetryPeriod:{Duration:2s} ResourceLock:configmaps} LockObjectNamespace:kube-system LockObjectName:ingress-gce-lock}}
I0803 17:21:24.622297       1 clients.go:51] Using in cluster configuration
F0803 17:21:24.636042       1 main.go:113] app.NewNamer(ctx.KubeClient, "", "") = failed to retrieve uid: configmaps "ingress-uid" is forbidden: User "system:serviceaccount:kube-system:default" cannot get resource "configmaps" in API group "" in the namespace "kube-system", returning empty name`

I've checked it out and I don't have **ingress-uid** but I have **ingress-nginx-internal-gke-cloud** instead, and I deployen on namespace **kube-system**.

Said all that, can anybody help me, please?
Thx  in advance

**Comment by rramkumar1** [comment]
> I've checked it out and I don't have ingress-uid but I have ingress-nginx-internal-gke-cloud instead, and I deployen on namespace kube-system.

Can you clarify what you mean? I don't quite understand.

**Comment by 3j0s** [comment]
Hi!

I was trying to deploy **gce-ingress** using **heml 3** as a provider of **terraform**, but at the end of the logs I got this error: 
`app.NewNamer(ctx.KubeClient, "", "") = failed to retrieve uid: configmaps "ingress-uid" is forbidden: User "system:serviceaccount:kube-system:default" cannot get resource "configmaps" in API group "" in the namespace "kube-system", returning empty name`

What I mentioned was that I checkout out an I realice that I don't have that **ingress-uid configmaps** builded in **kube-system** namespace, I tried to re-create it but still didn't work, so I'm stuck right there.
