### ISSUE TITLE
Rename this project from GLBC

### ISSUE THREAD

**Issue by bplotnick** [kubernetes/ingress-gce#1211]
It is an endless pit of confusion and frustration that GLBC and GCLB are so close. In discussion this makes it incredibly difficult to understand whether the person is talking about the load balancer or the controller or whether they meant to say one, but made a mistake and said the other. Not to mention the fact that I have to search Jira for both terms to find both things. I know naming things is hard, but this is a pretty clear example of a terrible name.

I can't even imagine what people with dyslexia feel about this.

Here's some suggestions you can have royalty free:
* ingress-gce - it's the title of the repo after all
* GCP Ingress Controller - or if you need to shorten it "GIC"
* Ingress Controller for GCP - ICG or if you want to make it hip: "Icy-G"

Here's a suggestion on what *not* to use:
* Google Balancer for Load Controller (GBLC)
* Google Cloud Load Balancer Controller (GCLBC)
* Anything related to Service Mesh

**Comment by rramkumar1** [comment]
@bplotnick Mind sending a PR? We are happy to change references to "GLBC" in documentation and code. We still do maintain a go binary called "glbc" which likely will be harder to change.
