### ISSUE TITLE
Kubernetes incorrectly warns with "invalid ingress configuration" when using the "allow-http: false" annotation

### ISSUE THREAD

**Issue by jmound** [kubernetes/ingress-gce#1214]
On GKE, creating an Ingress with a managed certificate and disabling http as described in [Disabling HTTP](https://cloud.google.com/kubernetes-engine/docs/concepts/ingress-xlb#disabling_http) via the annotation: `kubernetes.io/ingress.allow-http: "false"` generates a warning:

GKE v1.17.8-gke.17:
```
kubectl version |grep Server
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.8-gke.17", GitCommit:"cd7ca396c79d2e8f3fdb06c6865549770091d431", GitTreeState:"clean", BuildDate:"2020-07-20T22:12:03Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```
Steps to reproduce:
```
$ kubectl get -n frontend ingress 
No resources found in frontend namespace.
$ grep allow app/store/cluster/in-scope/namespaces/frontend/ingress.yaml 
    kubernetes.io/ingress.allow-http: "false"
$ kubectl -n frontend apply -f .../ingress.yaml 
ingress.networking.k8s.io/frontend created
$ kubectl -n frontend describe ingress frontend
Name:             frontend
Namespace:        frontend
Address:          34.120.228.7
Default backend:  default-http-backend:80 (10.4.1.11:8080)
Rules:
  Host        Path  Backends
  ----        ----  --------
  *           
              /*   frontend:80 (10.4.1.4:8080)
Annotations:  ingress.gcp.kubernetes.io/pre-shared-cert: mcrt-REDACTED
              ingress.kubernetes.io/backends: {"k8s-be-31403--REDACTED":"HEALTHY","k8s-be-31818--REDACTED":"HEALTHY"}
              ingress.kubernetes.io/https-forwarding-rule: k8s2-fs-888jw4sk-frontend-frontend-REDACTED
              ingress.kubernetes.io/https-target-proxy: k8s2-ts-888jw4sk-frontend-frontend-REDACTED
              ingress.kubernetes.io/ssl-cert: mcrt-REDACTED
              ingress.kubernetes.io/url-map: k8s2-um-888jw4sk-frontend-frontend-REDACTED
              kubernetes.io/ingress.allow-http: false
              kubernetes.io/ingress.global-static-ip-name: frontend-ext-ip
              networking.gke.io/managed-certificates: frontend
Events:
  Type     Reason  Age   From                     Message
  ----     ------  ----  ----                     -------
  Normal   ADD     97s   loadbalancer-controller  frontend/frontend
  Warning  Sync    54s   loadbalancer-controller  Error during sync: error running load balancer syncing routine: loadbalancer 888jw4sk-frontend-frontend-REDACTED does not exist: invalid ingress frontend configuration, please check your usage of the 'kubernetes.io/ingress.allow-http' annotation.
  Normal   CREATE  37s   loadbalancer-controller  ip: (REDACTED)
```

The warning message appears even when using the annotation as documented: " Warning  Sync    54s   loadbalancer-controller  Error during sync: error running load balancer syncing routine: loadbalancer 888jw4sk-frontend-frontend-REDACTED does not exist: invalid ingress frontend configuration, please check your usage of the 'kubernetes.io/ingress.allow-http' annotation." 

Contents of `ingress.yaml`:
```
$ cat app/store/cluster/in-scope/namespaces/frontend/ingress.yaml 
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: frontend
  annotations:
    kubernetes.io/ingress.global-static-ip-name: frontend-ext-ip
    kubernetes.io/ingress.allow-http: "false"
    networking.gke.io/managed-certificates: frontend
spec:
  rules:
  - http:
      paths:
        - path: "/*"
          backend:
            serviceName: frontend
            servicePort: 80
```
It does not appear to be related to the status of the ManagedCertificate:
```
$ kubectl -n frontend describe managedcertificates.networking.gke. frontend
Name:         frontend
Namespace:    frontend
Labels:       <none>
Annotations:  API Version:  networking.gke.io/v1beta2
Kind:         ManagedCertificate
Metadata:
  Creation Timestamp:  2020-08-12T18:35:56Z
  Generation:          4
  Resource Version:    443128
  Self Link:           /apis/networking.gke.io/v1beta2/namespaces/frontend/managedcertificates/frontend
  UID:                 REDACTED
Spec:
  Domains:
    store.REDACTED.com
Status:
  Certificate Name:    mcrt-REDACTED
  Certificate Status:  Active
  Domain Status:
    Domain:     store.REDACTED.com
    Status:     Active
  Expire Time:  2020-11-10T10:47:37.000-08:00
Events:         <none>
```

This is possibly related to #1001, however the `WillNotConfigureFrontend` event is not seen.

**Comment by rramkumar1** [comment]
@jmound The `allow-http` annotation has always been a stopgap and sort of brittle. Would you use redirects once those are supported? The PRs to support redirects are merged.

**Comment by rramkumar1** [comment]
@jmound You are experiencing the same issue as #1001. Ignore the lack of the `WillNotConfigureFrontend` keyword, we removed it for other reasons but the underlying error is the same.

I believe right now this needs to be a two-step process. You need to first configure a HTTP + HTTPS LB with a ManagedCert and once that is fully programmed, then add the `allow-http: false`.

**Comment by rramkumar1** [comment]
@jmound Correction on above after investigating more:

I retract the statement that this should be a two-step process. It can be accomplished in one step, its just that the provisioning of the LB will fail for some time until the ManagedCertificate controller applies the certificate to the Ingress.

**Comment by jmound** [comment]
Thanks, that helps. Do you have any thoughts on improving the warning message? To someone creating the Ingress resource, the below message heavily implies that the actual Ingress configuration is invalid, that a mistake was made and something needs to be fixed. 

```
Warning  Sync    54s   loadbalancer-controller  Error during sync: error running load balancer syncing routine: loadbalancer 888jw4sk-frontend-frontend-REDACTED does not exist: invalid ingress frontend configuration, please check your usage of the 'kubernetes.io/ingress.allow-http' annotation.
```

**Comment by rramkumar1** [comment]
@jmound I think that's a reasonable request. What I am thinking is that if you are using ManagedCertificates then this message is a bit different than if you are not using it. What do you think of this:

```
Error during sync: error running load balancer syncing routine: loadbalancer 888jw4sk-frontend-frontend-REDACTED does not exist: invalid ingress frontend configuration. If you are using ManagedCertificates then please ignore this error.
```

**Comment by jmound** [comment]
Unless I'm mistaken, it's not an invalid configuration. If that's the case, then that line should be removed. From a previous comment:

> ...its just that the provisioning of the LB will fail for some time until the ManagedCertificate controller applies the certificate to the Ingress.

How about something along the lines of: `LoadBalancer provisioning in progress, waiting for ManagedCertificate status to update` ? I'm not familiar with the exact workflow of the managed certificate controller, so that probably needs to be modified to be more accurate. But the main point is that if the ingress config with the managed cert annotation is a correct, valid configuration, we shouldn't be messaging otherwise.

**Comment by rramkumar1** [comment]
Sure that sounds better, although its going to be a bit painful to rip out this part of the message due to layering in the code:

```
Error during sync: error running load balancer syncing routine:
```

What about something like this?

```
Error during sync: error running load balancer syncing routine: waiting for ManagedCertificate status to update
```

**Comment by jmound** [comment]
Why state that it is an error at all?

This config is what the docs currently state is the correct thing to do. I understand that the Ingress config is described in two separate sections ( [Disabling HTTP](https://cloud.google.com/kubernetes-engine/docs/concepts/ingress-xlb#disabling_http) and [Setting up the managed certificate](https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs#setting_up_the_managed_certificate) ), and that there is an aspect of using Google Managed Certs that is marked as beta. However, if this is the correct way to declare an Ingress with a managed certificate, then to me ingress-gce shouldn't be throwing an error at all.

That being said, that message is clear enough that there isn't an invalid config, and that the correct course of action is to wait.

**Comment by rramkumar1** [comment]
I agree that its not. Reason for my comment was that I thought it would take a bit of refactoring to make it so that this Event is not prepended with an error message.

However, I double-checked the code and I think it can be accomplished without any refactoring.

**Comment by jmound** [comment]
@rramkumar1 As a data point, there are folks still seeing this message and justifiably misinterpreting it as something that needs to be addressed.

**Comment by zioproto** [comment]
It is now possible to create an Ingress with HTTP to HTTPS redirects enabled:
https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#https_redirect

This should be better than using the annotation `allow-http: false`

**Comment by zioproto** [comment]
@rramkumar1 I am reading https://cloud.google.com/kubernetes-engine/docs/concepts/ingress-xlb#disabling_http and https://github.com/kubernetes/ingress-gce/issues/1214#issuecomment-679155619

From the documentation this fact that the `kubernetes.io/ingress.allow-http: "false"` annotation used in GKE conflicts with other annotations `networking.gke.io/managed-certificates` is not clear.

What is the long term plan to fix this behaviour ?

I see at least 2 actionable things to do:
* Make Kubernetes print a better error message
* Update the GKE documentation to avoid people configuring the 2 annotations that conflict to each other.

Thanks
