### ISSUE TITLE
Release versions discrepancy between Releases, Changelog, Readme & main GitHub repo page

### ISSUE THREAD

**Issue by sbocinec** [kubernetes/ingress-gce#1216]
There is a discrepancy in list of releases accross the project what makes it really confusing to navigate through the releases. At the time of submitting the issue, this is the situation:

1. [ingress-gce](https://github.com/kubernetes/ingress-gce) GitHub main page displays v`1.8.0` as the latest release:
![Screenshot from 2020-08-14 14-20-39](https://user-images.githubusercontent.com/4834459/90248730-87bc7b00-de39-11ea-8589-59738dfaf6db.png)
2. [ingress-gce GitHub Releases section](https://github.com/kubernetes/ingress-gce/releases) says there is v`1.10.1` latest version available 
![Screenshot from 2020-08-14 14-23-14](https://user-images.githubusercontent.com/4834459/90248844-ba667380-de39-11ea-83cd-45068b648617.png)
3. [ingress-gce CHANGELOG.md](https://github.com/kubernetes/ingress-gce/blob/master/CHANGELOG.md) documents changes for the v`1.9.5` as the latest version
![Screenshot from 2020-08-14 14-24-06](https://user-images.githubusercontent.com/4834459/90248989-fb5e8800-de39-11ea-99e6-4ed886a94795.png)
4. [GKE version mapping in the ingress-gce README.md](https://github.com/kubernetes/ingress-gce#gke-version-mapping) mentions v`1.9.7` used in the newest GKE available
![Screenshot from 2020-08-14 14-26-31](https://user-images.githubusercontent.com/4834459/90249108-2c3ebd00-de3a-11ea-9fb2-8c099d7acbd6.png)

It would be great if it's possible to fix these discrepancies, it would really help to avoid the confusion and understand the project better.
 
Thanks in advance!

**Comment by rramkumar1** [comment]
@sbocinec Apologies for the confusion. We are working on fixing this.

**Comment by spencerhance** [comment]
Looks like we are still missing the releases

**Comment by tonglil** [comment]
It would be great if we can know what version the cluster is using via the cloud console or `kubectl describe ingress` or somewhere directly since a lot of this information is a guessing game to match it up with the cluster version and release note combing.
