### ISSUE TITLE
Public Docker images

### ISSUE THREAD

**Issue by asgoel** [kubernetes/ingress-gce#1271]
Where should I be looking for the registry of docker images for ingress-gce? I'm looking here: https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/ingress-gce-glbc-amd64?gcrImageListsize=30 and the latest release seems to only be 1.9.1. Are they now somewhere else?

**Comment by rramkumar1** [comment]
@asgoel Can I ask why you need them?

**Comment by asgoel** [comment]
@rramkumar1 we run our own version of ingress-gce to get bleeding edge updates before they are released into GKE (for example, the frontend configs with custom ssl policies before they were available, and now HTTP -> HTTPS redirects)

**Comment by rramkumar1** [comment]
@spencerhance Anything you can add here?

**Comment by asgoel** [comment]
@spencerhance @rramkumar1 any update here?
