### ISSUE TITLE
Update to use Ingress and IngressClass networking.k8s.io/v1 APIs before v1.22

### ISSUE THREAD

**Issue by liggitt** [kubernetes/ingress-gce#1301]
Ingress and IngressClass APIs earlier than networking.k8s.io/v1 are deprecated and scheduled to no longer be served in Kubernetes v1.22

The networking.k8s.io/v1 APIs are available starting in v1.19

/cc @robscott

**Comment by swetharepakula** [comment]
This is still in progress.
/remove-lifecycle stale

**Comment by robscott** [comment]
This is still in progress. 

/remove-lifecycle rotten

**Comment by brondum** [comment]
any updates on supporting `spec.ingressClassName`?

**Comment by visheyra** [comment]
I stumbled some time ago on this issue, and one of the google guy I can exchange with shared me this documentation https://cloud.google.com/kubernetes-engine/docs/how-to/custom-ingress-controller#controller_summary TL;DR you can configure ingressClass but you'll have to specify the annotation as well. This is working fine on a 1.21 cluster, I plan to test in 1.22 soon

**Comment by swetharepakula** [comment]
This issue was concerning the APIs that ingress-gce was using to manage ingress resources. Since the controller now only uses the v1 API this issue can be closed.

Please open a new issue for `ingressClassName` support if still desired.
