### ISSUE TITLE
Feature: Support custom TLS certificates when using HTTPS to the backends

### ISSUE THREAD

**Issue by Ares3266** [kubernetes/ingress-gce#1305]
I'd like to be able to configure the certificates that the LB uses to re-encrypt traffic to the backend services. The use case being that I want to be able to build a strong cryptographic identity of north-south traffic (managed by GCE) into my service mesh.

Google already supports defining which scheme to use through the `service.alpha.kubernetes.io/app-protocols` annotation, however our service mesh does not trust that traffic; it does not trust the certificate it originates from. 

The Service Mesh in question here is Consul - and I've [raised an issue with them](https://github.com/hashicorp/consul/issues/9056) too to determine how they can ~~better~~ actually support external Ingress controllers, however the abstract concept of being able to configure the root of trust that the LB uses to re-encrypt traffic -- so that any external service mesh can use this pattern -- is probably something that GCE should support

**Comment by enj** [comment]
/reopen
/remove-lifecycle rotten

This seems like valuable functionality to have 😄

**Comment by plgingembre** [comment]
We currently do not verify the cert issued to the backend. TLS to the backend is on our roadmap.
