### ISSUE TITLE
Can't provision an ingress with ManagedCertificate

### ISSUE THREAD

**Issue by smaslennikov** [kubernetes/ingress-gce#1334]
Updated my GKE cluster and nodes from 1.17 to 1.18 - this issue persisted in both 1.18 releases (the newest 1.18.10-gke.2101 one as well). 

`Error syncing to GCP: error running load balancer syncing routine: error getting secrets for Ingress: secret "" does not exist`

I assume the culprit is that the ManagedCertificate is not yet provisioned, but it can't provision if the ingress doesn't forward traffic yet (fails provisioning with `FAILED_NOT_VISIBLE`).

Looks like NEGs are now default, I've disabled that in the service and the issue persisted.

**Comment by integrii** [comment]
I have this issue as well.  Not sure whats going on yet.  Running on 1.17 here.

`  Warning  Sync    2m53s (x221 over 22h)  loadbalancer-controller  Error syncing to GCP: error running load balancer syncing routine: error getting secrets for Ingress: secret "" does not exist`

**Comment by Nishaal-Tailor** [comment]
Remove the `tls` section in your spec:
```yaml
tls:
- hosts:
  - example.com
