### ISSUE TITLE
NEG endpoints not getting updated with the new deployments 

### ISSUE THREAD

**Issue by santoshrajusagi** [kubernetes/ingress-gce#1357]
As per the GKE ingress controller docs, NEGs will be created automatically with each endpoint in the group pointing to the target Pod IP address and port right? In our case, those endpoint IP addresses and ports are not getting updated if new pods are getting created by the deployment and those endpoints end up having old pod IPs and the reason our backend services are staying in the UNHEALTHY state all the time and the ingress is returning 502s.

I'm also seeing the following error message in the service events section which might be related to the above issue.
<img width="1498" alt="Screenshot 2021-01-20 at 5 42 59 PM" src="https://user-images.githubusercontent.com/58718147/105215799-c0464a80-5b77-11eb-8ac7-55510b73f858.png">

I have dug through the ingress-gce codebase and this is where the error is being reported - 
https://github.com/kubernetes/ingress-gce/blob/master/pkg/neg/manager.go#L165

Interesting thing is that I was able to fix it if I completely remove the existing ingress service and create a new ingress with a new deployment. I can see NEGs getting created with desired endpoint IPs and ports from that point and then we hit this issue again after few days with new deployments.

**Comment by Omasumasu** [comment]
I faced same issue today's morning.
Is there any solution to solve it?

**Comment by Omasumasu** [comment]
I found it, if anyone edit svc resource manually using `kubectl edit`, and not matching with `kubectl.kubernetes.io/last-applied-configuration` it happened.
I tried to remove resource and recreate it, the error was not shown.

**Comment by swetharepakula** [comment]
Thanks for opening this issue!

This looks like a known bug in the NEG controller that was fixed with https://github.com/kubernetes/ingress-gce/pull/1342. This is available starting from v1.10.13 which is in GKE versions 1.18.12-gke.1201+, 1.19.5-gke.800+, 1.17.13-gke.2600+ and all 1.20 and 1.21 clusters.

**Comment by freehan** [comment]
/close

reopen if needed.
