### ISSUE TITLE
Orphaned Resources After Cluster Delete

### ISSUE THREAD

**Issue by danehans** [kubernetes/ingress-gce#136]
After running the following commands, I see orphaned resources that were created by the gce ingress controller:

```
$ kubectl delete ing $ING -n $ING_NAMESPACE
$ gcloud container clusters delete $CLUSTER_NAME
```
List of orphaned resources:
```
$ gcloud compute instance-groups list
NAME                      LOCATION    SCOPE  NETWORK  MANAGED  INSTANCES
k8s-ig--6c90c323237f439e  us-west1-a  zone   default  No       0
k8s-ig--71cb3990c3cf10a6  us-west1-a  zone   default  No       0

$ gcloud compute backend-services list
NAME                            BACKENDS                                            PROTOCOL
k8s-be-30286--71cb3990c3cf10a6  us-west1-a/instanceGroups/k8s-ig--71cb3990c3cf10a6  HTTP
k8s-be-31225--6c90c323237f439e  us-west1-a/instanceGroups/k8s-ig--6c90c323237f439e  HTTP
k8s-be-31253--6c90c323237f439e  us-west1-a/instanceGroups/k8s-ig--6c90c323237f439e  HTTP
k8s-be-31345--71cb3990c3cf10a6  us-west1-a/instanceGroups/k8s-ig--71cb3990c3cf10a6  HTTP
k8s-be-31823--6c90c323237f439e  us-west1-a/instanceGroups/k8s-ig--6c90c323237f439e  HTTP
k8s-be-32421--71cb3990c3cf10a6  us-west1-a/instanceGroups/k8s-ig--71cb3990c3cf10a6  HTTP

$ gcloud compute url-maps list
NAME                                             DEFAULT_SERVICE
k8s-um-fortio-fortio-ingress--6c90c323237f439e   backendServices/k8s-be-31253--6c90c323237f439e
k8s-um-fortio-fortio-ingress--71cb3990c3cf10a6   backendServices/k8s-be-30286--71cb3990c3cf10a6
k8s-um-fortio-fortio-ingress2--6c90c323237f439e  backendServices/k8s-be-31823--6c90c323237f439e

$ gcloud compute target-http-proxies list
NAME                                             URL_MAP
k8s-tp-fortio-fortio-ingress--71cb3990c3cf10a6   k8s-um-fortio-fortio-ingress--71cb3990c3cf10a6
k8s-tp-fortio-fortio-ingress2--6c90c323237f439e  k8s-um-fortio-fortio-ingress2--6c90c323237f439e

$ gcloud compute forwarding-rules list
NAME                                             REGION    IP_ADDRESS      IP_PROTOCOL  TARGET
a38f1bb8811e511e89c5b42010a8a013                 us-west1  35.197.65.23    TCP          us-west1/targetPools/a38f1bb8811e511e89c5b42010a8a013
a5f61b2bd126f11e89c5b42010a8a013                 us-west1  35.203.177.233  TCP          us-west1/targetPools/a5f61b2bd126f11e89c5b42010a8a013
ac78780fb11e111e8858442010a8a020                 us-west1  35.230.48.211   TCP          us-west1/targetPools/ac78780fb11e111e8858442010a8a020
k8s-fw-fortio-fortio-ingress--71cb3990c3cf10a6             35.227.193.162  TCP          k8s-tp-fortio-fortio-ingress--71cb3990c3cf10a6
k8s-fw-fortio-fortio-ingress2--6c90c323237f439e            35.190.69.114   TCP          k8s-tp-fortio-fortio-ingress2--6c90c323237f439e
```

I would expect the gce ingress controller to remove these resources when the ingress or cluster is deleted.

**Comment by nicksardo** [comment]
This is a known issue and being worked on.

**Comment by danehans** [comment]
@nicksardo Can you share a link to the known issue? I searched through the repo issue list before opening this issue and could not find a match.

**Comment by nicksardo** [comment]
@danehans The issue is internal to Google. When you delete the cluster, GKE does not wait for the ingress controller to clean up resources. If you want to avoid orphaning resources, delete all the ingress objects and then wait for all the related GCP resources to be deleted prior to calling `gcloud container clusters delete...`

You can delete the orphan resources through the UI or via `gcloud`.
Within GCP Console, go to Network Services->Load Balancing and delete the orphaned load balancers. Click on the "advanced" link to see if any resources remain (like backend services) and delete them too.
If you want to use gcloud, start at the front of the load balancer resources and work backwards (the opposite order you have listed)

**Comment by danehans** [comment]
I have been manually deleting the resources using `gcloud`. For others that may come across this issue:
```
$ gcloud compute forwarding-rules delete $ROUTE_RULE_NAME --global -q
$ gcloud compute target-http-proxies delete $TARGET_HTTP_PROXIES -q
$ gcloud compute url-maps delete $URL_MAPS -q
$ gcloud compute backend-services delete --global -q $BACKEND_SERVICES
$ gcloud compute instance-groups unmanaged delete -q $K8S_INSTANCE_GROUPS
```

**Comment by ahmetb** [comment]
@danehans there are a few more to delete:

    gcloud compute health-checks delete -q [NAME]
    gcloud compute firewall-rules delete -q [NAME]

Also the static IPs that are not used are actually billed, so if you want to release that:

    gcloud compute addresses delete --global -q [NAME]

**Comment by TxsAdamWest** [comment]
Any update on this?

**Comment by bowei** [comment]
GKE currently gives a grace period to allow the controller to delete the resources, so the resources should get a chance to be deleted. It may be that the controller is taking longer than the grace period to do the GC, which we are working on.

**Comment by clehene** [comment]
@nicksardo are these phantom LBs still being worked on?
This is a good example of how eventual consistency can make things hard to impossible. Deleting an ingress and creating another ingress with the same name is even more interesting. Tooling reports some certificates while in reality, it uses the old ones. The list goes on. Managing these idiosyncrasies feels more like voodoo :)

**Comment by michaela-elise** [comment]
gcloud beta compute forwarding-rules list | cut -d ' ' -f1 | xargs -I{} gcloud beta compute forwarding-rules delete {} --global
gcloud beta compute target-http-proxies list | cut -d ' ' -f1 | xargs -I{} gcloud beta compute target-http-proxies delete {} --global
gcloud beta compute url-maps list | cut -d ' ' -f1 | xargs -I{} gcloud beta compute url-maps delete {} --global
gcloud beta compute backend-services list | cut -d ' ' -f1 | xargs -I{} gcloud beta compute backend-services delete {} --global

**Comment by hasheddan** [comment]
@nicksardo any updates on this issue?

**Comment by bowei** [comment]
Finalizers are now fully supported, so I would consider the ingress-gce side of things to be closed.
Please reopen if the finalizers are not working properly. (Premature stoppage of the controller is a different issue)

/close

**Comment by hasheddan** [comment]
@bowei it seems like this issue encompasses firewall rules not being cleaned up when a cluster is deleted, which still occurs due to premature stoppage of the ingress controller. I am assuming this will not be solved here, but I also do not think the core of this issue has been addressed.

**Comment by christian-kreuzberger-dtx** [comment]
> it seems like this issue encompasses firewall rules not being cleaned up when a cluster is deleted

I just saw that issue, it caused a problem for us.

**Comment by KenTheWhaleGoddess** [comment]
Bump.

**Comment by taihen** [comment]
This is still an issue.

**Comment by bowei** [comment]
The reason the issue is closed is because the logic required in the controller itself is sufficient for cleanup. 

What is causing orphaned resources is actually the behavior of the control plane shutting down controllers before they have a chance to clean up; the controller can't do anything about it if it is no longer running. 

I would recommend opening a bug against (GKE?) about the fact that when a cluster is deleted, the deletion does not wait for resource teardown to complete before shutting down.

The workaround is to have a loop that waits for resources to go away before deletion -- do a `for` loop over all namespaces and delete all resources, then wait for resources to be finalized.
