### ISSUE TITLE
"internal" ingresses

### ISSUE THREAD

**Issue by caarlos0** [kubernetes/ingress-gce#138]
Hey!

Sorry if this is not the right place to ask or if I'm missing something, but, I wonder how can I create ingress with "internal" IPs (visible only inside the VPC)?

As far as I looked into, it only creates ingress with addresses like 35.x.x.x. I tried internal load balancers as well, which work, but there is 5 LB limit and I need **a lot** more than that.

Thanks!

**Comment by nicksardo** [comment]
GCP does not have an internal HTTP(S) LB. 

The HTTP(S) LB also utilizes backend services (I'm assuming you're seeing the quota of 5), so switching to L7 wouldn't help you. I recommend you go back to using the ILB and request more quota.

**Comment by kupson** [comment]
It looks like GCP have internal HTTP(S) Load Balancers now - https://cloud.google.com/load-balancing/docs/l7-internal/setting-up-l7-internal

**Comment by MrHohn** [comment]
I believe this is happening. Ref https://github.com/kubernetes/ingress-gce/issues/731.
cc @spencerhance
