### ISSUE TITLE
Feature: Support selecting network tier and scope

### ISSUE THREAD

**Issue by cezarsa** [kubernetes/ingress-gce#1380]
Currently it's not possible to create a `Standard` tier external L7LB using Ingress objects. Even if the project default tier is set to `Standard` the ingress controller fails[1] because it tries to create a LB with a `global` scope and there's no way to specify a `regional` scope.

For L4 LBs created using Services with type `LoadBalancer` the custom annotation `cloud.google.com/network-tier: Standard` was introduced in https://github.com/kubernetes/kubernetes/pull/88487 to solve this problem.

Would it be possible to use this same strategy for Ingresses while also allowing a custom scope or using a CRD (FrontendConfig?) would be more appropriate? I'd be willing to work on a PR if this change is desired.

[1] - Error event message:
```
Error 400: STANDARD network tier (the project's default network tier) is not supported: STANDARD network tier is not supported for global forwarding rule., badRequest
```

**Comment by freehan** [comment]
This is not possible to achieve today due to the google cloud LB does not support this setup. 

Ideally, Google Cloud LB supports regional external LB. Then standard network tier can be applied.

**Comment by freehan** [comment]
Closing the issue. Reopen if needed.

**Comment by huynqtiki** [comment]
https://cloud.google.com/network-tiers/docs/overview
@fredkan actually HTTP(S) Load Balancing does support regional external LB via standard network tier ?

I can confirm this if I created it manually 
![image](https://user-images.githubusercontent.com/26454669/129396093-ca835d8c-0df0-41f6-a6b9-11743cd593e9.png)
![image](https://user-images.githubusercontent.com/26454669/129396352-acf1a9c7-c123-4432-8ede-511929d613d6.png)

In my case it's a needed feature, can we reopen this ?

**Comment by Vlad1mir-D** [comment]
@freehan Why closed? Google Cloud LB supports regional external LB indeed!
https://cloud.google.com/load-balancing/docs/https#load-balancer-mode:
> Global external HTTP(S) load balancer (classic). This is the classic external HTTP(S) load balancer that is global in Premium Tier but can be configured to be regional in Standard Tier. This load balancer is implemented on Google Front Ends (GFEs). GFEs are distributed globally and operate together using Google's global network and control plane.
