### ISSUE TITLE
port based routing:: allow port in host for rules

### ISSUE THREAD

**Issue by humblewolf** [kubernetes/ingress-gce#1388]
spec:
  rules:
    - host: app.example.com:5000 <<----- something like this
      http:
        paths:
          - path: "/*"
            backend:
              serviceName: my-service
              servicePort: 5005

--------------------------------------------------------------------

I know it can be argued that why one would design his apis like this (hitting some port other than 80/443 in request). 

Apart from http -> https routing (which you guys provide support via another mechanism) this can be useful to people migrating to kubernetes from bare-metal installation and listening at various ports with their client code already in thousands of apps.

**Comment by mark-church** [comment]
Is the request to define the listening port on the http load balancer that's deployed by Ingress resource?

The newly introduced GKE Gateway controller does actually allow the listening port to be specified, however the TCP load balancers only support three ports (80, 8080, and 443): https://cloud.google.com/kubernetes-engine/docs/how-to/gatewayclass-capabilities#gateway

What additional listening ports would you want? How many? For what use-cases or apps specifically that are hard-coded to use something other than 80/443?
