### ISSUE TITLE
Set namespace for BackendConfig.iap.oauthclientCredentials

### ISSUE THREAD

**Issue by dinvlad** [kubernetes/ingress-gce#1393]
Hi folks,

It appears that currently, `BackendConfig` for IAP requires the OAuth client secret to be located in the same namespace [1]. Could you add an option to specify the namespace for the secret?

Our use case for this is to have one secret shared among multiple services deployed within the same cluster. Each service is deployed in a separate namespace, making it inconvenient and error-prone having to create the same secret across multiple namespaces currently.

Thanks

[1] https://github.com/kubernetes/ingress-gce/blob/051cfde145f34c8721e39df778e262fb4a256c67/pkg/backendconfig/validation.go#L69

**Comment by mark-church** [comment]
This is not currently possible with BackendConfig. The Gateway API is being developed to significantly improve Ingress however. We just had our preview release: https://cloud.google.com/kubernetes-engine/docs/concepts/gateway-api

Currently Gateway supports the BackendConfig in the same way that Ingress does (1 per service, Namespace-scoped). However, we plan to improve how service policy and configuration is done with Gateway for use-cases like this. I'd be interested in getting your feedback on this document which is an early proposal for having a hierarchical system for defining policy for things like IAP: https://docs.google.com/document/d/1Wh52e7pupV0H1lEA5l_sqDmvRC7lk2cf1fufCz8vxzM/edit?usp=sharing

It is an early proposal in the OSS, probably 1-2 quarters from actually getting into the product in GKE, but your use-case (defining auth centrally for many services across namespace boundaries) is exactly one of the use-cases it could address. It would be great to get your and anybody else's feedback on this. Thanks!

**Comment by dinvlad** [comment]
Great, was not aware of that - sounds very interesting! Closing this one for now.
