### ISSUE TITLE
Switching Clusters by Switching LB IP address takes 7 min

### ISSUE THREAD

**Issue by mikosa** [kubernetes/ingress-gce#1413]
Hello
Sometimes we need to do some major updates in our cluster so we do this work on a new cluster instead. When we r done, we then switch the new cluster with the old live cluster.
we are doing this by deleting the ingress in the old cluster to free the ip address, then we apply the ip to the new cluster ingress. The new cluster loadbalancer takes forever to start serving the requests (around 5 min)

Is there a way to improve this downtime?

**Comment by mark-church** [comment]
Use multi-cluster ingress or multi-cluster gateways that allows you to share a VIP between two clusters. It was built for this exact purpose:

- https://cloud.google.com/kubernetes-engine/docs/concepts/multi-cluster-ingress
- https://cloud.google.com/kubernetes-engine/docs/how-to/deploying-multi-cluster-gateways

**Comment by freehan** [comment]
Reopen if needed.
