### ISSUE TITLE
ingress-gce-404-server-with-metrics causes OOM

### ISSUE THREAD

**Issue by jupblb** [kubernetes/ingress-gce#1426]
We encountered a scenario where [404-server-with-metrics](https://github.com/kubernetes/ingress-gce/blob/master/cmd/404-server-with-metrics) can cause OOM exception. This is probably caused by logs being partially retained in the memory. When someone pings the cluster a lot (e.g. botnet looking for vulnerabilities) this causes a surge in the amount of log messages being written. Example:
```
...
I0505 11:27:49.607462 1 server-with-metrics.go:243] response 404 (backend NotFound), service rules for [ /header.html ] non-existent
I0505 11:27:49.707176 1 server-with-metrics.go:243] response 404 (backend NotFound), service rules for [ /q79w_38jg__.shtml ] non-existent
I0505 11:27:49.707220 1 server-with-metrics.go:243] response 404 (backend NotFound), service rules for [ /gk/public_html/ ] non-existent
...
```
Which in turn may cause [the container](https://github.com/kubernetes/kubernetes/blob/e74ef5301a2eef1d5aca61a32eec2bf2bddda2d6/cluster/addons/cluster-loadbalancing/glbc/default-svc-controller.yaml) to hit the memory limit.

/cc @mborsz

**Comment by mborsz** [comment]
In fact it's not logs being kept in memory. Those looks good.

I have done a following experiment:
* Modified code to add /debug/pprof/heap
* Ran 'curl' test from the README.md
* Checked docker stats (it was ~400MiB)
* Fetched pprof for the memory and...

![image](https://user-images.githubusercontent.com/2559168/117180394-6db23680-add4-11eb-91d6-afb7ae91bd19.png)

it looks like vast majority of memory is being allocated in lines https://github.com/kubernetes/ingress-gce/blob/b1a745203c5465c6a59056acc2233da37b36402e/cmd/404-server-with-metrics/server-with-metrics.go#L99-L107

It looks like on each server.idleChannel update (which happens every request) we allocate a new time.Timer which then lives for the next *idleLogTimer (1h by default)

This matches the documentation of time.After (src: https://golang.org/pkg/time/#After):

```
The underlying Timer is not recovered by the garbage collector until the timer fires. If efficiency is a concern, use NewTimer instead and call Timer.Stop if the timer is no longer needed.
```

**Comment by spencerhance** [comment]
cc: @skmatti @vbannai

**Comment by vbannai** [comment]
A simple step like the following would suffice? 
I have not verified but this will get away from allocated a new time.Timer for each request received. 

 go func() { 
       timeout := time.After(*idleLogTimer)
 	for { 
 		select { 
 		case <-server.idleChannel: 
 		case <-timeout: 
 			klog.Infof("No connection requests received for 1 hour\n") 
 		} 
 	} 
 }()

**Comment by vbannai** [comment]
It might be better to call allocate using NewTimer() and call timer.Stop() when the idleChannel lights up. That way we are cleaning up the timers as and when requests are received keeping the memory footprint down.

**Comment by nokernel** [comment]
This issue still exist.

**Comment by ratelle** [comment]
I'd like to assign this issue to myself and work on a small PR to fix it.
