### ISSUE TITLE
Consider Emitting Events for GC errors

### ISSUE THREAD

**Issue by freehan** [kubernetes/ingress-gce#143]
GC should record event when error occurs. Some GC problem needs user attention to fix. For instance, if user reference resources created by ingress controller from other manual configured resources. These resources could not be GCed. ingress controller will end up GC it forever and logging on the master while user gets zero signal to about the problem.

**Comment by nicksardo** [comment]
Question is where to emit events for GC since GC is not tied to a specific ingress.

**Comment by swetharepakula** [comment]
Closing. GC events have been added.
