### ISSUE TITLE
Have performance issue if Cloud CDN is enabled

### ISSUE THREAD

**Issue by WLun001** [kubernetes/ingress-gce#1469]
I found out that GKE Ingress (with Cloud CDN) is way slower than GKE Ingress (without Cloud CDN), when testing against hello-world API server written in Go, (wait for 200ms and return response). Here is the benchmark results, access through public IP address, no DNS, no HTTPS, not cacheable by CDN and no server-side caching.

Tested enabled Cloud CDN from backend config CRD or from Cloud console, workload were running on GKE autopilot

**With Cloud CDN**
```
$ bombardier -c 200 -n 100000 IP_ADDRESS

Bombarding IP_ADDRESS with 100000 request(s) using 200 connection(s)
 100000 / 100000 [=====] 100.00% 197/s 8m25s
Done!
Statistics        Avg      Stdev        Max
  Reqs/sec       206.84     622.51    7707.32
  Latency         1.01s   410.20ms      5.48s
  HTTP codes:
    1xx - 0, 2xx - 100000, 3xx - 0, 4xx - 0, 5xx - 0
    others - 0
  Throughput:    52.75KB/s
```

**Without Cloud CDN**
```
$ bombardier -c 200 -n 100000 IP_ADDRESS

Bombarding IP_ADDRESS with 100000 request(s) using 200 connection(s)
 100000 / 100000 [=====] 100.00% 885/s 1m52s
Done!
Statistics        Avg      Stdev        Max
  Reqs/sec       899.61     760.42   10838.69
  Latency      225.16ms    17.68ms   533.07ms
  HTTP codes:
    1xx - 0, 2xx - 100000, 3xx - 0, 4xx - 0, 5xx - 0
    others - 0
  Throughput:   197.52KB/s
```
**with service type `Load Balancer`**

```
$ bombardier -c 200 -n 100000 IP_ADDRESS

 Bombarding IP_ADDRESS/ with 100000 request(s) using 200 connection(s)
 100000 / 100000 [=====] 100.00% 911/s 1m49s
Done!
Statistics        Avg      Stdev        Max
  Reqs/sec       922.00     827.36    5866.92
  Latency      218.86ms     9.84ms   369.95ms
  HTTP codes:
    1xx - 0, 2xx - 100000, 3xx - 0, 4xx - 0, 5xx - 0
    others - 0
  Throughput:   191.66KB/s

```

**Comment by swetharepakula** [comment]
Thanks for reporting the issue! The `ingress-gce` repository only has the controller code that is used to configure the loadbalancer. Since the performance issue seems is with the load balancer and not the controller, please open a support ticket with GCP with this info and cluster details.

**Comment by Olegt0rr** [comment]
@WLun001, since [the article](https://blog.yongweilun.me/gke-ingress-is-slower-than-you-think) points here, please post any news about this issue here or update an article
