### ISSUE TITLE
gke ingress rror syncing to GCP: error running load balancer syncing routine: loadbalancer ax0jpqse-api-zil17xhm does not exist: invalid ingress frontend configuration, please check your usage of the 'kubernetes.io/ingress.allow-http' annotation.

### ISSUE THREAD

**Issue by po45ke95** [kubernetes/ingress-gce#1478]
have problem is sometimes ingress can connect gcp loadbalancer sometimes cant
in ingress show this error
Error syncing to GCP: error running load balancer syncing routine: loadbalancer ax0jpqse-api-zil17xhm does not exist: invalid ingress frontend configuration, please check your usage of the 'kubernetes.io/ingress.allow-http' annotation.

my kubernetes.io/ingress.allow-http: false

**Comment by swetharepakula** [comment]
Thanks for reporting the issue! A couple questions so we can further investigate.
1) Can you paste the yaml of your frontend configuration and ingress? (If different when successful vs unsuccessful please post both)
2) Are there any changes made to the Ingress or frontend configuration when you notice that the ingress is able to sync and not able to sync?

**Comment by po45ke95** [comment]
1.In our project doesnt use fronend cofig.
2.We notice the ingress  is not able to sync didnt change anything,but same ingress yaml in other service can always sync,that our confuse.
`apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.gcp.kubernetes.io/pre-shared-cert: ""
    ingress.kubernetes.io/backends: '{"k8s-be-30016--75ef436e3be83a63":"HEALTHY","k8s-be-31740--75ef436e3be83a63":"HEALTHY","k8s1-75ef436e-production-client-api-8080-f3b13919":"HEALTHY"}'
    ingress.kubernetes.io/https-forwarding-rule: k8s2-fs-ax0jpqse-production-client-api-zil17xhm
    ingress.kubernetes.io/https-target-proxy: k8s2-ts-ax0jpqse-production-client-api-zil17xhm
    ingress.kubernetes.io/ssl-cert: 
    ingress.kubernetes.io/url-map: k8s2-um-ax0jpqse-production-client-api-zil17xhm
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: client-api-production-ip-address
    meta.helm.sh/release-name: sw-api
    meta.helm.sh/release-namespace: production
    networking.gke.io/managed-certificates: client-api-prod-certificate
  creationTimestamp: "2021-01-20T03:32:54Z"
  finalizers:
  - networking.gke.io/ingress-finalizer-V2
  generation: 3
  labels:
    app: client-api
    app.kubernetes.io/managed-by: Helm
    chart: sw-api-1.13.6
    env: production
    heritage: Helm
    release: sw-api
  name: client-api
  namespace: production
  resourceVersion: "161202574"
  selfLink: /apis/extensions/v1beta1/namespaces/production/ingresses/client-api
  uid: 3aad61d0-5528-4e1e-a7f0-87b106fd895d
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: swagger
          servicePort: 8080
        path: /docs/*
        pathType: ImplementationSpecific
      - backend:
          serviceName: client-api
          servicePort: 8080
        path: /*
        pathType: ImplementationSpecific
status:
  loadBalancer:
    ingress:
    - ip: 
`

**Comment by swetharepakula** [comment]
A few more followups:
1. Are you using GKE or running the controller by itself?
2. If using GKE, what are the cluster versions of the clusters you mentioned? (The one that is working and not working). If running the controller on its own, what Ingress versions are you using?

If you are using GKE, it may be better to open a support ticket as support will have access to more information about the cluster. Otherwise can you send an email to srepakula@google.com with details about your clusters (GCP project name, cluster name)?

Thanks,
Swetha

**Comment by po45ke95** [comment]
1. we using gke.
2. gke-cluster-version: 1.18.17-gke.1901.

**Comment by orlandothoeny** [comment]
@po45ke95 Have you tried putting `true` in quotes?

Like this: `kubernetes.io/ingress.allow-http: "false"`

**Comment by freehan** [comment]
Ping @po45ke95 for response.

**Comment by po45ke95** [comment]
> @po45ke95 Have you tried putting `true` in quotes?
> 
> Like this: `kubernetes.io/ingress.allow-http: "false"`

**Comment by ZiaUrRehman-GBI** [comment]
```apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: server-ingress
  namespace: demo
  annotations:
    kubernetes.io/ingress.class: gce
    cert-manager.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.global-static-ip-name: static-ip
spec:
  defaultBackend:
    service:
      name: server
      port:
        name: https
  rules:
    - host: dev.example.com
      http:
        paths:
          - backend:
              service:
                name: server
                port: 
                  name: https
            path: /*
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - dev.example.com
      secretName: web-ssl
