### ISSUE TITLE
GKE Ingress Bad Gateway or Backend not found

### ISSUE THREAD

**Issue by dotnetpiper** [kubernetes/ingress-gce#1481]
Hi Team,

I've been using GKE and setup GKE Ingress mere to manage the path for all  which we have kept in GCR.
I've created a .Net core based API which is has various path , if I expose the deployment with service as type Loadbalancer it works perfectly. Though when I utilize GKE Ingress and setup service and its backend it throws an error like Bad Gateway or sometime backend not found.

.Net core api application exposes following path when i exposed on service as loadbalancer, kindly follow below screenshot for reference:
http://35.202.38.40/api/books
http://35.202.38.40/api/categories

![![![image](https://user-images.githubusercontent.com/20516546/122716691-34506000-d288-11eb-800b-fa9f9181898a.png)]

The same way we do have post api's.

Now I'm stuck when I utilize GKE ingress and setup my ingress.yaml as follows , it doesn't work and throws an error.
Ingress.Yaml

`apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gke-ingress
  annotations:
    # If the class annotation is not specified it defaults to "gce".
    kubernetes.io/ingress.class: "gce"    
spec:  
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:          
            serviceName: hello-world
            servicePort: 80
      - path: /api/*       
        backend:          
            serviceName: hello-world
            servicePort: 80`      

NOTE: my hello-word is exposing a .Net Core API application, kindly don't get confuse with name as "hello-world" for testing.
![image](https://user-images.githubusercontent.com/20516546/122716753-4b8f4d80-d288-11eb-9f1f-3b8186ccef34.png)

**Deployment and service Yaml**
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  selector:
    matchLabels:
      greeting: hello
      department: world
  replicas: 2
  template:
    metadata:
      labels:
        greeting: hello
        department: world
    spec:
      containers:
      - name: hello
        image: gcr.io/strategic-uuu-636633/oneplus2:631
        ports:
        - containerPort: 80
        
**Service.Yaml**

apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  type: NodePort
  selector:
    greeting: hello
    department: world
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

Kindly advise how to setup path based routing in GKE Ingress for .Net Core Api app.

**Comment by swetharepakula** [comment]
Hi @dotnetpiper, thank you for raising the issue. Because you are using GKE it may be easier to debug if you open up a support ticket as they can better debug your environment.

Otherwise can you please post the error you are seeing and where you are seeing? What is the GKE version that you are using?

**Comment by freehan** [comment]
Ping @dotnetpiper for response.

**Comment by utamori** [comment]
I ran into the same problem, but solved it by setting up readinessProbe.

[GKE Ingress for HTTP(S) Load Balancing ingress#health_checks](https://cloud.google.com/kubernetes-engine/docs/concepts/ingress#health_checks)
