### ISSUE TITLE
ingress-gce does not work...very little documentation ..instructions lead to 404 pages

### ISSUE THREAD

**Issue by rangapv** [kubernetes/ingress-gce#149]
Hi,
I am trying to get external load balancer on GCE.
My cluster is kubernetes 1.9.3 (kubeadm)...

I am trying to install the ingress-gce from github...the documentation is very confusing and also there is no right pointers...

I started from here...

https://github.com/kubernetes/ingress-gce

Then I just downloaded the rc.yaml and the app.yaml did a kubectl then it would not start the loadbalancer pod bocs the liveliness probe was failing then I changed the rc.yaml where the liveliness probe was doing a healtcheck on the loadbalncer pod on port 8081 to 8080..now the pod seems to be running...

Now how will the backend loadbalancer in the GCP get created ? how will the fowarding rules get created ..?

I also tried the compiling of the binary(very cumbersome process ..no documentation) though I manged it.
 Since the rc.yaml is pulling the image do I still need to compile the binary ? or is it just an option ?

What are the scopes that is required for the instances so that it goes and creates the LoadBalancer and its rules ..?

This gives me 404....

https://github.com/kubernetes/ingress-gce/blob/master/examples/deployment/gce/README.md

Can you brief me about correct steps...

REgards
Ranga

**Comment by rangapv** [comment]
/labels
backend/gce

**Comment by rangapv** [comment]
/Labels
backend/gce

**Comment by manjotpahwa1** [comment]
Thanks for reporting! I'll get the documentation with no working links in place.

**Comment by nicksardo** [comment]
Duping to #249
/close
