### ISSUE TITLE
Explain how to change version used at GKE

### ISSUE THREAD

**Issue by bboreham** [kubernetes/ingress-gce#1531]
I read at https://github.com/kubernetes/ingress-gce#gke-version-mapping "Note that these versions are simply the defaults.", however after reading many many pages of documentation I am unable to find how to depart from the default.

Could you add a pointer please.

**Comment by swetharepakula** [comment]
Hi @bboreham, The version mapping that we have on our README is not complete and the actual mapping may be slightly different ( usually at the patch version) which is what we mean by this is only the default. There is no way to change the ingress version on a GKE cluster and the Ingress version is coupled with the GKE version and cannot be modified.

**Comment by bboreham** [comment]
Thank you. I think it would be worth putting that information alongside the table.
