### ISSUE TITLE
Add Cloud CDN cache mode to BackendConfig

### ISSUE THREAD

**Issue by steebchen** [kubernetes/ingress-gce#1533]
The Cloud CDN BackendConfig resource does not support setting the [cache mode](https://cloud.google.com/cdn/docs/using-cache-modes#api), e.g. `USE_ORIGIN_HEADERS`.

https://github.com/kubernetes/ingress-gce/blob/bac1e50af14856c4cf2162ece155de46b586dca9/pkg/apis/backendconfig/v1/types.go#L83-L88

Could this be added to the CDNConfig?

**Comment by gabihodoroaga** [comment]
@steebchen There is a PR open for this #1387, and for all other CDN options as well but the review process is some how stuck because nothing happened in the last 2 months.

**Comment by steebchen** [comment]
Still relevant.

/remove-lifecycle stale

**Comment by freehan** [comment]
PR is merged. https://github.com/kubernetes/ingress-gce/pull/1387
