### ISSUE TITLE
Hung Instance Group operations causing downtime

### ISSUE THREAD

**Issue by csainty** [kubernetes/ingress-gce#1535]
We've had this happen twice now, during a node pool upgrade an API call to modify the instance group hangs for 60 minutes before timing out. This ultimately results in all nodes being removed from the instance group and a service outage until the timeout occurs and another sync operation runs.

See timeout logs here
![Screen Shot 2021-08-04 at 09 27 51](https://user-images.githubusercontent.com/810995/128153553-4e554bfa-73be-4031-9819-a23cc98ca035.png)

See instance group depletion here
![Screen Shot 2021-08-04 at 10 42 29](https://user-images.githubusercontent.com/810995/128153640-2a5d6f69-ee98-46b1-bffc-ec4c9caec617.png)

Following along some code paths
https://github.com/kubernetes/ingress-gce/blob/master/pkg/instances/instances.go#L293
https://github.com/kubernetes/ingress-gce/blob/master/vendor/k8s.io/legacy-cloud-providers/gce/gce_instancegroup.go#L94
https://github.com/kubernetes/ingress-gce/blob/master/vendor/github.com/GoogleCloudPlatform/k8s-cloud-provider/pkg/cloud/context.go#L25

It appears the timeout is a default from the GCP libraries.

We had a support case open with GCP the first time this happened, and I will update that with this reoccurrence, however I'd like to put it to the developers here that a shorter timeout would be more suitable 🙏

**Comment by csainty** [comment]
@swetharepakula I would, humbly, challenge the `kind/support` label.

I gave all the details from our instance to show the severity of it, I am not looking for the developers here to diagnose or support our specific case. We've got a paid support ticket open for that.

The issue is rather that you're inheriting a 60 minute timeout on GCP API calls and I propose that is too long when the consequences of waiting are so severe.
Is it not more correct to fail quickly and come back to it in the next sync attempt?

I'd throw up a PR, but do not have enough visibility and context to pick a better default, there does appear to be telemetry there though, so I assume a better default can be found.

**Comment by skmatti** [comment]
csainty@ High connection draining timeouts (3600 seconds (1 hour)) for one of the backend service of an instance-group based Ingress will cause issues for other instance-group based Ingresses in the cluster. 

We recently updated our documentation to reflect this issue in https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#draining_timeout

Please let us know if reducing the timeout to a smaller value resolved the issue.

**Comment by csainty** [comment]
Thanks @skmatti we received this insight from the paid support ticket too.
I'll close the issue and leave it to your team to consider correct behaviour here.

For example, if you could continue adding new nodes to the instance group while they are being removed and given time to drain in the background, then it might keep the ingress alive during this period.
Additionally setting a realistic timeout based on observable draining timeout would let you log a bit more clearly the expected time for a call to finish and react better to api stability.

Anyway it is on your radar now. Thanks again for the reply.

**Comment by skmatti** [comment]
cc: @bowei

**Comment by bowei** [comment]
We are looking at how to improve management of the IGs. However, there are some dependencies between the controllers in kubernetes/kubernetes and ingress-gce that makes changing the algorithm a bit trick. The best thing to do is to move to using NEGs if you can, as that will be the most scalable and quick to sync.
