### ISSUE TITLE
Adding ingress rule to ingress definition doesn't update Load Balancer definition

### ISSUE THREAD

**Issue by jacek-jablonski** [kubernetes/ingress-gce#1546]
Kubernetes version: `1.20.8-gke.900`

Hi,
I have updated my ingress definition, by adding a path rule. However, this change isn't reflected in the Load Balancer configuration. By any means, I'm not able to force LB to update (without deleting the existing ingress). Unfortunately, events and logs show nothing useful in this case, so I am also unable to debug this situation.

![ingress](https://user-images.githubusercontent.com/35669512/129059611-fcae3161-e9f5-48ed-8708-0961a8484e72.png)

As you can see, LB is missing `/tagging/*` path:
![lb](https://user-images.githubusercontent.com/35669512/129059617-ff6331c1-e008-4fb1-9561-c0316fb4f7be.png)

How can I debug this situation or force ingress to update LB?

**Comment by jacek-jablonski** [comment]
Finally, I've recreated an ingress, which solved this situation.

But today I tried to add a new path to this ingress and the same situation occurred. The path is visible in the ingress definition, but Load Balancer doesn't get updated.

Please could you take a look at this situation? Recreating ingress causes quite a long downtimes.

**Comment by freehan** [comment]
Can you file a support ticket with GKE support and include necessary information (cluster, ingress, time frame, etc)?

**Comment by freehan** [comment]
Another alternative is to provide a test yaml and steps to repro.
