### ISSUE TITLE
Seems ingress don't transfer the "Transfer-encoding" Header from backend

### ISSUE THREAD

**Issue by maxiplay** [kubernetes/ingress-gce#157]
I tried to use Google cloud cdn with my container engine configuration. When backend respond with GZIP and Transfer-encoding : chunked it  ingress don't transfer the "Transfer-encoding" Header from backend so I can't have a cache hit.

When the content is not Gzipped i have the "Content-Length" header and a cache hit success.

I linked the issue to stackoverflo question, https://stackoverflow.com/questions/49297244/impossible-to-use-google-cloud-cdn-cache-with-ingress-controller-transfer-encod?noredirect=1#comment85706992_49297244

apiVersion: extensions/v1beta1

**Comment by rramkumar1** [comment]
@maxiplay The GCE Ingress controller does not do any modification of response headers. This sounds like an issue with Google Cloud Load Balancer rather than Ingress. Closing this issue for now.
