### ISSUE TITLE
Keep pod in NEG whilst terminating

### ISSUE THREAD

**Issue by fatmcgav** [kubernetes/ingress-gce#1574]
We have a scenario where we're running Jenkins in GKE using the `ingress-gce` class.

Jenkins is unfortunately a single statefulset instance, with potentially long-running CI jobs that we want to allow to end gracefully before the pod stops.

We've tried using the `preStop` lifecycle hook, however we hit a scenario whereby because the pod goes into a `Terminating` state it gets removed from the NEG even whilst it's stopping.
This effectively causes the Jenkins UI to become unavailable whilst it's still terminating jobs in the background, which is problematic.

Are there any available workarounds for this behaviour?
Or is this intended behaviour and the Jenkins model just doesn't work?

**Comment by freehan** [comment]
Yes. This is the intended behavior of NEG controller. It optimized to lower the programming latency. Currently this behavior is not configurable. 

Is it possible to gracefully terminate the jenkins workflow before deleting the pod (put it into terminating state)?

**Comment by freehan** [comment]
This feature depends on the Graceful termination KEP currently in progress.
