### ISSUE TITLE
GKE 1.22 v1beta1 deprecation

### ISSUE THREAD

**Issue by dinvlad** [kubernetes/ingress-gce#1578]
Hi folks,

I've got an email from GCP that `v1beta1` APIs will be deprecated in K8s 1.22. Does it affect existing GKE resources and annotations like `networking.gke.io/v1beta1.FrontendConfig`, where it's unclear if `v1` is supported yet?

Thank you

**Comment by swetharepakula** [comment]
Hi @dinvlad, 

The notice was regarding [v1beta1 APIs](https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/#api-changes) that Kubernetes removed in 1.22. The linked blog has the list of APIs that have been removed as well as which APIs to use instead.

`networking.gke.io/v1beta1.FrontendConfig` will continue to be supported.

Cheers,
@swetharepakula
