### ISSUE TITLE
Translation failed: invalid ingress spec: only "ImplementationSpecific" path type is supported

### ISSUE THREAD

**Issue by tpraveen-boomplus** [kubernetes/ingress-gce#1584]
I am running GKE  1.20.10-gke.301

 I am trying deploy ingress getting following errors 

Translation failed: invalid ingress spec: only "ImplementationSpecific" path type is supported; only "ImplementationSpecific" path type is supported; only "ImplementationSpecific" path type is supported; only "ImplementationSpecific" path type is supported

**Comment by swetharepakula** [comment]
In GKE 1.20.10-gke.301 we only support `ImplementationSpecific` path type. Please check your ingress definition and ensure you are specifying `ImplementationSpecific`.

We support `Prefix` and `Exact` starting in `1.21.3-gke.1600`

**Comment by tpraveen-boomplus** [comment]
my ingress definition has pathType: ImplementationSpecific, pathType: Prefix and pathType: Exact.
for now i am using nginx ingress controller. 
thanks update.
