### ISSUE TITLE
Zonal NEG being removed from Load Balancer

### ISSUE THREAD

**Issue by Scalahansolo** [kubernetes/ingress-gce#1589]
During rollouts of new pods, there are instances where the load balancer for the GCE ingress will drop a zone out of all the serving backends, and it takes an unknown amount of time before they get back into the pool. 

There are plenty of issues about this particular issue, and we have tried a whole handful of things to alleviate the problem, but there has yet to be any particular resolution to fully solve the problem.

Without being able to solve the issue, we will have to move back to a single zonal cluster, which seems like a step backward.

**Comment by swetharepakula** [comment]
/kind support

@Scalahansolo Are there any node pool changes that occur around that time? About how long does it take for the zones to be added back? What cluster version are you using?

Can you open a support ticket with GKE. They/we will be able to investigate further as they will have access to the cluster and the master logs (where ingress controller logs are).

**Comment by spencerhance** [comment]
@Scalahansolo which GKE version was this on?
