### ISSUE TITLE
Missing ListUrlMaps from LoadBalancers interface

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/ingress-gce#162]
I see that ListUrlMaps is missing from LoadBalancers interface at: https://github.com/kubernetes/ingress-gce/blob/master/pkg/loadbalancers/interfaces.go#L37.

I need it for kubemci as part of work for https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/145.

Any objections to me sending a PR to add it?

cc @nicksardo @bowei

**Comment by nicksardo** [comment]
Sure.

**Comment by G-Harmon** [comment]
cc me

**Comment by nikhiljindal** [comment]
Thanks for the quick reply @nicksardo 
Sent https://github.com/kubernetes/ingress-gce/pull/165
