### ISSUE TITLE
Not possible to have client certificate authentication

### ISSUE THREAD

**Issue by muvaf** [kubernetes/ingress-gce#1622]
Hi!

I have an application that authenticate requests based on their client certificate. However, if I use `Ingress` in GKE, it terminates SSL on the load balancer and application doesn't accept an HTTP request. If I set `cloud.google.com/app-protocols: '{"clients":"HTTPS"}'` on the `Service`, then load balancer makes an HTTPS request to the application but then;
* If I use port `80` on the load balancer, then I can't deliver my client certificates.
* If I use port `443` on the load balancer, it doesn't work since SSL is not configured.
  * If I configure SSL with my self-signed server certificates, the request sent to the application from the load balancer does not have the client certificate details I need for authentication because SSL is already terminated at load balancer.

Other ingress controllers, like ingress-nginx, has solved this via an annotation [`nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream`](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#client-certificate-authentication) where it terminates the SSL and then in the request load balancer makes to the application, the client certificate is forwarded.

I think two things can solve this problem:
* Option to forward TLS certificate to the application in the request `load balancer -> application`.
* Option to let the application terminate SSL even if the request comes to `load-balancer-ip:443`, like [`nginx.ingress.kubernetes.io/ssl-passthrough`](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#ssl-passthrough) does.

I have a fair amount of Go and Kubernetes controller experience, so I can contribute if folks think it's possible to solve the problem with a code change in ingress-gce 🙂

**Comment by freehan** [comment]
I do not think this is supported on Google Cloud LB. This would be a feature request to GCLB. 

One alternative is to use L4 LB on port 80 or 443 and it will deliver traffic to your backends directly.
