### ISSUE TITLE
More info about pre-requisite in dev-setup.md

### ISSUE THREAD

**Issue by kundan2707** [kubernetes/ingress-gce#1627]
More and clear information about pre-requisit should be present in 
https://github.com/kubernetes/ingress-gce/blob/master/docs/contrib/dev-setup.md
For example:
Docker  version, Go and its version
Any other remaining ....

**Comment by freehan** [comment]
Go version can be found in `go.mod`. There is no dependency on docker version. 

Reopen if needed.

**Comment by freehan** [comment]
Welcome a PR for adding documentation in dev-setup.md.

**Comment by kundan2707** [comment]
@freehan will create a PR if i identify few more items to be added in dev-setup.md

**Comment by kundan2707** [comment]
I am closing this issue for now. WIll reopen if identify any further required changes.
