### ISSUE TITLE
Support for URL redirects

### ISSUE THREAD

**Issue by dinvlad** [kubernetes/ingress-gce#1677]
Hi folks,

Does GCE Ingress support the [URL redirect](https://cloud.google.com/load-balancing/docs/url-map-concepts#url-redirects) feature of GCE LB? I've seen `defaultUrlRedirect` mentioned in the [code](https://github.com/kubernetes/ingress-gce/blob/951827341a53e783698632b1fec9d187dcc43474/pkg/composite/gen.go#L2435), however I'm trying to understand if it's actually usable inside an Ingress, and how.

Thanks!

**Comment by spencerhance** [comment]
Hi @dinvlad, today it is only used for enabling HTTP->HTTPS redirects on external ingress:

https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#https_redirect

**Comment by dinvlad** [comment]
@spencerhance thanks - Google Support shared this public issue filed for it: https://issuetracker.google.com/212418577
