### ISSUE TITLE
use a sslCertificates from another project

### ISSUE THREAD

**Issue by raphaelauv** [kubernetes/ingress-gce#1682]
In a project A I want use a sslCertificates from a project B

I tried :

```yaml
ingress.gcp.kubernetes.io/pre-shared-cert: https://www.googleapis.com/compute/v1/projects/B/global/sslCertificates/ssl-cert-in-b
```
or

```yaml
ingress.gcp.kubernetes.io/pre-shared-cert: projects/B/global/sslCertificates/ssl-cert-in-b
```

But it's not working , is it possible ?

**Comment by swetharepakula** [comment]
Thanks for opening an issue! 

Can you share more about this use case? Is this a Shared VPC setup or are all certs in a different project?

**Comment by raphaelauv** [comment]
Shared VPC setup -> No

The cert is in another project
