### ISSUE TITLE
GCP certificate-manager support?

### ISSUE THREAD

**Issue by thequailman** [kubernetes/ingress-gce#1692]
When will GCE ingress support certificates generated by [certificate-manager](https://cloud.google.com/certificate-manager/docs/overview)?  The certificates have a separate path, and don't seem to work if you specify them in the annotation `ingress.gcp.kubernetes.io/pre-shared-cert` (https://cloud.google.com/kubernetes-engine/docs/how-to/load-balance-ingress#ingress_annotations).

**Comment by Burekasim** [comment]
Hi @thequailman 

I had a call with GCP support today, it's not supported and they GKE team has an internal discussion about how to support this feature.

**Comment by plgingembre** [comment]
Hi @thequailman,

Thanks for your question. Cloud Certificate Manager will natively be supported using the Gateway API in GKE. Current support with Ingress is K8s secret, Self-managed certs, or Google-managed certs. 

Thanks,
Pierre-Louis

**Comment by toVersus** [comment]
Hi @plgingembre,

Thanks for your clarification! So, you mean that there is no plan for Ingress to attach certificates generated by Certificate Manager, right?

**Comment by hjorth** [comment]
+1 for getting this on gce ingress.

Currently it seems to be working when setting the certificate map manually on the https target proxy.

But maybe this will stop working once cert-manager is not beta.

**Comment by dgnemo** [comment]
According to [1] Certificate Manager now reached GA status.

Is it really not possible to use it with the GKE offering ?!?

[1] https://cloud.google.com/certificate-manager/docs/release-notes

**Comment by markrandall** [comment]
I am in the same position.

I have a need to assign hundreds of SSL certificates to a GKE ingress but am capped by the 15 limit via the ingress object. We are running on a premium network tier and a global load balancer behind Cloud CDN and Cloud Armor, but seemingly have no way of having GKE and certificate manager talk to each other, and as mentioned by the post previously gateway api does not support CDN or Armor.

**Comment by martinraison** [comment]
As mentioned by @hjorth, setting the certificate map manually on the target https proxy seems to be working. But I had to attach a dummy `ManagedCertificate` on the ingress (the domain name can be anything), to force it to provision an HTTPS proxy. Not sure if there's a simpler way

**Comment by pbiggar** [comment]
I attached a certificate-map to the target https proxy of my GKE ingress, and this took down my site (browsers were no longer able to connect to existing k8s certs). I've reported this to GCP via the support channel, but would advice caution to others going down this route.

**Comment by hjorth** [comment]
> I attached a certificate-map to the target https proxy of my GKE ingress, and this took down my site (browsers were no longer able to connect to existing k8s certs).

The minute you activate certificate-map - the existing certificates are no longer used.

You need to have all your certificates provisioned in certificate-manager and map entres as well.

It might take a few minutes before the Google managed certificates is generated and provisioned. But its much faster than Managed Certificates.

**Comment by martinraison** [comment]
Note: even though I got it working with a _single cluster_ ingress, attaching a certificate map manually to the target https proxy of a _multi cluster_ ingress does not seem to work. The certificate map does not seem to be used at all, and the target https proxy configuration gets reverted automatically after a while.

**Comment by markrandall** [comment]
Sharing what I learnt  after reached out to Google Cloud Support about the matter of having a that supports both cert manager + CDN + Armor:

They told me that there was no support for this setup at the moment but that it will come with the eventual GA of the Gateway API, but there is no fixed timeline for when that might be expected to arrive, other than after the first half of 2023.

An internal feature request was already raised and a public tracker issue was created here:
https://issuetracker.google.com/issues/263437663

**Comment by jjhuff** [comment]
@markrandall thanks for following up with support. Still, disappointing. Ultimately, I'd just like the DNSAuth/ACME support that certificate manager product brings.

**Comment by buptliuwei** [comment]
Is there any progress on this? ingress-gce does not seem to be able to solve some basic fuction, and wants us all to use Gateway API 
https://github.com/kubernetes/ingress-gce/issues/109

**Comment by swetharepakula** [comment]
As mentioned earlier in https://github.com/kubernetes/ingress-gce/issues/1692#issuecomment-1133470810, we do not plan to add support for Certificate Manager in Ingress. The Gateway API does currently have an integration with certificate manager: https://cloud.google.com/kubernetes-engine/docs/how-to/secure-gateway#secure-using-certificate-manager

**Comment by Vlad1mir-D** [comment]
Until you're a client with a very big bill and an enterprise support, they don't give a shit so it's useless to attempt communicate them.

**Comment by sergey-vin** [comment]
that is so strange that such a basic functionality is not supported yet. AWS works like a charm.
but in GCP, when having a GKE Autopilot k8s cluster and trying to provision L7 LB via GKE Ingress or directly via terraform resources and connecting it to GCP managed cert already took me 2-3 full days with no results.

had to read many docs, all leading to nothing:
- https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-multi-ssl
- https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs
- https://cloud.google.com/load-balancing/docs/target-proxies
- https://cloud.google.com/certificate-manager/docs/overview
- https://stackoverflow.com/questions/75505966/how-to-use-already-created-google-managed-ssl-with-gke-ingress-or-istio-ingress
- https://discuss.google.dev/t/gke-troubleshoot-error-ssl-certificate-provisioning-failed-not-visible/153233
- https://cloud.google.com/load-balancing/docs/load-balancing-overview
- https://cloud.google.com/load-balancing/docs/choosing-load-balancer?authuser=1#premium-standard
- https://cloud.google.com/kubernetes-engine/docs/concepts/ingress
- https://cloud.google.com/load-balancing/docs/ssl-certificates/google-managed-certs?authuser=1

Google, Claude Code, Github autopilot, Cursor, my brain (which is the least intelligent in that list) all fall victims to that impossible quest

**Comment by kush-wisdom** [comment]
> As mentioned earlier in [#1692 (comment)](https://github.com/kubernetes/ingress-gce/issues/1692#issuecomment-1133470810), we do not plan to add support for Certificate Manager in Ingress. The Gateway API does currently have an integration with certificate manager: https://cloud.google.com/kubernetes-engine/docs/how-to/secure-gateway#secure-using-certificate-manager

Can you clarify that the support added in GatewayAPI will only work with GKE-gateway-api controller; as someone using Gateway API with different controller; this is useless?
