### ISSUE TITLE
K8S Ingress spec missing URL rewrite capability

### ISSUE THREAD

**Issue by m62534** [kubernetes/ingress-gce#1723]
Missing a way of configuration-as-code/infra-as-code for k8s ingress to perform the following actions (which can be done via gui): https://cloud.google.com/load-balancing/docs/https/setting-up-url-rewrite#modifying_the_url_map

**outcome**:
1. user navigates to somesite.com/public/ql
2. url map redirects to somesite.com/api/ql/external

**Comment by swetharepakula** [comment]
The K8s Ingress API is in V1 and does not support providing a rewrite for a path. The [Gateway API](https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/) is meant to replace the Ingress API in Kubernetes and natively supports rewrites. We will look to support this feature in the GKE Gateway implementation.

Please look to the [GKE Gateway Docs](https://cloud.google.com/kubernetes-engine/docs/concepts/gateway-api) for more information about the GKE implementation.
