### ISSUE TITLE
Allow naming NEG when ingress: true

### ISSUE THREAD

**Issue by nicoche** [kubernetes/ingress-gce#1727]
Hi!

I currently use annotation `"cloud.google.com/neg"` (`NEGAnnotationKey` https://github.com/kubernetes/ingress-gce/blob/master/pkg/annotations/service.go#L39-L47)  with `ingress: true` to automatically create network endpoint groups. It works incredibly well.
I want to set a custom name to NEGs. I saw in GCP documentation that it's possible, but that means dropping `ingress: true`, which I don't want to do 😢.

Is there any plan to support this?
If I can bring any help, I'd be happy to.

**Comment by dorfire** [comment]
+1
