### ISSUE TITLE
How to identify controller version in GKE?

### ISSUE THREAD

**Issue by mikenorgate** [kubernetes/ingress-gce#1738]
Is there any way to identify which version of ingress-gce is being used in a GKE cluster or when a new version of ingress-gce will be made available by GKE? 

With new versions of ingress-gce containing some required bug fixes it would be useful to track when the updated version will be available in GKE

**Comment by kundan2707** [comment]
@mikenorgate  i hope you already got answer for  your question.

**Comment by kundan2707** [comment]
Closing this issue as already answered.
Feel free to reopen if needed.
