### ISSUE TITLE
Feature: Support selecting network tier and scope

### ISSUE THREAD

**Issue by Vlad1mir-D** [kubernetes/ingress-gce#1745]
https://github.com/kubernetes/ingress-gce/issues/1380 Wasn't reopened so I'm duplicating this feature request.

> Currently it's not possible to create a `Standard` tier external L7LB using Ingress objects. Even if the project default tier is set to Standard the ingress controller fails[1] because it tries to create a LB with a `global` scope and there's no way to specify a `regional` scope.
> 
> For L4 LBs created using Services with type `LoadBalancer` the custom annotation `cloud.google.com/network-tier: Standard` was introduced in kubernetes/kubernetes#88487 to solve this problem.
> 
> Would it be possible to use this same strategy for Ingresses while also allowing a custom scope or using a CRD (FrontendConfig?) would be more appropriate? I'd be willing to work on a PR if this change is desired.
> 
> [1] - Error event message:
> 
> ```
> Error 400: STANDARD network tier (the project's default network tier) is not supported: STANDARD network tier is not supported for > global forwarding rule., badRequest
> ```

P.S. Also would like to duplicate my answer to https://github.com/kubernetes/ingress-gce/issues/1380#issuecomment-884380535:

> @freehan Why closed? Google Cloud LB supports regional external LB indeed!
> https://cloud.google.com/load-balancing/docs/https#load-balancer-mode:
> >
> > Global external HTTP(S) load balancer (classic). This is the classic external HTTP(S) load balancer that is global in Premium Tier but can be configured to be regional in Standard Tier. This load balancer is implemented on Google Front Ends (GFEs). GFEs are distributed globally and operate together using Google's global network and control plane.

**Comment by tedchang77** [comment]
this feature is something we would be very interested in as well due to data residency requirements.

**Comment by z15alall** [comment]
Hi samething here, highly anticipated from us, it will be very usefull to have the abbility to chose a regional LB if needed to reduce cost...
