### ISSUE TITLE
Feature: Add domain support for PSC

### ISSUE THREAD

**Issue by geNAZt** [kubernetes/ingress-gce#1751]
Currently a ServiceAttachment doesn't support setting domains. It is possible via Web UI and terraform resources. We currently use it to expose a general service so having a internal domain attached to it so every connected consumer gets a DNS entry pushed via service directory would be awesome.

**Comment by bbayszczak** [comment]
Hello

I met the same limitation on my side

/remove-lifecycle rotten

**Comment by dhilipkumars** [comment]
Helo any update on this feature request? 
ping @swetharepakula

**Comment by swetharepakula** [comment]
No update yet. This work has not yet been prioritized.
