### ISSUE TITLE
Feature: Add labels to forwarding rule being created

### ISSUE THREAD

**Issue by thomasmey** [kubernetes/ingress-gce#1753]
Hi,

I would like to add some custom labels to the forwarding rule being created by ingress-gce. Maybe the labels could be transfered from FrontendConfig/Ingress annotations to the forwaring rule.

**Comment by swetharepakula** [comment]
/kind feature

Hi @thomasmey, would you mind explaining more about your use case and why you need custom labels?

Thanks!

**Comment by thomasmey** [comment]
Hi,

the idea is that the existence of those labels will trigger a process which will create a x.509 certificate and will update LB with this certificate and private key.
