### ISSUE TITLE
Custom Error Pages

### ISSUE THREAD

**Issue by g3kk0** [kubernetes/ingress-gce#1757]
Is it possible to serve custom error pages for things like 404, 503 errors using this ingress controller?

The community Nginx ingress controller appears to support this. It would be good if this was possible with the GCE controller too.

**Comment by kundan2707** [comment]
@g3kk0  seems a good idea. Can you add such page?

**Comment by swetharepakula** [comment]
Hi @g3kk0,

You can have a custom 404 error page by specifying a default backend on the Ingress. Currently if no default backend is provided, the GCE Ingress controller adds our default backend.

For 503, we need to investigate how this can be done and will add an update.

Thanks,
Swetha

fyi @spencerhance

**Comment by alexstojda** [comment]
/reopen

this would be a great feature....

**Comment by allenvino1** [comment]
I think vanilla gcp load balancer supports this. would be great if gke ingress supports it. +1
