### ISSUE TITLE
BackendConfig does not support Named Cookies in CDN Cache Key

### ISSUE THREAD

**Issue by anderspetersson** [kubernetes/ingress-gce#1766]
I'd like https://cloud.google.com/cdn/docs/using-cache-keys#updating_cache_keys_to_use_named_cookies support in BackendConfig.

Currently it throws a validationerror: error validating data: ValidationError(BackendConfig.spec.cdn.cachePolicy): unknown field "includeNamedCookies" in com.google.cloud.v1.BackendConfig.spec.cdn.cachePolicy;

**Comment by gnubibi33** [comment]
Need the same but for HTTP headers :)

**Comment by anderspetersson** [comment]
Still valid in GKE 1.26.1-gke.200

**Comment by gnubibi33** [comment]
Any update ?

**Comment by Skotar** [comment]
Bump. This is very important!
