### ISSUE TITLE
Health checks should accepts 3XX response codes as healthy

### ISSUE THREAD

**Issue by rnett** [kubernetes/ingress-gce#1768]
Having services respond with a 3XX response code is fairly common, for example to redirect to a "starting" page or an OAuth login.  It's a valid successful response, however the ingress's health checks regard it as unhealthy.

**Comment by swetharepakula** [comment]
/kind feature

@rnett, thanks for creating the issue! Unfortunately the GCP load balancing healthcheck has a strict requirement on a 200 status. This is not configurable, so we (ingress controller) cannot support this feature. The healtcheck can have a large amount of traffic, we recommend having a dedicated healtcheck endpoint that does not require a OAuth login or have redirection that will limit CPU usage.
