### ISSUE TITLE
original http request origin and host headers are overriden

### ISSUE THREAD

**Issue by sht5** [kubernetes/ingress-gce#179]
when my client makes an http request to the Ingress domain  i see that the request origin and host headers are sent correctly but on my backend i can see they are changed by Ingress to some internal ip. This is crucial for setting up CORS for my app ( checks domain and alters response headers accordingly).

**Comment by sabinthomas** [comment]
Any update on this? I've looked at all the request headers on the request forwarded from the GCE Ingress, and I can't find anything that exposes the origin IP?

```
x-forwarded-for
x-real-ip
```

In the absence of this ability, I may have to move to using the nginx ingress.

**Comment by bowei** [comment]
Hi, can you post your headers that you are seeing on your application side?
According to this page: https://cloud.google.com/load-balancing/docs/https/, you should be seeing `x-forwarded-for`

**Comment by ItsLeeOwen** [comment]
I have a Deployment, NodePort Service, and Ingress on GKE cluster running `1.13.6-gke.6`.

I've added `externalTrafficPolicy: Local` according to docs: https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-type-nodeport

I see what looks like an ISP address in Kansas in `X-Forwarded-For`, but not the original client IP.

**Comment by synvestable** [comment]
Hi, can you guys add some insight to this? This is a security bug if there's no feature to cover it, can't use in prod.
