### ISSUE TITLE
Unclear documentation of spec.rules.http.paths

### ISSUE THREAD

**Issue by tvainika** [kubernetes/ingress-gce#181]
Documentation of `spec.rules.http.paths` is unclear regarding, regexp versus wildcard, and multiple matches priority.

According [Kubernetes documentation](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#httpingresspath-v1beta1-extensions), `http.paths` should be regular expression. However when testing it on my GCE, it clearly seems to be wildcard match like all examples when looking at GCE load balancer [documentation](https://cloud.google.com/compute/docs/load-balancing/http/url-map).

Second, I did not find anywhere explanation what happens if there is multiple matching path configurations. Which one will be selected? The one that is listed first or last in my `Ingress.yaml`, or something else?

**Comment by tvainika** [comment]
/remove-lifecycle stale

Still in Kubernetes v1.12 this is documented as POSIX regex, but GCE matcher is not regex. See here https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/#httpingresspath-v1beta1-extensions

**Comment by bowei** [comment]
This is an item on the GA list: https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/20190125-ingress-api-group.md

**Comment by wyaeld** [comment]
@bowei why is updating the documentation just be clear on the available behaviour such a long process?  This issue is over a year old.  The differences with `ingress-gce` vs `ingress-nginx` are a huge pain point for new uses.

**Comment by rramkumar1** [comment]
@wyaeld This was updated a while back, looks like we just forgot to close the issue. The docs live [here](https://cloud.google.com/kubernetes-engine/docs/concepts/ingress)

Pasting the relevant section here: 

"The only supported wildcard character for the path field of an Ingress is the * character. The * character must follow a forward slash (/) and must be the last character in the pattern. For example, /*, /foo/*, and /foo/bar/* are valid patterns, but *, /foo/bar*, and /foo/*/bar are not.

A more specific pattern takes precedence over a less specific pattern. If you have both /foo/* and /foo/bar/*, then /foo/bar/bat is taken to match /foo/bar/*.

For more information about path limitations and pattern matching, see the URL Maps documentation."
