### ISSUE TITLE
ingress controller should only manage instance groups for multicluster ingress

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/ingress-gce#182]
Forked from https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/131

ingress-gce controller is configuring the whole load balancer including creating url map, target proxy, etc for multicluster ingresses.
This is a regression. It should only manage instance groups.

Thanks to @MrHohn for finding the problem.
@nicksardo is working on a fix and I am going to send a PR to update the ingress-gce tests to catch this early.

Filing this issue to track

cc @csbell @G-Harmon @bowei

**Comment by G-Harmon** [comment]
nikhil was telling me about this bug today.

**Comment by nikhiljindal** [comment]
https://github.com/kubernetes/ingress-gce/pull/183 fixed the code and https://github.com/kubernetes/kubernetes/pull/61909 updated the test to ensure that we do not regress.

The test is still failing tough. 
Sent https://github.com/kubernetes/kubernetes/pull/61987 to fix that
