### ISSUE TITLE
Test Failing: [sig-network] Loadbalancing: L7 GCE [Slow] [Feature:Ingress] multicluster ingress should get instance group annotation

### ISSUE THREAD

**Issue by freehan** [kubernetes/ingress-gce#185]
https://k8s-testgrid.appspot.com/sig-network-gce#ingress-gce-e2e&width=5

probably due to this: https://github.com/kubernetes/ingress-gce/pull/183

**Comment by nikhiljindal** [comment]
Its due to https://github.com/kubernetes/kubernetes/pull/61909.
Being fixed by https://github.com/kubernetes/kubernetes/pull/61987

**Comment by nikhiljindal** [comment]
The test is now green: https://k8s-testgrid.appspot.com/sig-network-gce#ingress-gce-e2e

/close
