### ISSUE TITLE
Do we have header bases routing in ingress-gce controller

### ISSUE THREAD

**Issue by AlamBeg** [kubernetes/ingress-gce#1861]
Our requirement is to route the traffic to pods based on header-based routing in ingress-gce controller.
Do we have any specific any ways to add header-based routing on ingress rules?
Please assist me on the same as we are using GKS with ingress-gce on production.

**Comment by kundan2707** [comment]
@AlamBeg  https://github.com/kubernetes/ingress-gce/issues/1088#issuecomment-879084063

**Comment by spencerhance** [comment]
cc: @spencerhance
