### ISSUE TITLE
Pin dependencies of update-codegen.sh

### ISSUE THREAD

**Issue by spencerhance** [kubernetes/ingress-gce#1870]
While looking at #1855 it came up that we are not pinning versions of the two dependencies:

1. k8s.io/code-generator
2. k8s.io/kube-openapi/cmd/openapi-gen

We should pin these so that we can have reproducible results when running our API generation.

We should be able to use the same approach as golangci-lint in `hack/tools/tools.go` to install the dependencies.  Then we can access them like how it's done in `build/test.sh`.

**Comment by swetharepakula** [comment]
cc/ @gauravkghildiyal
