### ISSUE TITLE
Enabling global access for internal HTTP(S) load balancer

### ISSUE THREAD

**Issue by oofnikj** [kubernetes/ingress-gce#1883]
I'm having an issue trying to create an internal L7 load balancer through the GCE ingress controller with global access enabled. In the [docs](https://cloud.google.com/load-balancing/docs/l7-internal#forwarding_rule_and_ip_address), the following is written:
> An internal HTTP(S) load balancer's forwarding rules are regional, even when global access is enabled. After you enable global access, the regional internal forwarding rule's allowGlobalAccess flag is set to true.

On another [page](https://cloud.google.com/load-balancing/docs/l7-internal/setting-up-l7-internal#global-access), it's stated that global access cannot be enabled for existing forwarding rules. I confirmed this by running

```sh
% gcloud compute forwarding-rules update k8s2-fr-xxxxxxxx-monitoring-grafana-zzzzzzzz --region=us-central1 --allow-global-access
ERROR: (gcloud.compute.forwarding-rules.update) Could not fetch resource:
 - Invalid value for field 'resource.allowGlobalAccess': 'true'. Updating the allow-global-access flag is only supported for regional INTERNAL forwarding rules with backend service/target instance.
 ```
 
 Once the load balancer and associated forwarding rule is created by the ingress controller, I tried manually creating a new forwarding rule and attaching it to the existing target HTTP proxy with global access enabled, which worked as expected. I would like to know if there is a way to do this declaratively through ingress annotations or some other means?

**Comment by hatemosphere** [comment]
we are actually experiencing the same issue here. we want to be able to access internal HTTP(s) LB residing in a different region while having VPC peering established between VPCs in two different regions. it's definitely technically possible to do that by manually creating a new global forwarding rule on top of existing non-global LB, but it's not clear how to do it via k8s Ingress object.
