### ISSUE TITLE
Ingress creates wrong firewall rule after `default-http-backend` service was clobbered.

### ISSUE THREAD

**Issue by bowei** [kubernetes/ingress-gce#19]
_From @MrHohn on December 8, 2016 18:46_

From kubernetes/kubernetes#36546.

During development, found ingress firewall test failed instantly on my cluster. Turned out due to some reasons, the `default-http-backend` service was deleted and recreated, and it was then allocated a different nodePort. Because ingress controller records this nodePort at the beginning but never refresh([ref1](https://github.com/kubernetes/ingress/blob/master/controllers/gce/main.go#L208) and [ref2](https://github.com/kubernetes/ingress/blob/master/controllers/gce/controller/cluster_manager.go#L274)), it always create firewall rule with the stale nodePort after.

@bprashanth 

_Copied from original issue: kubernetes/ingress-nginx#48_

**Comment by bowei** [comment]
_From @bprashanth on December 9, 2016 0:23_

The assumption is it doesn't change, and it typically shouldn't because it exists in the kube-system namespace, do you remember why it was deleted ? Since it *can* totally get deleted by the user, we should periodically reconciling the default backend.

**Comment by bowei** [comment]
_From @MrHohn on December 9, 2016 0:36_

I accidentally deleted all kube-system services while doing experiment on addon manager, not kubernetes's fault.

**Comment by nicksardo** [comment]
Dupe #184
/close
