### ISSUE TITLE
BackendConfig.cdn.compressionMode not supported

### ISSUE THREAD

**Issue by mogest** [kubernetes/ingress-gce#1908]
[Cloud CDN dynamic compression](https://cloud.google.com/cdn/docs/dynamic-compression#gcloud) was introduced in October last year, however there is no automatic way yet of enabling it when the backend service is set up by GKE.

It can be manually enabled using

    gcloud beta compute backend-services update --global [backend-service-name] --compression-mode=AUTOMATIC

Could this setting be added to `BackendConfig`?

**Comment by cezarygerard** [comment]
@spencerhance PTAL

**Comment by spencerhance** [comment]
Hi @mogest,

Thanks for your feature request!  We would be happy to review a PR for this, however it is unlikely that we will be prioritizing adding this feature in GKE Ingress.  However, I would expect to see it in [GKE Gateway](https://cloud.google.com/kubernetes-engine/docs/concepts/gateway-api).

**Comment by mogest** [comment]
Thanks @spencerhance.  I'll see what I can do with a PR!

**Comment by tczekajlo** [comment]
This PR should help with the issue - https://github.com/kubernetes/ingress-gce/pull/2004
