### ISSUE TITLE
Failing to create an Ingress shouldn't stop the controller from creating the others

### ISSUE THREAD

**Issue by jody-frankowski** [kubernetes/ingress-gce#197]
(Not sure if that is the right place to fill this issue :smiley:)
It looks like the controller doesn't try to create other Ingress object when it fails for one.

See [this issue](https://github.com/jenkins-x/jx/issues/599) for the reproduction steps.
In a nutshell: Ingresses with non-NodePort services break proper Ingresses with NodePort services.

Also (not specified in the other issue) here are the ingresses that break ingress-gce (note the `ClusterIP` type):
```
kubectl get svc
NAME                            TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)     AGE
heapster                        ClusterIP   10.15.241.123   <none>        8082/TCP    4d
[...]
```

Two things bug me:
* ingress-gce seems to break all together when it fails for just one Ingress
* ingress-gce seems to report errors related to other ingresses for a given one

**Comment by jody-frankowski** [comment]
The k8s version of the cluster is `1.9.6-gke.0`.
I'll try to reproduce the issue with 1.10 when it's GA.

**Comment by nicksardo** [comment]
Fixed in later versions of ingress
/close
