### ISSUE TITLE
Fail earlier instead of using defaults

### ISSUE THREAD

**Issue by nicksardo** [kubernetes/ingress-gce#201]
- Ingresses targeting services that are not typed NodePort or LoadBalancer should fail and not create any additional resources. 
 - translator.ToURLMap should not need to fetch backend services. They were asserted earlier.

**Comment by rramkumar1** [comment]
1. Will be fixed by #214, which is a WIP
2. Fixed by #207

**Comment by nicksardo** [comment]
Need to decide what's desirable behavior when the sync fails but the URL map references a backend service that should be GC'd. Maybe we continue to update the URL map on error? Maybe GC is smarter and updates the URL map to stop referencing the backend service? Maybe the backend service is stuck around until the ingress is fixed?
