### ISSUE TITLE
Support Leader Election for GLBC for HA masters

### ISSUE THREAD

**Issue by freehan** [kubernetes/ingress-gce#204]
GLBC should be leader-elected, (the same way we are doing for scheduler, controller-manager, cluster-autoscaler, etc.)
As an example, this is what scheduler is doing:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-scheduler/app/server.go#L414

**Comment by rramkumar1** [comment]
Fixed by #258
/close
