### ISSUE TITLE
Feature request: allow ingress to re-use existing HTTP(S) LB forwarding rule and target proxies

### ISSUE THREAD

**Issue by ggprod** [kubernetes/ingress-gce#2040]
Currently there is no support for backend buckets being created by deploying the Ingress object in GKE.  According to this issue: https://github.com/kubernetes/ingress-gce/issues/33 there is no plan to support backend buckets in the Ingress (though it may be added to the Gateway controller in the future).

However it is a common pattern to have a single HTTP(S) LB with a backend bucket for serving static files (like a SPA web-app) and 1 or more backend services for dynamic content (like REST APIs).  This allows a single unicast IP address and domain to be used for all of these (with different URL paths leading to static or dynamic content) which is also a common pattern.  With the current GKE Ingress controller this is not possible and to accomplish this would require 2 HTTP(S) LBs with separate IPs, forwarding rules, and target proxies.

A mitigation for this lack of important functionality would be to allow the Ingress object to point to an existing (already created) HTTP(S) LB (IP address, forwarding rule, target proxies). That would allow a HTTP(S) to be created outside GKE and connected to a backend bucket and then that could be reused for the GKE Ingress.

**Comment by swetharepakula** [comment]
/kind feature

Thanks for the feature request @ggprod ! 

Unfortunately, there are security risks regarding ownership when trying to claim load balancers or any other resources that were not created by the Ingress controller itself. Therefore this is not a feature that we plan to implement in ingress-gce.
