### ISSUE TITLE
Update service with NEG status

### ISSUE THREAD

**Issue by johnhoran** [kubernetes/ingress-gce#2147]
When NEGs are created via a kubernetes service, I would suggest that something in the status.conditions part of the service would be updated after the NEGs are actually created.  I'm aware that this information is part of the `ServiceNetworkEndpointGroup`, the primary reason I'd suggest adding something to the service is so it can be used with  
[terraform kubernetes_manifest](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/manifest) so you could define a wait condition to get terraform to wait for the NEGs existance before trying to add them into a `google_compute_backend_service`

**Comment by swetharepakula** [comment]
Thanks for the suggestion @johnhoran! This feature needs some design work especially in how to handle Regional clusters where the number of NEGs can continue to expand after the initial specification because the cluster expands to a new zone.
