### ISSUE TITLE
BackendConfig.securityPolicy is not removed after config updates

### ISSUE THREAD

**Issue by julien-michaud** [kubernetes/ingress-gce#2209]
got the same issue as this one today https://github.com/kubernetes/ingress-gce/issues/1706 

I removed a securityPolicy from a BackendConfig CR but the change was not reflected in GCP, forcing me to remove the securityPolicy from the UI.

**Comment by bowei** [comment]
Hi, this is the intended semantic. 

SecurityPolicy removal may be a critical operation, so we require the user to explicitly remove it by specifying empty string in the configuration.
