### ISSUE TITLE
[glbc] Only watch pods hostNetwork=false or having container ports specified

### ISSUE THREAD

**Issue by linxiulei** [kubernetes/ingress-gce#2279]
I am tempted to add a watch filter for pod informer to only watch pods with `hostNetwork=false` or having container ports specified to reduce cache footprint. However, I am not entirely sure if `glbc` is actually interested in those pods.

**Comment by aojea** [comment]
The problem I see is how safe it is? how do we know that we don't break anybody, there is a lot of unexpected setups in the wild , better you discuss with @swetharepakula and @cezarygerard

**Comment by linxiulei** [comment]
I think we can use static check for the safety. See https://github.com/pohly/kubernetes/blob/4bc9434f99d9a87dd5b63e738b6b1b16693f10e4/hack/golangci-strict.yaml#L57

**Comment by swetharepakula** [comment]
I agree with @aojea , I don't think we will be able to filter pods because it is hard to say which pods can be excluded. Spoke offline with @linxiulei , a better option may be to save only the fields that the neg controller cares about (the only controller that watches pods in this repository).
