### ISSUE TITLE
Images should be published to community registry

### ISSUE THREAD

**Issue by sl1pm4t** [kubernetes/ingress-gce#2384]
The built images for this project are being published to a non-standard location (`gcr.io/k8s-ingress-image-push`) and should be updated to a community registry.

Also, the published builds should be promoted and reflected on the releases page of this repository.

/cc @upodroid

**Comment by swetharepakula** [comment]
We do not publish any images for use from this repository. All images pushed to k8s-ingress-image-push are meant for testing purposes only and should not be considered released images.

**Comment by sl1pm4t** [comment]
Why don't images get published from this repository? The community can benefit from this project.
