### ISSUE TITLE
502 on access after deploying the app with ingress, with successful health testing

### ISSUE THREAD

**Issue by orange723** [kubernetes/ingress-gce#2385]
This is my yaml

deploy.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: "2023-12-03T10:33:04Z"
  generation: 4
  labels:
    env: dev
    kustomize.toolkit.fluxcd.io/name: frontend-kustomization
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: frontend-deployment
  namespace: frontend
  resourceVersion: "6362883"
  uid: 096f9c02-345e-4367-8742-758f332285e4
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: frontend
      env: dev
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
        env: dev
    spec:
      containers:
      - image: frontend
        imagePullPolicy: IfNotPresent
        name: frontend
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-12-03T10:35:03Z"
    lastUpdateTime: "2023-12-03T10:35:03Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-12-03T10:33:04Z"
    lastUpdateTime: "2023-12-03T10:51:34Z"
    message: ReplicaSet "frontend-deployment-6877f7d69" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

svc.yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    cloud.google.com/neg-status: '{"network_endpoint_groups":{"80":"k8s1-798e46d9-fro-8-47024330"},"zones":["us-west1-a"]}'
  creationTimestamp: "2023-12-03T10:33:04Z"
  labels:
    env: dev
    kustomize.toolkit.fluxcd.io/name: frontend-kustomization
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: frontend-service
  namespace: frontend
  resourceVersion: "6344751"
  uid: 46c849a8-c984-4382-b3af-42b7296231fa
spec:
  clusterIP: 10.48.2.19
  clusterIPs:
  - 10.48.2.19
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30209
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: frontend
    env: dev
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/backends: '{"k8s1-798e46d9-8-47024330":"HEALTHY","k8s1-798e46d9-kube-system-default-http-backend-80-912fa066":"HEALTHY"}'
    ingress.kubernetes.io/forwarding-rule: k8s2-fr-i8ad6r8kr-197as235
    ingress.kubernetes.io/target-proxy: k8s2-tp-i8ad6r8kfr-197as235
    ingress.kubernetes.io/url-map: k8s2-um-i8ad6r8kfr-197as235
    kubernetes.io/ingress.class: gce
  creationTimestamp: "2023-12-03T10:33:04Z"
  finalizers:
  - networking.gke.io/ingress-finalizer-V2
  generation: 1
  labels:
    env: dev
    kustomize.toolkit.fluxcd.io/name: frontend-kustomization
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: frontend-ingress
  namespace: frontend
  resourceVersion: "6352147"
  uid: 55877ebb-117c-4665-b92a-b41e3422b8ad
spec:
  rules:
  - host: x.x.com
    http:
      paths:
      - backend:
          service:
            name: frontend-service
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer:
    ingress:
    - ip: 35.44.13.xx
  

Everything is working fine including the health check, I have many services deployed using the same way, only this one is not working properly, can anyone tell me why this is? When I curl -v x.x.com on the server there is a timeout and I don't know why ingress is not working properly and not receiving traffic

**Comment by IvanUkhov** [comment]
This can potentially be of relevance:

https://cloud.google.com/kubernetes-engine/docs/troubleshooting/troubleshoot-load-balancing#500-series-errors

It explains what might be happening and how to tackle it.

**Comment by orange723** [comment]
I found the problem, it's a gcp ip problem, gcp has fixed it.
