### ISSUE TITLE
Support SSL policies

### ISSUE THREAD

**Issue by ppawiggers** [kubernetes/ingress-gce#246]
GCLB [provides 3 SSL policies](https://cloud.google.com/compute/docs/load-balancing/ssl-policies?hl=en_US): COMPATIBLE, MODERN and RESTRICTED, which disable specific ciphers. By default, an ingress resource on GCLB selects the COMPATIBLE SSL policy, but I'd like that to be configurable (so TLS v1.0 can be disabled for my resource).

**Comment by briansneddon** [comment]
This may be already implied, but for the sake of clarity the three policies above are the pre-defined policies and if support for switching the policies is to be added then it should also include support for custom policies (also explained in the link above).

**Comment by Stephen2** [comment]
This would be great

**Comment by aaron-trout** [comment]
+1

Also network security policies :D

**Comment by aaron-trout** [comment]
Looks like security policy work is happening here: https://github.com/kubernetes/ingress-gce/pull/291

**Comment by RobMaskell** [comment]
This would be really handy

**Comment by arthurlm44** [comment]
supporting `ssl_policy` in an annotation would be a great feature

**Comment by walterdolce** [comment]
> GCLB provides 3 SSL policies: COMPATIBLE, MODERN and RESTRICTED

Custom policies should also be supported.

**Comment by aviv-ebates** [comment]
Looks like the terminology changed - `COMPATIBLE`, `MODERN` and `RESTRICTED` are now called "Profiles", and "Policy" includes these plus a minimum TLS version.

**Comment by rramkumar1** [comment]
Please see #515. I'll go ahead and leave this issue open though.

**Comment by AntonyCook** [comment]
Is the only work around in the short term to apply the SSL policy separately with a post deploy gcloud command ?

**Comment by mercuriete** [comment]
TLS 1.0 is the default of GCE.
We need to restrict to 1.2 or better.

Doesn't make any sense to change it by hand.

Please create a BackendConfig with this.

**Comment by gijo-varghese** [comment]
Would love to see TLS 1.3. Right now it's 1.2

**Comment by rnaveiras** [comment]
The following PRs added the feature to specify a SslPolicy in the FrontendConfig. Not sure if the implementation is completed, as I am not able to find any documentation. 

https://github.com/kubernetes/ingress-gce/pull/1017
https://github.com/kubernetes/ingress-gce/pull/1019
https://github.com/kubernetes/ingress-gce/pull/1020
https://github.com/kubernetes/ingress-gce/pull/1021

Current docs for BackendConfig https://cloud.google.com/kubernetes-engine/docs/concepts/backendconfig

/cc @spencerhance @rramkumar1 could you provide an update here, please?

**Comment by spencerhance** [comment]
@rnaveiras The implementation is complete, but it is not available directly from GKE yet.  We are hoping to make that available soon, but in the meantime the only option is to self-manage the controller.

**Comment by rnaveiras** [comment]
@spencerhance thanks, that are great news. can I .assume that the maintainers will cut a new release and they will update the [GKE Version Mapping](https://github.com/kubernetes/ingress-gce#gke-version-mapping) accordingly?

I believe that we can close this issue then after that.

**Comment by lpzdvd-packlink** [comment]
+1 here
We'd like to enforce TLS v1.2 using GKE due to credit card payments.
Any updates about it?

**Comment by asgoel** [comment]
@spencerhance is there documentation anywhere on how to setup the `FrontendConfig` on a ingress when using a self-managed controller?

**Comment by spencerhance** [comment]
@rnaveiras if you checkout the latest 1.9 tag and use "--enable-frontend-config" you should have access to the feature

@asgoel We still plan on releasing this very soon, which will include official documentation.  For the self managed controller here is an example yaml:

```yaml
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: ssl-fc
spec:
  sslpolicy: policy-name
```

The ingress annotation is: ```networking.gke.io/v1beta1.FrontendConfig: 'ssl-fc'```

**Comment by minac** [comment]
Sorry to bother, but TLS 1.0 and 1.1 are being deprecated everywhere, and I'm eager to get this set up. 

I understand that in GCP it is possible to manually edit the Frontend Configuration to match a more restrictive SSL Policy, but ideally one would set the policy in Kubernetes (as above), given that the load balancers are dynamically generated by the ingress.

How soon do you think is "very soon" @spencerhance? 🙏 

Do you know if it will be available for all versions of GKE clusters or just for some?

Thanks!

**Comment by spencerhance** [comment]
@minac This should be coming to the rapid channel in O(weeks), and then to regular channel within a month after that

**Comment by minac** [comment]
Thanks for the update, @spencerhance! Will it also be made available to older GKE versions not on a channel like 1.14?

**Comment by spencerhance** [comment]
@minac Most likely not 1.14.  Typically versions in "Regular" channel also are available in "no channel" so that they can be upgraded to.  However, we usually do not cherry-pick new features to k8s versions older than that.

**Comment by rschoultz** [comment]
Hi, do you know when this might hit the rapid channel or other?

**Comment by philipp-hb** [comment]
according to the documentation, it should already be in rapid as beta
https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#ssl

**Comment by spencerhance** [comment]
Hi @rschoultz @philipp-hb, 

Yes it is currently available in 1.17.6-gke.11 (Rapid Channel).  That ingress features page is the correct documentation.

**Comment by iagomelanias** [comment]
Very excited to use this feature when it's available on the regular channel.

**Comment by abdidarmawan007** [comment]
i try check default ingress gce in GKE stable channel 1.14.x use tls 1.0 and 1.1

Fiture SSL Policies still beta in GKE 1.17.6

**Comment by marnovo** [comment]
Trying to infer from the comments/statuses: is it reasonable to infer we would see this hitting the regular channels now in Aug-Sep/2020 or I am missing something? 

P.s.: let me know if tracking this (thus my question) would be more appropriate elsewhere. Did a lot of search but Google issue tracker tickets seem hopelessly outdated…

**Comment by lukas1994** [comment]
I need to disable TLS 1.0 due to get access to a third-party API. When will this be available in the regular channel? Is there an easy workaround for now? Can I just set an SSL policy manually after each k8s apply?

**Comment by BusiPlay** [comment]
> I need to disable TLS 1.0 due to get access to a third-party API. When will this be available in the regular channel? Is there an easy workaround for now? Can I just set an SSL policy manually after each k8s apply?

Yes, just set the SSL policy after apply https://cloud.google.com/load-balancing/docs/use-ssl-policies#attach-policy

**Comment by spencerhance** [comment]
Hi @lukas1994, this is available in regular channel via 1.17 :)

**Comment by marnovo** [comment]
Can confirm availability on regular, finally we were able to disable TLS 1.0.

**Comment by swetharepakula** [comment]
Closing as this feature has been implemented.
