### ISSUE TITLE
GCE ingress L4 Support

### ISSUE THREAD

**Issue by Kripu77** [kubernetes/ingress-gce#2460]
Hi all, given GCE ingress is a layer 7 load balancer is there any possibility of having layer 4 LB support in the future?

**Comment by swetharepakula** [comment]
L4 LB Support is available by configuring Service type LoadBalancer resources.

**Comment by Kripu77** [comment]
Hi Sweta, thank you for your response. I was looking for a workaround to have the ingress controller provision a Layer 4 load balancer, instead of directly using a service type as LoadBalancer in the service resource manifest.

**Comment by swetharepakula** [comment]
@Kripu77, can you expand more on why you would like to use the Ingress API over the Service API to configure/provision an L4 Load Balancer?

I am trying to understand what is missing from the existing Services API?

**Comment by Kripu77** [comment]
> @Kripu77, can you expand more on why you would like to use the Ingress API over the Service API to configure/provision an L4 Load Balancer?
> 
> I am trying to understand what is missing from the existing Services API?

@swetharepakula, we prefer using the Ingress API over the Service API to set up a Layer 4 Load Balancer because we want a single load balancer that can handle both Layer 4 and Layer 7 protocols. We use MQTT, which is a Layer 4 protocol, and we also have web services that uses Layer 7 (HTTP). Right now, with the current GCE ingress setup, we can't have just one load balancer for both types of traffic.

Because of this, we had to create a separate Layer 4 Load Balancer just for MQTT which is a cost implication as we need to reserve a static IP, provision a external load balancer. 

If GCE Ingress could work with both Layer 4 and Layer 7, we wouldn't need to do this.


Looking forward to your input if I'm wrong in above.



Thanks,
Kripu

**Comment by cezarygerard** [comment]
If I understand correctly you want just 1 kubernetes object and 1 IP address to provision both L7 and L4 load balancers?

This sounds like feature request for our  Gateway API implementation https://cloud.google.com/kubernetes-engine/docs/concepts/gateway-api 

We have this on the roadmap, but probably not this year

**Comment by Kripu77** [comment]
> If I understand correctly you want just 1 kubernetes object and 1 IP address to provision both L7 and L4 load balancers?
> 
> This sounds like feature request for our Gateway API implementation https://cloud.google.com/kubernetes-engine/docs/concepts/gateway-api
> 
> We have this on the roadmap, but probably not this year

@cezarygerard you're correct. Any chance this feature making to GCE ingress as well?
