### ISSUE TITLE
Rewrite ingress-gce general documentation

### ISSUE THREAD

**Issue by nicksardo** [kubernetes/ingress-gce#249]
TODO: Rewrite README.md emphasizing on the features this controller does support and provide links to the appropriate example directories.

**Comment by leedsjb** [comment]
Please note the file ingress-app.yaml referenced in README.md does not exist in the repo. Please see: https://github.com/kubernetes/ingress-gce/pull/150 where this file was removed.

**Comment by nicksardo** [comment]
Be sure to mention how users should configure their timeouts in their applications: https://github.com/kubernetes/ingress-gce/issues/245

**Comment by cceckman** [comment]
And note that the file `rc.yaml` listed in README.md does not exist in the repo.

**Comment by rramkumar1** [comment]
@leedsjb @cceckman Working on a fix for that. Thanks for pointing it out.

**Comment by rramkumar1** [comment]
Closing this bug since the scope is quite broad. We will file individual issues for each docs fix.

/close
