### ISSUE TITLE
GCE: Converting ephemeral IP to static doesn't update related TargetHTTPSProxy

### ISSUE THREAD

**Issue by kimroen** [kubernetes/ingress-gce#259]
This could be user error or issues with documentation, but I was encouraged to make an issue after first commenting on the help document I was following, so here goes:

I was going through [this tutorial on getting an Ingress set up](https://cloud.google.com/kubernetes-engine/docs/tutorials/http-balancer), and then later ran into some issues getting TSL-termination working. When visiting the domain using `https://`, the browser didn't get a response from the server.

After some head-scratching, I realized the problem I was having was that the TargetHTTPSProxy and TargetHTTProxy had different IP-addresses, so HTTPS-traffic never reached my URL map.

Step 5 of the document linked above explains how to convert the ephemeral IP you get when creating the Ingress to a static one. I had followed this advice, but only the TargetHTTPProxy was using this static IP, and the TargetHTTPSProxy was still using an ephemeral IP that had changed.

Some speculation on a few different things the problem could be:

1. The TargetHTTPSProxy didn't use the static IP automatically as I was expecting
2. The `kubernetes.io/ingress.global-static-ip-name` annotation on the Ingress needs to be set when converting the IP
3. HTTP and HTTPS were already using different IP-addresses before I converted and I just didn't notice I was only converting one of them

Hopefully that helps!

**Comment by nicksardo** [comment]
Which version of Kubernetes were you using?

**Comment by kimroen** [comment]
This is a newly created cluster, so it's running the default (`1.8.8-gke.0`).

**Comment by rramkumar1** [comment]
@kimroen Is this still an issue? 

I'm curious how this happened because if you create an HTTP(S) Ingress from scratch, we automatically allocate a reserved IP for you.

**Comment by kimroen** [comment]
@rramkumar1 Hi! I fixed it manually when it happened so I'm not sure if it's still an issue with new Ingress setups.

Like I say in the original issue, this happened as I was following a tutorial (linked above), so it's very possible that I messed something up or that the tutorial was unclear. In either case, I ended up with two proxies using different IP-addresses, one ephemeral and one static.

**Comment by swetharepakula** [comment]
Closing since there has been no update since 2019.
