### ISSUE TITLE
Does not work if workers are in different subnet. 

### ISSUE THREAD

**Issue by manishrajkarnikar** [kubernetes/ingress-gce#282]
I have workers spanning different subnet for security reasons.  I see following error during the creation of unmanaged instance group. As a result, it cannot add any instance in the group

``` 
Requeuing "default/zoneprinter" due to error: [googleapi: Error 400: Resource 'projects/xxxx/zones/us-central1-b/instances/k8s-ig--xxxxxx' is expected to be in the subnetwork 'projects/xxxx/regions/us-central1/subnetworks/app-hosting-us-central1' but is in the subnetwork 'projects/xxxx/regions/us-central1/subnetworks/platform-us-central1'., wrongSubnetwork ....] (ingresses)

 ```

**Comment by nicksardo** [comment]
Can you describe your setup? Are you using multi-cluster or single cluster ingress?

**Comment by manishrajkarnikar** [comment]
@nicksardo I am using single cluster. But my masters are in different subnet than the workers.
