### ISSUE TITLE
Align node filtering with service controller

### ISSUE THREAD

**Issue by octplane** [kubernetes/ingress-gce#292]
Hello,

Would there be any interest in aligning the current node selection currently done when building the Instances Group:

https://github.com/kubernetes/ingress-gce/blob/master/pkg/controller/utils.go#L202-L215

- code ignores `Unschedulable` nodes,

to the one in k8s:

https://github.com/kubernetes/kubernetes/blob/97fdf8ac70dfdaf07074dee6b6cb345be71e96ec/pkg/controller/service/service_controller.go#L585-L619

code ignores:
- `Unschedulable` nodes
- Nodes with the label `node-role.kubernetes.io/master` 
- Nodes with the label `alpha.service-controller.kubernetes.io/exclude-balancer`

More generally, it might be nice to allow to blacklist labels via configuration.

**Comment by rramkumar1** [comment]
Fixed by #370 
/close
