### ISSUE TITLE
Invalid certificate leads to firewall rule no longer being updated on GKE

### ISSUE THREAD

**Issue by svenbovens** [kubernetes/ingress-gce#298]
Related to #294. We had an invalid certificate pointed to by an ingress leading to an event "Error 400: The SSL certificate could not be parsed." shown on all ingresses.

When creating a new ingress in this state everything would be done properly except adapting the firewall rule to add the new port. This lead to failing health checks for the backend and the ingress not being usable.

In the logs of that firewall rule, the events with subtype _compute.firewalls.update_ would no longer be seen.

Two things can be done here: 

- if there's an invalid certificate pointed to by an (unrelated) ingress, the firewall rule should still be adapted for new ingresses.
- if the update of the firewall rule fails for some reason, this should be shown somewhere on the ingress.

We discovered the issue on gke 1.8. The issue persisted after an update to 1.9.7-gke.1.

When the invalid certificate was fixed, the firewall rules are being updated again.

**Comment by nicksardo** [comment]
Root cause is https://github.com/kubernetes/ingress-gce/issues/44
