### ISSUE TITLE
[GLBC] Changing front-end configuration does not remove unnecessary target proxies/ssl-certs

### ISSUE THREAD

**Issue by bowei** [kubernetes/ingress-gce#32]
_From @tonglil on March 20, 2017 17:59_

Porting this issue from contrib over: https://github.com/kubernetes/contrib/issues/1517.

There is no enforcement of the annotation `kubernetes.io/ingress.allow-http: "false"` when it is set to false, after previously being set to true or unset.

See during the edge hop:
- Checks annotation: https://github.com/kubernetes/ingress/blob/37bdb3952e090e50f44207ad0e54b1f2a4ef1055/controllers/gce/loadbalancers/loadbalancers.go#L598-L602
- Creates: https://github.com/kubernetes/ingress/blob/37bdb3952e090e50f44207ad0e54b1f2a4ef1055/controllers/gce/loadbalancers/loadbalancers.go#L619-L627

No deletion/cleanup enforcement happens if it is set to false.

_Copied from original issue: kubernetes/ingress-nginx#468_

**Comment by bowei** [comment]
_From @nicksardo on April 21, 2017 19:7_

No deletion/cleanup happens when removing the TLS section or pre-shared cert annotation.  Will rename this to be more general.

**Comment by bowei** [comment]
_From @nicksardo on April 24, 2017 18:41_

Furthermore, if you disable TLS on an active ingress, then delete the ingress resource, the controller will fail to destroy resources. It doesn't try deleting the https forwarding rule or https target proxy, which means the URL map is still used.

**Comment by bowei** [comment]
_From @montanaflynn on August 7, 2017 23:3_

Any updates on this? We have a production ingress and are looking for a workaround.

**Comment by bowei** [comment]
_From @nicksardo on August 7, 2017 23:19_

@montanaflynn There's no fix yet.

You should be able to delete the HTTP forwarding rule and target proxy manually in the GCP Console.  Highly recommend duplicating the issue in a test cluster and trying it out first.

**Comment by bluecmd** [comment]
It is still relevant, I just hit this today. /remove-lifecycle stale

**Comment by MichielDeMey** [comment]
Same issue here, changed to HTTPS only and the HTTP frontend was not deleted.
I deleted the HTTP frontend manually from the LB and that did not seem to have any side-effects on the traffic.

**Comment by metral** [comment]
Hitting this on v1.1.1

/remove-lifecycle stale

**Comment by raelga** [comment]
Still happening, added `kubernetes.io/ingress.allow-http: "false"` and the HTTP Frontend was not deleted.

_Cleaned_ manually after adding the annotation by updating the Ingress Load Balancer removing the HTTP Frontend. Eventually, the HTTP Target Proxy was deleted by GCP.
