### ISSUE TITLE
Does/will the GCE ingress controller support whitelist-source-range?

### ISSUE THREAD

**Issue by bowei** [kubernetes/ingress-gce#38]
_From @nickform on April 6, 2017 12:11_

Can anyone comment on when we will be able to use the 'whitelist-source-range' annotation with the GCE Ingress Controller? From Googling plus experimentation the answer is not "it works right now" but perhaps we've made a mistake? If not, is this something which might happen in future? Thanks!

_Copied from original issue: kubernetes/ingress-nginx#566_

**Comment by bowei** [comment]
_From @nicksardo on April 6, 2017 17:59_

The L7 Google Cloud Load Balancer does not currently have firewall rules for source IPs. I'll keep this open in case the load balancer supports it in the future.

**Comment by bowei** [comment]
_From @albertsun on April 28, 2017 17:6_

This would be extremely useful to have. @nicksardo is there an open issue somewhere for the L7 LB to support source IP firewall rules where we can track the status of it?

**Comment by bowei** [comment]
_From @nicksardo on April 28, 2017 17:30_

https://issuetracker.google.com/issues/35904903

**Comment by mooperd** [comment]
Hi, what is the status of this issue? We'd like to be able to control access to specific k8s services. This seems like the most likely way of handling it.

**Comment by tonglil** [comment]
It is still relevant. The bug tracker also receives +1s on a regular basis.

**Comment by slabber** [comment]
Now that we have Cloud Armor and can restrict ingress based on IP, it would be interesting to incorporate Cloud Armor rules in ingress annotations.

Is there a plan for that?

**Comment by rramkumar1** [comment]
@slabber Cloud Armor integration with ingress-gce will be coming very soon :)

**Comment by nicksardo** [comment]
/close
Now available in latest version of ingress-gce.

**Comment by cfebs** [comment]
@nicksardo - is a specific k8s version required to use the whitelist annotation? Or will it just start working for gce ingress?

**Comment by nickform** [comment]
This is great news - thanks to everyone who has tracked and worked on this.

**Comment by guishimamoto** [comment]
Anyone was able to use the whitelist annotation in GCE ?

**Comment by rramkumar1** [comment]
Documentation for all our new feature support (IAP, CDN, CloudArmor) will be coming very soon.

**Comment by rramkumar1** [comment]
@mnemitz  See https://cloud.google.com/kubernetes-engine/docs/concepts/backendconfig

**Comment by vTNT** [comment]
It's not a very good plan. It's too complicated
