### ISSUE TITLE
Feature Request: Name GCP resources better

### ISSUE THREAD

**Issue by ashi009** [kubernetes/ingress-gce#397]
It's annoying to see a backend being referred as `k8s-be-31073--d4ff5a71b6e25bd6`, or an instance group being named as `k8s-ig--d4ff5a71b6e25bd6`.  All these names are totally meaningless on the GKE console.

Is it possible to give them some more meaningful names?

**Comment by mayansalama** [comment]
Piggybacking onto this, it would be useful if there were a way to configure the name of the backend-service created by the Ingress.

I've been looking into using IAP for authentication, however getting user ID in GKE requires the backend service ID, which is a bit of a chicken and egg problem. Right now getting it working properly requires either redeploying, dynamic config, or looking up the service ID live - being able to name the backend service ID would make this somewhat easier.

**Comment by rramkumar1** [comment]
@skmatti CC'ing you since you are looking into this.

**Comment by shpml** [comment]
Is there any progress on this? Trying to view metrics and create alerts based on response codes with a backend being referred as above isn't very informative. Ideally I'd like to see the k8's service name.

**Comment by swetharepakula** [comment]
Closing as this issue hasn't had any comments in over a year. The newer GCP resources like NEGs do have service names added into the name.
