### ISSUE TITLE
[GLBC] Garbage collection runs too frequently - after every sync

### ISSUE THREAD

**Issue by bowei** [kubernetes/ingress-gce#40]
_From @nicksardo on April 28, 2017 22:5_

GC runs at the end of every sync for ever ingress. If there are many ingress objects, this results in many GCP calls. It's even more troublesome in the case of federated clusters.

We should perform a loadbalancer-specific GC on delete notification, but only run cluster-wide GC on a less frequent basis, such as resyncPeriod (set to 10min).
cc @madhusudancs @csbell 

_Copied from original issue: kubernetes/ingress-nginx#674_

**Comment by swetharepakula** [comment]
This has been fixed with the finalizers & GC V2.
