### ISSUE TITLE
Multiple pre-shared certificates not working

### ISSUE THREAD

**Issue by Kronuz** [kubernetes/ingress-gce#419]
In the documentation (https://github.com/kubernetes/ingress-gce/blob/fea549960931d72f6bd9505796d75ea8a085f92b/README.md#gcp-ssl-cert) it says multiple pre-shared certs can be specified as follows:

```yaml
  annotations:
      ingress.gcp.kubernetes.io/pre-shared-cert: "my-certificate-1, my-certificate-2, my-certificate-3"
```

However, when I try that, I get the following error and certificates are not loaded:
```
Warning  GCE      4s                  loadbalancer-controller  googleapi: Error 400: Invalid value 'my-certificate-1, my-certificate-2, my-certificate-3'. Values must match the following regular expression: '[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?', invalidParameter
```

Version is:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.3", GitCommit:"9b5b719c5f295c99de68ffb5b63101b0e0175376", GitTreeState:"clean", BuildDate:"2018-05-31T18:32:23Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by rramkumar1** [comment]
What version of the ingress controller are you running? Based on your k8s version, I would think it is a version that does not support multiple TLS. Note that multiple TLS is supported in ingress-gce version 1.1 and higher

**Comment by rramkumar1** [comment]
ping @Kronuz

**Comment by Kronuz** [comment]
Yes, I was using v1.9.7-gke.3, and neither annotations nor multiple tls.secretName worked. With v1.10 at least the later works; but to be honest, I didn’t try comma separated certificate names in annotations with it, only secretName.

**Comment by bowei** [comment]
Can this be closed?

**Comment by rramkumar1** [comment]
@Kronuz going to close the issue out for now since it looks to be resolved.

Please reopen if you have further concerns.
