### ISSUE TITLE
[GLBC] LB garbage collection orphans named ports in instance groups

### ISSUE THREAD

**Issue by bowei** [kubernetes/ingress-gce#43]
_From @nicksardo on May 8, 2017 18:54_

The GLBC does not remove the named port from an instance group when a backend is being deleted.

If users are frequently created/deleting services and ingresses, instance groups will become polluted with old node ports. Eventually, users will hit a max limit. 
```
Exceeded limit 'MAX_DISTINCT_NAMED_PORTS' on resource 'k8s-ig--aaaaaaaaaaaa'
```

Temporary workaround
```shell
region=us-central1
cluster_id=$(kubectl get configmaps ingress-uid -o jsonpath='{.data.uid}' --namespace=kube-system)
ports=$(gcloud compute backend-services list --global --format='value(port,port)' |  xargs printf 'port%s:%s,')
for zone in b c f; do
  gcloud compute instance-groups unmanaged set-named-ports k8s-ig--$cluster_id --zone=$region-$zone --named-ports=$ports
done
```
Modify the region and list of zone suffix in the script.

_Copied from original issue: kubernetes/ingress-nginx#695_

**Comment by bowei** [comment]
_From @nicksardo on May 26, 2017 22:20_

Requires https://github.com/kubernetes/kubernetes/pull/46457

**Comment by bowei** [comment]
_From @porridge on June 5, 2017 12:44_

I see that the dependency was merged a week ago. Is there a plan/ETA for this one?

**Comment by bowei** [comment]
_From @nicksardo on June 5, 2017 17:33_

@porridge I'm waiting on one more PR to merge before we can update this repo's vendored dependencies. 

I expect to have a fix in for the next release of GLBC, but there's no ETA for that just yet.

**Comment by bowei** [comment]
_From @pawloKoder on July 4, 2017 15:54_

Any update on this issue?

**Comment by bowei** [comment]
_From @G-Harmon on September 27, 2017 23:53_

Hi, I'm starting to work on this now, as my first Kubernetes fix.

**Comment by icco** [comment]
I'm seeing this still, as the suggested fix doesn't work. Any other thoughts?

**Comment by kraklin** [comment]
Any new information about this issue. We had to create new cluster and migrate all things to it because of this bug :/

**Comment by G-Harmon** [comment]
Why didn't the suggested workaround work, @icco?

**Comment by icco** [comment]
@G-Harmon not sure, but it comes back like once a week.

**Comment by EliezerIsrael** [comment]
I just got bit by this one.  Any news?

**Comment by DaveWelling** [comment]
It seems like the workaround for this is to move the orphaned ports to another region? Is that right? I'm guessing that means there is no way to directly remove the ports? I cannot see any obvious method via the gcloud compute instance-groups cli. Did anybody find a better solution? I'm worried I will just have to jump from region to region.
Obviously, I'm also going to avoid recreating ingresses unnecessarily, but that also doesn't seem like permanent solution when we are in heavy development and have frequent deployments.

It seems strange to me that more people are not hitting this issue. Is there some mitigating difference in now people are deploying services that I haven't thought of?

**Comment by swetharepakula** [comment]
As the last report of this was almost a year ago, we are closing out this issue. We recommend users to move to NEGs (container-native) and migrate off of InstanceGroups. If there are still issues, please open a new github issue. Thanks!
