### ISSUE TITLE
When using NEG services only, the controller still creates instance groups

### ISSUE THREAD

**Issue by lbernail** [kubernetes/ingress-gce#433]
Hello

We have been testing the NEG feature for a little while and I noticed that even when we only have services using NEGs, the controller still creates the instance groups (they are not attached to the backend-services which only point to NEGs)

Is this expected?

Laurent

**Comment by freehan** [comment]
Based on the current implementation (https://github.com/kubernetes/ingress-gce/blob/master/pkg/instances/instances.go#L86), even if the name ports are empty. Instance groups are still created. 

The `default-http-backend` service under kube-system namespace is still not default to use NEG. Ingress controller will attach this backend (Instance Group) to the LB if the ingress does not include default backend.

**Comment by lbernail** [comment]
What about not calling `ensureInstanceGroupsAndPorts` in `ensureIngress` if the service has the NEG annotation?
We'd still need to handle the default-http-backend case. I'm not very familiar with the code yet but I'm happy to work on a PR if you have ideas on how to handle this

**Comment by freehan** [comment]
Yeah. That is what I plan to do. But need to watch out GC logic for this though.

**Comment by lbernail** [comment]
I just built a controller from master and tested it
It worked great. Thanks!
