### ISSUE TITLE
GLBC: Each ingress sync updates resources for all ingresses

### ISSUE THREAD

**Issue by bowei** [kubernetes/ingress-gce#44]
_From @nicksardo on July 11, 2017 23:58_

For every ingress, the controller runs resource synchronization for all ingresses, thus resulting in unnecessary work.

Furthermore, if a GCP error occurs when handling one of the ingress resources, an event will be raised for every ingress resource.

_Copied from original issue: kubernetes/ingress-nginx#950_

**Comment by bowei** [comment]
_From @thockin on August 3, 2017 16:46_

What event?

**Comment by bowei** [comment]
_From @nicksardo on August 3, 2017 17:10_

A K8s Event record noting an error/warning message.

Take a look at this code: https://github.com/kubernetes/ingress/blob/7b38e5a36ed7e097e1cd98aca0f37c504059ab4c/controllers/gce/controller/controller.go#L311-L320
Checkpoint (https://github.com/kubernetes/ingress/blob/7b38e5a36ed7e097e1cd98aca0f37c504059ab4c/controllers/gce/controller/cluster_manager.go#L141-L149) creates/manages the resources for all ingresses. If there's an error, it's returned and an event is recorded for the ingress which caused the sync, but not necessarily the ingress which caused the error.

**Comment by bowei** [comment]
_From @thockin on August 3, 2017 17:12_

blech!

**Comment by mooperd** [comment]
+1 Anyone looking at this. Its quite annoying.

**Comment by bowei** [comment]
We are actively working this issue. Expect an update in a few weeks.

**Comment by mooperd** [comment]
@nicksardo Hey, is this issue fixed? When is it being rolled out?

**Comment by nicksardo** [comment]
The logic was changed to single the relevant resources. Assuming testing goes well, it'll make K8s 1.10. Currently unknown which 1.9 or 1.8 patch releases will get this new version.
