### ISSUE TITLE
Allow configuration-snippet Annotation.

### ISSUE THREAD

**Issue by jainishshah17** [kubernetes/ingress-gce#445]
I have need to do URL rewrite to use my application. I want to do following:

```
      rewrite ^/(v2)/token /artifactory/api/docker/null/v2/token;
      rewrite ^/(v2)/([^\/]*)/(.*) /artifactory/api/docker/$2/$1/$3;
```

It will be great to have support for `configuration-snippet`.

**Comment by rramkumar1** [comment]
Just found a duplicate issue #109. Going to close this out in favor of that one 

/close
