### ISSUE TITLE
ingress-gce fails to create backend services when across zones with different balancing modes

### ISSUE THREAD

**Issue by nimeshksingh** [kubernetes/ingress-gce#480]
We have a gke cluster with two zones, one of which was added significantly later than the other.  The ingress controller added backend services with a balancing mode of UTILIZATION for the first zone, and when we added the second zone it set the balancing mode in the new zone to RATE.  Now when we try to add new backend services, it goes into a failure loop where it tries the RATE balancing mode, which fails in one zone, then tries the UTILIZATION balancing mode, which fails in the second zone.  This continues forever and we're blocked from adding new backends.

Image showing the initial state before trying to add a second backend service:
<img width="690" alt="screen shot 2018-09-17 at 5 45 12 pm" src="https://user-images.githubusercontent.com/7454380/45658032-b5f47d00-baa1-11e8-9c9e-2c78be01c62d.png">

GKE Master version: 1.10.7-gke.1

**Comment by rramkumar1** [comment]
@nimeshksingh Is this still occurring? My understanding is that this should already be handled semi-gracefully but maybe you have hit an edge case.

**Comment by swetharepakula** [comment]
Closing as there has been no update since 2019.
