### ISSUE TITLE
Ingress-GCE does not GC LB resources when ingress class changed and no other ingress on GCE exists

### ISSUE THREAD

**Issue by freehan** [kubernetes/ingress-gce#481]
Repro steps:
1. Make sure there is no ingress exists in the cluster.
2. Create a test ingress with no ingress class annotation
3. Wait for ingress-gce controller to provision LB
4. Add a non-GCE ingress class on the test ingress
5. The LB resources will be leaked. 

Root cause:
- Ingress-gce controller does not act on non-relevant ingresses.  https://github.com/kubernetes/ingress-gce/blob/release-1.3/pkg/controller/controller.go#L127
- Ingress-gce controller only GC resources in the ingress sync loop.
https://github.com/kubernetes/ingress-gce/blob/release-1.3/pkg/controller/controller.go#L287

**Comment by rramkumar1** [comment]
@pondohva Thanks, send us a PR whenever you are ready!

/assign @pondohva
