### ISSUE TITLE
can not access  nginx through ingress and problem in curl 

### ISSUE THREAD

**Issue by AhmedMItman** [kubernetes/ingress-gce#490]
i have kubernetes-cluster v1.10 over centos 7
i am trying to deploy ingress , i followed video 

and finally i found 
-> kubectl get ing
NAME      HOSTS              ADDRESS   PORTS     AGE
nginx     kub-master                               80, 443     9h
there is now address for nginx 

-> and when i execute "  curl --ipv4 -v http://kub-master "
* About to connect() to kub-master port 80 (#0)
*   Trying kub-master...
* Connection refused
* Failed connect to kub-master; Connection refused
* Closing connection 0
curl: (7) Failed connect to kub-master; Connection refused
 
-> kubectl cluster-info 
Kubernetes master is running at http://localhost:8080
KubeDNS is running at http://localhost:8080/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.

-> systemctl restart flanneld
Job for flanneld.service failed because a timeout was exceeded. See "systemctl status flanneld.service" and "journalctl -xe" for details.

-> systemctl status flanneld
● flanneld.service - Flanneld overlay address etcd agent
   Loaded: loaded (/usr/lib/systemd/system/flanneld.service; enabled; vendor preset: disabled)
   Active: activating (start) since Fri 2018-09-21 17:22:37 EDT; 1min 10s ago
 Main PID: 18327 (flanneld)
   Memory: 22.8M
   CGroup: /system.slice/flanneld.service
           └─18327 /usr/bin/flanneld -etcd-endpoints=http://kube-master:2379 -etcd-prefix=/kube-centos/network

Sep 21 17:23:38 kub-mst.coral.io flanneld-start[18327]: E0921 17:23:38.833256   18327 network.go:102] failed to register network: operation not supported

#how to solve this issue and access port 80  ?

**Comment by bowei** [comment]
Are you running on GKE on Google Cloud?

**Comment by AhmedMItman** [comment]
@bowei No, Over physical server for master OS centos 7 and VM for slave OS centos 7

**Comment by bowei** [comment]
You should file the bug against the appropriate repository. This repo is only for Ingress resources running on GCP.
