### ISSUE TITLE
Zonelister logic prevents instance removal from instance group & instance group GC

### ISSUE THREAD

**Issue by bowei** [kubernetes/ingress-gce#50]
_From @nikhiljindal on July 25, 2017 1:38_

Looking at the code (https://github.com/kubernetes/ingress/blob/a58b80017170eecbe8b2d6573b66192cafe0d32a/controllers/gce/controller/controller.go#L177), it looks like we are not doing anything when nodes are added and deleted. We should be updating the instance group when that happens.

Am I missing something?

_Copied from original issue: kubernetes/ingress-nginx#1012_

**Comment by bowei** [comment]
_From @nikhiljindal on July 25, 2017 1:39_

@nicksardo pointed out that the logic was removed in https://github.com/kubernetes/ingress/commit/c7c2a564a994ec28de9fe5fb0b4a1847be94e0ad#diff-9141c651905f3492033cf255f8e12fd7L176.

@aledbf Was that intentional?

**Comment by bowei** [comment]
_From @nicksardo on July 25, 2017 18:18_

Quick FYI: the instance groups are eventually synced when the resync period occurs for any ingress. This may explain why nobody has noticed this in practice.

**Comment by bowei** [comment]
_From @nicksardo on July 31, 2017 23:47_

This still occurs despite having the fix.  I'm guessing that the handler is called when the node is added; however, it's NotReady state prevents the instance group from being updated. I don't know why the handler isn't called again when the node becomes Ready.

**Comment by bowei** [comment]
_From @aledbf on August 1, 2017 0:0_

@nicksardo maybe because the handler does not have an `UpdateFunc`?

**Comment by bowei** [comment]
_From @nicksardo on August 1, 2017 0:32_

Ah, that would certainly do it. According to the comment, we don't want to have an `UpdateFunc` due to the frequency.  @nikhiljindal and I need to look more closely at the instance sync logic.

**Comment by bowei** [comment]
_From @nikhiljindal on August 1, 2017 17:8_

If there was a way to find out the update, we could add an UpdateFunc that adds the node to queue only if there has been a "relevant change" in node. Node's heartbeat being updated, for example, is not a "relevant change".

**Comment by bowei** [comment]
_From @nicksardo on August 1, 2017 17:14_

Right, not a quick change though.

**Comment by bowei** [comment]
_From @nicksardo on August 3, 2017 0:54_

Looks like removing nodes from instances groups has never worked. 
```
I0803 00:20:41.239780       5 instances.go:234] Syncing nodes [gke-testingress-default-pool-9818f010-zcxl gke-testingress-default-pool-9818f010-h3b8 gke-testingress-default-pool-9818f010-jk3f]
I0803 00:20:41.367945       5 instances.go:265] Removing nodes from IG: [gke-testingress-default-pool-9818f010-6znn gke-testingress-default-pool-9818f010-dz9r]
E0803 00:20:41.368941       5 instances.go:191] Failed to get zones for gke-testingress-default-pool-9818f010-6znn: node not found gke-testingress-default-pool-9818f010-6znn, skipping
E0803 00:20:41.369292       5 instances.go:191] Failed to get zones for gke-testingress-default-pool-9818f010-dz9r: node not found gke-testingress-default-pool-9818f010-dz9r, skipping
I0803 00:20:41.369599       5 utils.go:212] Syncing gke-testingress-default-pool-9818f010-8ffx
I0803 00:20:41.369912       5 instances.go:234] Syncing nodes [gke-testingress-default-pool-9818f010-zcxl gke-testingress-default-pool-9818f010-h3b8 gke-testingress-default-pool-9818f010-jk3f]
I0803 00:20:41.479824       5 instances.go:265] Removing nodes from IG: [gke-testingress-default-pool-9818f010-6znn gke-testingress-default-pool-9818f010-dz9r]
E0803 00:20:41.480328       5 instances.go:191] Failed to get zones for gke-testingress-default-pool-9818f010-6znn: node not found gke-testingress-default-pool-9818f010-6znn, skipping
E0803 00:20:41.481218       5 instances.go:191] Failed to get zones for gke-testingress-default-pool-9818f010-dz9r: node not found gke-testingress-default-pool-9818f010-dz9r, skipping
I0803 00:20:46.453664       5 utils.go:212] Syncing gke-testingress-default-pool-9818f010-dz9r
I0803 00:20:46.454195       5 instances.go:234] Syncing nodes [gke-testingress-default-pool-9818f010-h3b8 gke-testingress-default-pool-9818f010-jk3f gke-testingress-default-pool-9818f010-zcxl]
I0803 00:20:46.545582       5 utils.go:212] Syncing gke-testingress-default-pool-9818f010-6znn
I0803 00:20:46.546366       5 instances.go:234] Syncing nodes [gke-testingress-default-pool-9818f010-h3b8 gke-testingress-default-pool-9818f010-jk3f gke-testingress-default-pool-9818f010-zcxl]
```

**Comment by bowei** [comment]
_From @nicksardo on September 14, 2017 20:42_

Note: We also need to address node syncing with regards to large clusters. https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/12/artifacts/gce-scale-cluster-master/glbc.log

**Comment by gkop** [comment]
What are the workarounds for this in practice? Does everybody follow up the k8s delete node API call with a second call to the GCP API? (that's what I do - it's annoying...)

**Comment by pondohva** [comment]
> _From @nicksardo on August 3, 2017 0:54_
> 
> Looks like removing nodes from instances groups has never worked.
> 
> ```
> I0803 00:20:41.239780       5 instances.go:234] Syncing nodes [gke-testingress-default-pool-9818f010-zcxl gke-testingress-default-pool-9818f010-h3b8 gke-testingress-default-pool-9818f010-jk3f]
> I0803 00:20:41.367945       5 instances.go:265] Removing nodes from IG: [gke-testingress-default-pool-9818f010-6znn gke-testingress-default-pool-9818f010-dz9r]
> E0803 00:20:41.368941       5 instances.go:191] Failed to get zones for gke-testingress-default-pool-9818f010-6znn: node not found gke-testingress-default-pool-9818f010-6znn, skipping
> E0803 00:20:41.369292       5 instances.go:191] Failed to get zones for gke-testingress-default-pool-9818f010-dz9r: node not found gke-testingress-default-pool-9818f010-dz9r, skipping
> I0803 00:20:41.369599       5 utils.go:212] Syncing gke-testingress-default-pool-9818f010-8ffx
> I0803 00:20:41.369912       5 instances.go:234] Syncing nodes [gke-testingress-default-pool-9818f010-zcxl gke-testingress-default-pool-9818f010-h3b8 gke-testingress-default-pool-9818f010-jk3f]
> I0803 00:20:41.479824       5 instances.go:265] Removing nodes from IG: [gke-testingress-default-pool-9818f010-6znn gke-testingress-default-pool-9818f010-dz9r]
> E0803 00:20:41.480328       5 instances.go:191] Failed to get zones for gke-testingress-default-pool-9818f010-6znn: node not found gke-testingress-default-pool-9818f010-6znn, skipping
> E0803 00:20:41.481218       5 instances.go:191] Failed to get zones for gke-testingress-default-pool-9818f010-dz9r: node not found gke-testingress-default-pool-9818f010-dz9r, skipping
> I0803 00:20:46.453664       5 utils.go:212] Syncing gke-testingress-default-pool-9818f010-dz9r
> I0803 00:20:46.454195       5 instances.go:234] Syncing nodes [gke-testingress-default-pool-9818f010-h3b8 gke-testingress-default-pool-9818f010-jk3f gke-testingress-default-pool-9818f010-zcxl]
> I0803 00:20:46.545582       5 utils.go:212] Syncing gke-testingress-default-pool-9818f010-6znn
> I0803 00:20:46.546366       5 instances.go:234] Syncing nodes [gke-testingress-default-pool-9818f010-h3b8 gke-testingress-default-pool-9818f010-jk3f gke-testingress-default-pool-9818f010-zcxl]
> ```

node can't be found because GetZoneFromNode filters nodes with not ready statuses. I opened PR to fix this particular issue. I'm working on Add/Update/Delete functions but it might take a lot of time.

I've found the way how I can connect node object from nodeInformer with ingresses:
1. find instance group for this node
2. iterate through backendPool.List() (BackendService) to find Backend with the Group field with instance group name from 1.
3. pass this BackendService to find ingresses with this BackendService in label "ingress.kubernetes.io/backends"

It looks ugly right now, but it's working. But I didn't find the way to track only relevant node updates.

**Comment by Aut0R3V** [comment]
@bowei anything that can be done here?

**Comment by swetharepakula** [comment]
There have been various fixes in this area to make the ingress controllers react to zone changes. If the issues still exist, please open a new issue with details.
