### ISSUE TITLE
Tracking issue for FrontendConfig work

### ISSUE THREAD

**Issue by rramkumar1** [kubernetes/ingress-gce#515]
For Ingress-GCE, we have the BackendConfig CRD which encapsulates features on the GCE Backend Service

Similarly, for frontend components of the load balancer (target proxy, url map, etc) we need a way to encapsulate features (i.e SSL Policy). The current method of using annotations will not scale.

Using this issue to track implementation of a "FrontendConfig" CRD. Ideally, we can provide the scaffolding and solicit members of the community to provide implementations for each feature.

/assign

**Comment by rramkumar1** [comment]
FYI @spencerhance

**Comment by psalaberria002** [comment]
Any update on this? It would be very nice to have the ability to change TLS options, ciphers, etc

**Comment by rramkumar1** [comment]
@spencerhance What do you think we should do with this issue?

**Comment by spencerhance** [comment]
@rramkumar1 I think we should close this since frontendconfig has been added, and keep around the issues regarding specific FC features (redirects, sslpolicy etc.)
