### ISSUE TITLE
Support session affinity via Ingress annotation

### ISSUE THREAD

**Issue by lornemet-eno** [kubernetes/ingress-gce#516]
ingress.kubernetes.io/affinity annotation is currently discarded.
The expected behavior would be to disable/enable session affinity based on the annotations value:
none (default) -> NONE
cookie -> GENERATED_COOKIE
??? -> CLIENT_IP

While simply turning on session affinity in the GCE ingress itself would not enable session affinity down to the POD (GCE would still send traffic to the NodePort of computes in the resourcegroup, which would not care about HTTP cookies), but would eliminate the need of manual/out-of-kubernetes configuration if additional measures are implamented (ie deployment -> daemonset, or pod antiaffinity + externalTrafficPolicy: Local).

**Comment by rramkumar1** [comment]
@lornemet-eno We will happily accept an implementation for this :)

See #513 for an example.

**Comment by rramkumar1** [comment]
@bpineau thanks for your work!

For everyone else, session affinity was implemented in https://github.com/kubernetes/ingress-gce/pull/526

That code will be shipping in approximately 2 weeks or so.

**Comment by rramkumar1** [comment]
FYI: This is now launched on GKE for cluster versions at or above 1.11.3-gke.18!

Docs: https://cloud.google.com/kubernetes-engine/docs/how-to/configure-backend-service

/close
