### ISSUE TITLE
ERR_SPDY_PROTOCOL_ERROR when streaming text/event-stream 

### ISSUE THREAD

**Issue by ilkerc** [kubernetes/ingress-gce#518]
Seeing error 'net::ERR_SPDY_PROTOCOL_ERROR 200' on console and connection gets dropped.
Not sure if it's because of the content type but happens only on text/eventstream s while sending the request over the ingress. Connection closes almost exactly 30 seconds.

Curl with -v
```
* HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, Client hello (1):
curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)
```

Anyone having insights about the issue?

**Comment by IvanAlegre** [comment]
Same happens to me. Content-type is application/json. Exactly closing connections on in second 30. Is there any way to tune this timeout?

@ilkerc did you fix it?

Thanks

**Comment by ilkerc** [comment]
@IvanAlegre

I think it’s related with the default proxy read, connect timeouts on our loadbalancer. Try increasing them

‘’’
proxy_connect_timeout       300;
proxy_send_timeout          300;
proxy_read_timeout          300;
send_timeout                300;
‘’’

**Comment by IvanAlegre** [comment]
Increased but with no luck. Still closing in 30 seconds. Anyway, in theory the default value for those values in our loadbalancer (nginx) are 60secs

**Comment by ilkerc** [comment]
@IvanAlegre

The following exact annotations solved my problem (server-snippets related with large js bundle downloads). You may give it a shot, good luck.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.org/server-snippets: sendfile on; sendfile_max_chunk 512k; tcp_nopush on;
```

**Comment by IvanAlegre** [comment]
Thanks again @ilkerc but this config wasn't the right one for us as we use GCE loadbalancers, not nginx class.

We finally made it work by creating a new service with a GCE BackendService https://cloud.google.com/load-balancing/docs/backend-service and change the destination service to the new one (without downtime).

It would be also possible to change manually the timeout in the backend service via web interface but this way is better.

**Comment by ilkerc** [comment]
Glad that worked out for you @IvanAlegre. Remembered that my whole point to switching nginx controller was using these costume snippets.

**Comment by yevon** [comment]
> @IvanAlegre
> 
> The following exact annotations solved my problem (server-snippets related with large js bundle downloads). You may give it a shot, good luck.
> 
> ```
> apiVersion: extensions/v1beta1
> kind: Ingress
> metadata:
>   annotations:
>     kubernetes.io/ingress.class: nginx
>     nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
>     nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
>     nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
>     nginx.org/server-snippets: sendfile on; sendfile_max_chunk 512k; tcp_nopush on;
> ```

This really helped a lot, it also helped to improve download speeds a lot over a nextcloud backend.
