### ISSUE TITLE
Document ingress.gcp.kubernetes.io/pre-shared-cert annotation

### ISSUE THREAD

**Issue by bowei** [kubernetes/ingress-gce#52]
Update GLBC documentation with this annotation + usage

**Comment by bowei** [comment]
https://github.com/kubernetes/ingress-nginx/issues/396

**Comment by nikhiljindal** [comment]
Not sure whats the scope of this issue. Is it for documentation on k8s.io/docs or documentation within this repo?
I updated docs in this repo to point out usage of that annotation: https://github.com/kubernetes/ingress-gce/pull/144.
@bowei @nicksardo What else is required?

**Comment by nicksardo** [comment]
The planned scope was just within this repo. I think your PR is sufficient. Thanks!
/close
