### ISSUE TITLE
Is github release tab forgotten or abandoned?

### ISSUE THREAD

**Issue by bpineau** [kubernetes/ingress-gce#534]
[raising the matter in case that's an oversight - otherwise please ignore and close]

The [Github "release" tab](https://github.com/kubernetes/ingress-gce/releases) was used to publish releases, up to v1.2.3.
That may drive people to think v1.2.3 is actually the last release? (at least it got me confused)

**Comment by rramkumar1** [comment]
Thanks to @MrHohn for fixing it!

/close
