### ISSUE TITLE
GKE BackendConfig permissions change `container.backendConfigs.get` does not exist

### ISSUE THREAD

**Issue by rllin-fathom** [kubernetes/ingress-gce#538]
I am getting the following error when trying to apply a yaml declaring a `BackendConfig`.  This was working as of yesterday for several months.  

```backendconfigs.cloud.google.com "XXXXXXXX" is forbidden: User "USER@DOMAIN.COM" cannot get backendconfigs.cloud.google.com in the namespace "NAMESPACE": Required "container.backendConfigs.get" permission.```

It seems like GKE changed permissions required to create BackendConfigs very recently?

however I can't find `container.backendConfigs.get` as a permission when I run `gcloud iam roles describe roles/container.admin` so it's unclear how to fix this.

**Comment by rramkumar1** [comment]
@rllin-fathom Looks like someone introduced a permission for this in GKE recently without letting us know :(

I looked in the UI and also could not find this permission. I will follow up on this and get back to you with the workaround. Sorry for the inconvenience

**Comment by rllin-fathom** [comment]
@rramkumar1 thanks, please keep us updated :)

**Comment by rramkumar1** [comment]
@rllin-fathom I synced up with our internal teams and looks like this permission has not propagated to UI yet. However you should be able to still give yourself or a different user that role via gcloud. 

Can you try this?

**Comment by rllin-fathom** [comment]
@rramkumar1 to be clear `container.backendConfigs.get` is not a role, it is a permission.  is it associated with a role in the backend?

From my understanding, it should be a permission for the role `roles/container.admin`, but as far as I can tell when I run `gcloud iam roles describe roles/container.admin`, `container.backendConfigs.get` doesn't show up.

maybe an example gcloud command from you would clear this up :)

**Comment by rramkumar1** [comment]
@rllin-fathom I've been told the UI for this has rolled out. Have you resolved this on your end? Can we close this issue?

**Comment by rllin-fathom** [comment]
yes if i have roles/container.admin then i can do things.  but we want to make permissions are granular as possible

![image](https://user-images.githubusercontent.com/25942131/48365892-0da60380-e661-11e8-96d0-417f23a07858.png)
I still do not see it in the UI, nor do I see it in `gcloud iam roles describe roles/container.admin`

**Comment by rramkumar1** [comment]
@rllin-fathom Sorry I was wrong, turns out the UI fix was submitted but that will take some time to rollout. 

Does this workaround work for you:

gcloud iam roles update [ROLE-ID] —project ...

**Comment by rllin-fathom** [comment]
@rramkumar1 great looks like the permission does just exist in the backend and I can just blindly attach it to a role.

thanks!

**Comment by rramkumar1** [comment]
@rllin-fathom Great! Sorry for the inconvenience. 

/close
