### ISSUE TITLE
Readiness Probe does not get reflected for NEG enabled ingress

### ISSUE THREAD

**Issue by freehan** [kubernetes/ingress-gce#541]
When the following conditions apply:
- NEG is enabled on the ingress referenced service 
- Service is ClusterIP type 

Then LB health check is created with default setting.

**Comment by manigandham** [comment]
We see this happen to on the latest version `1.11.2-gke.18` GKE clusters. NEG health checks are not reflecting any of the settings in the deployment YAML.

**Comment by hrdymchl** [comment]
+1

Posted about my issue on SO [here](https://stackoverflow.com/questions/53462978/unhealthy-backends-using-gcp-network-endpoint-groups-for-container-native-load-b)but sounds like the same problem. Am also on version `1.11.2-gke.18`.

**Comment by uschen** [comment]
same issue here 1.11.3 and 1.11.4

**Comment by freehan** [comment]
> same issue here 1.11.3 and 1.11.4

> the NEG will retain the old pod IPs for at least 5min, in the meantime, requests will be responded with 502.


@uschen I do not think this is the same issue. I created an umbrella issue for container native load balancing https://github.com/kubernetes/ingress-gce/issues/583. Can you take a look and see if it matches any known issues?

If not, would you mind creating an issue with more detail? It would be great if it could include repro steps.

**Comment by freehan** [comment]
PR to fix the health check bug is in flight: #582
