### ISSUE TITLE
configure maxRatePerInstance in backend

### ISSUE THREAD

**Issue by ukai** [kubernetes/ingress-gce#545]
ingress configures backend with maxRatePerInstance=1 like

backends:
- balancingMode: RATE
  capacityScaler: 1.0
  group: https://www.googleapis.com/compute/v1/projects/$project/zones/$zone/instanceGroups/$ig
  maxRatePerInstance: 1.0

This comment says maxRatePerInstance value doesn't matter
https://github.com/kubernetes/ingress-gce/blob/658331802409cf9469f49d9fb70ad27cc85a1a31/pkg/backends/ig_linker.go#L57

but actually I experienced lots of 502 errors when it received too many requests per second.

I manually raised maxRatePerInstance (e.g. to 20.0), 502 errors disappeared.
can we configure maxRatePerInstance by ingress annotation or so.

we might also want to configure timeoutSec too.

**Comment by rramkumar1** [comment]
@ukai Another option to alleviate this which would allow us not to expose it.

We could just increase the default maxRatePerInstance we set from 1 to N (possibly even the max int as shown in the comment).

/kind cleanup

**Comment by rramkumar1** [comment]
We need to consider though how changing that value might effect existing users.

I'll give it some thought before creating a PR.

/assign

**Comment by ukai** [comment]
by making backend server robust (less eviction, OOM killed), we could reduce 502 errors, so might not need to set maxRatePerInstance.

**Comment by rramkumar1** [comment]
@ukai Can we close this?

**Comment by ukai** [comment]
yeah
