### ISSUE TITLE
ErrImagePull: k8s.gcr.io/defaultbackend:1.5 not found

### ISSUE THREAD

**Issue by mkozjak** [kubernetes/ingress-gce#549]
Works with gcr.io/google-containers/defaultbackend:1.4.

**Comment by pondohva** [comment]
it was updated here https://github.com/kubernetes/ingress-gce/pull/496/files

but I can't download defaultbackend:1.5 too, 1.4 works fine

```
➜  ~ docker run -ti gcr.io/google_containers/defaultbackend:1.5
Unable to find image 'gcr.io/google_containers/defaultbackend:1.5' locally
docker: Error response from daemon: manifest for gcr.io/google_containers/defaultbackend:1.5 not found.
See 'docker run --help'.
➜  ~ docker run -ti k8s.gcr.io/defaultbackend:1.5
Unable to find image 'k8s.gcr.io/defaultbackend:1.5' locally
docker: Error response from daemon: manifest for k8s.gcr.io/defaultbackend:1.5 not found.
See 'docker run --help'.
```

I guess it has to be built using ingress-gce CI processes, because [it was adopted from ingress-nginx](https://github.com/kubernetes/ingress-gce/pull/503)

**Comment by pondohva** [comment]
@rramkumar1 should we just rollback to previous version right now? Could you please explain how this process work (from repo to docker image)

**Comment by rramkumar1** [comment]
@pondohva I will ask around and see why the image was bumped without it actually existing.

In the meantime, can you modify your default backend by hand and point it at 1.4?

**Comment by mkozjak** [comment]
@rramkumar1 bear in mind that `google_containers` in url is also `google-containers` if you want to get it working.
Change `gcr.io/google_containers/defaultbackend:1.5` to `gcr.io/google-containers/defaultbackend:1.4`.
