### ISSUE TITLE
Backend health is reported as "Unknown" if there are no pods in the first zone of a regional cluster

### ISSUE THREAD

**Issue by jeromefroe** [kubernetes/ingress-gce#554]
Currently, the health of a backend is determined by looking at the first `HealthStatus` of the service group:

```go
// TODO: Look at more than one backend's status
// TODO: Include port, ip in the status, since it's in the health info.
hs, err := b.cloud.GetGlobalBackendServiceHealth(name, be.Backends[0].Group)
if err != nil || len(hs.HealthStatus) == 0 || hs.HealthStatus[0] == nil {
	return "Unknown"
}
// TODO: State transition are important, not just the latest.
return hs.HealthStatus[0].HealthState
```

For regional clusters, the call to `GetGlobalBackendServiceHealth` will return a backend, and therefore a `HealthStatus`, for each zone. Consequently, if the serving pods of a service are running in a subset of the zones in a cluster, then the health of the service will be marked as `Unknown` if that subset of zones doesn't include the first zone in the cluster.

As a concrete example, I have a regional cluster running in `us-east1`, and if I have a service with two serving pods, one in `us-east1-c` and `us-east1-d` respectively, then the state of the service will be "Unknown" because there are no serving pods in `us-east1-b` and `hs.HealthStatus[0]` is nil as a result. This can be confusing for a user because other services which also have two serving pods will be marked as healthy arbitrarily if one of their pods is in `us-east1-b`.

The code in question includes a TODO for looking at more than one backend's status and I would be more than happy to work on a PR to do just that. Before doing so though I wanted to start a discussion on what the desired logic should be. Three potential options I see are:

1. If any `HealthState` is `"HEALTHY"`, report the backend as `"HEALTHY"` as well.
2. If a majority of the non-nil `HealthState`'s are `"HEALTHY"`, report the backend as `"HEALTHY"` as well.
3. If any non-nil `HealthState` is `"UNHEALTHY"`, report the backend as `"UNHEALTHY"`.

My personal take would be to follow approach 2 as I think it offers a good balance between options 1 and 3. Unlike option 3, it won't report the backend as unhealthy due to temporary disruptions in the serving pods, but unlike option 1 it can signal potential major disruptions before all backends are unhealthy. This is by no means an exhaustive list, and we may want to consider nil `HealthState`'s as well (I'm not familiar enough with Google Cloud API myself to understand their significance) so any feedback would be greatly appreciated. Thanks!

**Comment by rramkumar1** [comment]
@jeromefroe FYI this is a duplicate of #35

If you take a look at the discussion in that issue, we posed the question of what people are using this backend status annotation for? Do you have a use case for it? 

We are considering getting rid of it and having users simply look in the GCP console for this information.

**Comment by jeromefroe** [comment]
Ahh, I'll close this out in favor of that issue then.

I don't have any use for the annotation myself. I just found it confusing that the console was displaying the status of one of the backends as "Unknown" when other similar backends were marked as healthy and it seemed that the status in the console was being derived from the annotation.
