### ISSUE TITLE
Ingress-GCE docs overhaul

### ISSUE THREAD

**Issue by rramkumar1** [kubernetes/ingress-gce#557]
Using this issue to track the work being done to revamp the documentation in this repository.

/assign

**Comment by zvictor** [comment]
I am confused by the way it has been done.
Why deleting all the old docs before having new ones? What is the point of keeping users in the limbo with no place to check?

**Comment by rramkumar1** [comment]
@zvictor I'm not sure why you think we deleted old docs before having new ones. Only material that was severely outdated was deleted.
