### ISSUE TITLE
load balancer controller out of sync with gcp and ingress annotations

### ISSUE THREAD

**Issue by one000mph** [kubernetes/ingress-gce#562]
I have a use case where we need to reassign a reserved external IP from one Ingress to another. In the GCP console and CLI I am seeing that all forwarding rules, url maps, etc. are configured correctly but in `kubectl describe ing/<ingress-name>` I am getting the following error
```
Events:
  Type     Reason  Age                From                     Message
  ----     ------  ----               ----                     -------
  Warning  Sync    6m (x28 over 55m)  loadbalancer-controller  Error during sync: googleapi: Error 400: Invalid value for field 'resource.IPAddress': 'XX.XXX.XXX.XXX'. Invalid IP address specified., invalid
```
The IP `XX.XXX.XXX.XXX` is the old IP that was assigned to the Ingress prior to reconfiguring the frontend (forwarding rules in GCP). If I view the load balancer config in GCP Console I see a different IP `YY.YYY.YYY.YYY`. The IP `XX.XXX.XXX.XXX` is no longer reserved in GCP at all.

I have the following annotations on my kubernetes Ingress
```
    ingress.kubernetes.io/forwarding-rule: [redacted] # maps YY.YYY.YYY.YYY:80 to the correct backends
    ingress.kubernetes.io/https-forwarding-rule: [redacted] # maps YY.YYY.YYY.YYY:443 to the correct backends
    ingress.kubernetes.io/https-target-proxy: [redacted]
    ingress.kubernetes.io/ssl-cert: [redacted]
    ingress.kubernetes.io/target-proxy: [redacted]
    ingress.kubernetes.io/url-map: [redacted]
```

Why is the IP `XX.XXX.XXX.XXX` still hanging around. It seems strange that I cannot reassign an external IP to a LoadBalancer/Ingress. Any insights into this problem would be appreciated.

**Comment by one000mph** [comment]
In addition I can verify that traffic is being routed correctly from `YY.YYY.YYY.YYY` to my services. The only thing "broken" here is the k8s view of the Ingress and the load balancer controller which still thinks it is assigned `XX.XXX.XXX.XXX`

**Comment by bowei** [comment]
Can you describe the steps you took on the Ingress resource? (e.g. post the original YAML and the diffs)

**Comment by one000mph** [comment]
I did most of the editing with GCP itself. I created a global forwarding rule for `YY.YYY.YYY.YYY` to the appropriate target proxy. I then edited the annotations listed here to the correct names as reflected in the GCP console and with the `gcloud` cli.
```
    ingress.kubernetes.io/forwarding-rule: [redacted]
    ingress.kubernetes.io/https-forwarding-rule: [redacted]
    ingress.kubernetes.io/https-target-proxy: [redacted]
    ingress.kubernetes.io/target-proxy: [redacted]
```

Those updates correctly directed the network traffic to a new set of backends served via the endpoint set by the http & https forwarding rules but it did not update the loadbalancer IP from the perspective of GLBC. I also tried setting `ingress.kubernetes.io/global-static-ip-name: [external ip name]` based on the documentation [here](https://github.com/kubernetes/ingress-gce/blob/master/docs/annotations.md#specify-reserved-gcp-address) but this had no further effect.

**Comment by rramkumar1** [comment]
@one000mph Sorry for the really late reply.

> I then edited the annotations listed here to the correct names as reflected in the GCP console and with the `gcloud` cli.

What was the motivation behind editing the annotations? Modifying them does not do anything to the LB, they are only there as a "status". 

> I also tried setting `ingress.kubernetes.io/global-static-ip-name: [external ip name]` based on the documentation

Do you see any events when executing `kubectl get events` in the same namespace as your Ingress?

**Comment by one000mph** [comment]
> What was the motivation behind editing the annotations? Modifying them does not do anything to the LB, they are only there as a "status".
I don't think this is true in my experience. Setting that annotation does modify the ingress controller behavior. There is [documentation](https://cloud.google.com/kubernetes-engine/docs/tutorials/http-balancer#step_5_optional_configuring_a_static_ip_address) on how to modify annotations to configure the ingress controller. 

This is quite an old issue and I think what I was trying to do was probably a fringe use case that might not be officially supported (yet?). If I run into it again I'll come back to this and reopen.

**Comment by rramkumar1** [comment]
@one000mph The annotation you are referring to is "kubernetes.io/ingress.global-static-ip-name". This **is** an API surface for the user so you can edit it. The others like "ingress.kubernetes.io/forwarding-rule" or "ingress.kubernetes.io/target-proxy" are simply there for your consumption. Editing them does nothing.
