### ISSUE TITLE
BackendConfig OpenAPI spec

### ISSUE THREAD

**Issue by DennisVis** [kubernetes/ingress-gce#563]
I'm using Deployment Manager to deploy all k8s resources by leveraging custom types. To create these types Deployment Manager needs access to an OpenAPI spec. For the Ingress this works fine, but I can't find the one for the BackendConfig type. 

I see one is created in `pkg/apis/backendconfig/v1beta1/zz_generated.openapi.go`, is this exposed anywhere on the gke cluster?

**Comment by DennisVis** [comment]
The first place I looked was in the cluster swagger specification which can be found at `https://{cluster-ip}/swaggerapi`. But none of the endpoints seem to hold a reference to the namespace being used by the BackendConfig `cloud.google.com`.

I tried finding the API itself which can be found at `https://{cluster-ip}/apis/cloud.google.com/v1beta1`. A GET request results in a descriptive document, but it's not an OpenAPI spec so DM can't use it. 

I assume the spec must live somewhere and be reachable as the existence of `zz_generated.openapi.go` suggests as much.

**Comment by rramkumar1** [comment]
@DennisVis thanks for the info. I'll ask around to see how this can be resolved as I'm not immediately sure what the next step is.

**Comment by DennisVis** [comment]
@rramkumar1 Did you manage to make any progress on this?

**Comment by MrHohn** [comment]
It seems like folks are working on publishing openapi for CRD: https://github.com/kubernetes/kubernetes/pull/71192

**Comment by mbohlool** [comment]
Also `https://{cluster-ip}/swaggerapi` is deprecated and old swagger 1.2. It is not up to date. The correct path is `https://{cluster-ip}/openapi/v2`. But CRDs is not included in OpenAPI spec yet and kubernetes/kubernetes#71192 is trying to handle that. Note that it will only appear if the CRD has a validation schema which is in OpenAPI v3 model format.
