### ISSUE TITLE
Not exposed in ingress

### ISSUE THREAD

**Issue by kakarot1994** [kubernetes/ingress-gce#568]
I have noticed the feature is not exposed in Ingress.Please help out.

Thanks and Regards

**Comment by rramkumar1** [comment]
@kakarot1994 What feature?

**Comment by rramkumar1** [comment]
ping @kakarot1994

**Comment by rramkumar1** [comment]
I'm going to go ahead and close this since it's not clear what the issue is. 

@kakarot1994 Please re-open once you can provide more details.
