### ISSUE TITLE
Instance is Not Removed from IG when node is marked as unschedulable

### ISSUE THREAD

**Issue by freehan** [kubernetes/ingress-gce#591]
**How to reproduce it (as minimally and precisely as possible)**:
```
kubectl cordon ${Node}
```

**What happened**:

Ingress controller did not remove the corresponding instance from IG and emit error messages like this:
```
E1220 14:43:16.052232  257911 instances.go:214] Failed to get zones for e2e-test-mixia-minion-group-3mzg: node not found e2e-test-mixia-minion-group-3mzg, skipping
```

**What you expected to happen**:
Unschedulable node got removed from instance group.  

**Root Cause**:
Ingress controller failed to look up the corresponding zone of the instance when the node is marked as unschedulable. This is because the util function `GetZoneForNode` filter out the nodes that are not ready OR unschedulable. This is introduced here: #370

I think the `GetZoneForNode` should not filter out any nodes. It should return the zone of the node whenever is necessary. Thoughts?

/kind bug

**Comment by MrHohn** [comment]
https://github.com/kubernetes/ingress-gce/pull/576 is attempting to remove the predicate filter.

**Comment by freehan** [comment]
closing this as #576 is merged
