### ISSUE TITLE
Is there nginx-controller like session affinity support

### ISSUE THREAD

**Issue by tsloughter** [kubernetes/ingress-gce#60]
I've been trying to find a solid answer on how to use (if it is even possible) session affinity with a GCE ingress resource.

My understanding is that nginx supports this by going around the service's vip and directly to the pods, updating the nginx configuration as it needs to when the pods change -- since while service's support clientip affinity this would be based on the nginx ip and not the client making the http request so the service must be bypassed.

Can the GCE ingress do similar or is there an alternative way to get affinity?

**Comment by jaysonjc** [comment]
It appears that currently the only solution is to install an nginx controller in GKE.

**Comment by nandosangenetto** [comment]
@jaysonjc how can I do that?

**Comment by tetianakravchenko** [comment]
I am also interested in affinity for GCE ingress, any updates for this ticket?
