### ISSUE TITLE
Sync error when ingress name has dots

### ISSUE THREAD

**Issue by mcfedr** [kubernetes/ingress-gce#614]
Its valid for kubernetes resources to have dots in the names, so an ingress with a name like `some.host.com-ingress` is valid, but the gce ingress fails when you create such an ingress, with an error like

```
Error during sync: Error running load balancer syncing routine: googleapi: Error 400: Invalid value 'k8s-um-default-some.home.com-ingress--521bdf95908d2d0'. Values must match the following regular expression: '[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?', invalidParameter
```

This mismatch of valid values could be handled by the controller

**Comment by bowei** [comment]
We may not elect to fix this as the munging the dots into underscores in the name can result aliasing issues for the GCP objects, unless there are a lot of users in this situation...

**Comment by rramkumar1** [comment]
For tracking purposes, marking this as a bug but as bowei said, we may not fix this. 

/kind bug

**Comment by mcfedr** [comment]
Fair enough, i thought that might be the case, but still useful to know about it and for others to be able to find it.

**Comment by swetharepakula** [comment]
Closing, as we will not be adding support for this.
