### ISSUE TITLE
Defaults per cluster or project?

### ISSUE THREAD

**Issue by rodlogic** [kubernetes/ingress-gce#632]
Is there a way to provide a default TLS certificate or set of certificates when creating a LB that is not at the Ingress or Service level as an annotation?

I would like to provision one TLS certificate and one DNS name for the cluster, but I don't want to have to specify the TLS cert annotation on every ingress/service. If the ingress specifies a host that is not part of the cert they app owner is out of luck and should either correct the ingress or deploy it elsewhere.

**Comment by rramkumar1** [comment]
@rodlogic Is there some Kubernetes tooling that can help you with this? I'm not too familiar helm and terraform but would it be worth taking a look at those? 

I'm not sure there is much we can do here to solve this problem. Unless you have any other questions, I'll let you close this issue.

**Comment by bowei** [comment]
This kind of thing sounds like something best left to an external tool.

**Comment by rodlogic** [comment]
I guess I am trying to avoid the overhead of each group/team knowing what the underlying Managed TLS certificate id is when deploying their own workloads. It is just unnecessary overhead.

I would like to have a cluster be serving a workloads for a single DNS name and single TLS certificate that could be provisioned along side with the cluster and be picked up automatically by the ingress controller as a default when the Ingress DNS name matches and HTTPS is enabled.

Either ingress controller command line arguments or even a default ConfigMap that is used in case the Ingress doesn't provide the required annotations.

**Comment by rodlogic** [comment]
FYI: A similar issue was created on the AWS ALB Ingress Controller: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/746

**Comment by rramkumar1** [comment]
@rodlogic This might be a terrible idea so bear with me...

What if you stores the cluster-wide TLS cert name or secret in a config map and when a group/team creates an Ingress, you have a mutating admission webhook that then edits the Ingress object with that cert name / secret. In theory, this should free your teams from having to know about the TLS information and you can easily switch out the config by modifying the config map/

**Comment by bowei** [comment]
You can use a webhook for sync modifications or just have a controller watch and modify YAMLs asynchronously.

**Comment by rodlogic** [comment]
Hi @rramkumar1, thanks for the alternative! 

However, I am not sure I follow why this might be a terrible idea? I come with the assumption that this use case is more common than just an outlier (at least it has been also a request to the alb ingress controller and well accepted there), and considering the cost of a custom created, deployed and maintained mutating admission webhook multiplied by the number of companies/projects that will have the same need, it seems to me that this feature pays for itself with a very small cost to the ingress-gce project.

I may be wrong, but I also think that being able to have infrastructure specific defaults for other similar annotations, will also be very valuable.

**Comment by bowei** [comment]
This sounds like something that would go into an IngressClass resource? We should try to sketch out a generic design, this will not be the only common infra feature. Can you link the ALB feature request.

**Comment by rodlogic** [comment]
[This](https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/800) is discussion is also interesting.

More specifically, [this](https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/800#issuecomment-454104073) proposal and what it enables:

> Same. We have multiple environments (namespaces) in the same cluster and auto-detection via tags is how we assign DNS names for the services in each environment (via Route53/ExternalDNS). It would be great if something similar exists to support automatically assigning certs from ACM to the ALB so that we don't have to maintain a deployment spec with a unique cert ARN for each environment.

**Comment by rodlogic** [comment]
Hi @bowei, [this](kubernetes-sigs/aws-alb-ingress-controller#746) is the similar ALB feature request aside from the additional one I posted just now.

**Comment by bowei** [comment]
@rodlogic -- your link doesn't seem to work?

**Comment by rodlogic** [comment]
@bowei I just fixed it, sorry.
