### ISSUE TITLE
Confusion about the root health check

### ISSUE THREAD

**Issue by benfdking** [kubernetes/ingress-gce#674]
Please forgive me if I have put this in the wrong place. 

As has been often stated in the issues, there is some confusion about the ingress health check requiring a 200 at the root. After some investigation, we noticed that the request contained a distinctive `User-Agent` header `GoogleHC/1.0`. With that in mind, we built some Go middleware based on that finding:

https://github.com/tumelohq/gke-ingress-healthcheck-middleware

It is very simple and works on the assumption that the request is:

1. indeed at the root path
3. the User-Agent is "GoogleHC/1.0"
3. the request method is "GET"

Would there be any way of either confirming this to ensure that this is expected and does not suddenly break? This information could also possibly be put in some documentation to avoid further confusion.

**Comment by rramkumar1** [comment]
@benfdking 

Assumptions 1 and 3 look fine to me.

Regarding the user agent, we don't really have a way to prevent the Google Health Checker from modifying it's signature to say, "GoogleHC/1.1". My feeling is that you should not depend on the user agent being exactly as specified. A safer (but still risky) bet would be to check if the user agent starts with the prefix "Google".

If your setup allows, I would recommend an alternative solution. The recommendation would be to manually modify your health check to point to some path you know won't be hit by other clients. For example, serve a 200 on the path "/thisisonlyforthegooglehealthchecker" and then manually modify your health check to point to that path. Today, Ingress-GCE will not overwrite your changes to the manually modified health check so it is safe to do this.

**Comment by rramkumar1** [comment]
@benfdking Is there any other information I can provide here? I'm going to close this for now but please reopen if you need something else.

**Comment by benfdking** [comment]
Sorry I have not responded. Is this the pointing with the GKE possible? From everything I have read it doesn't work or is unreliable, i.e. the ingress can only be created after the services have been created?

**Comment by rramkumar1** [comment]
> From everything I have read it doesn't work or is unreliable, i.e. the ingress can only be created after the services have been created?

Yes that's true, but I'm not sure how that's related here.

**Comment by benfdking** [comment]
Unfortunately, this is the only reliable way I have seemed to found to handle the GCE-ingress. Given my current understanding of the issue, the fact that it is not self-corrective with regards to changes to the backend it points towards is not compatible with the way we currently develop. 

Given 

> Yes that's true, but I'm not sure how that's related here.

- every time the fanning out endpoints of the ingress change, the ingress needs to be deleted and recreated
- similarly if the health check endpoint changes 
All of which cause significant downtime as the load-balancers can take a while to stop and start. 

Additionally I don't think you can get it to work if you put the health check on another port. Something you might want to do if you are handling more sensitive information through the health check.

**Comment by rramkumar1** [comment]
> every time the fanning out endpoints of the ingress change, the ingress needs to be deleted and recreated

Do you mean K8s endpoints? Even if your K8s endpoints change, you should not have to delete and recreate the Ingress.

> Additionally I don't think you can get it to work if you put the health check on another port.

This is correct. See #647 which is related.

**Comment by benfdking** [comment]
Trying to address this issue here as well https://github.com/pusher/oauth2_proxy/issues/86

**Comment by rramkumar1** [comment]
@benfdking Can this be closed? I think the original question was answered.

**Comment by rramkumar1** [comment]
@benfdking Closing this. Please reopen if you have anymore questions.
