### ISSUE TITLE
Link for the example on deploying ingress controller is not valid

### ISSUE THREAD

**Issue by pcnfernando** [kubernetes/ingress-gce#686]
Under the heading;  [how-do-i-deploy-an-ingress-controller](https://github.com/kubernetes/ingress-gce/blob/master/docs/faq/README.md#how-do-i-deploy-an-ingress-controller), the example pointed is an invalid link.

**Comment by rramkumar1** [comment]
Sorry about that. The documentation in this repo is in a slight state of flux but I am working on getting everything back in a good state.

**Comment by rramkumar1** [comment]
@pcnfernando This is now fixed. See docs/deploy.
