### ISSUE TITLE
Disabling/Configuring HSTS

### ISSUE THREAD

**Issue by pedropregueiro** [kubernetes/ingress-gce#693]
Is it possible to configure the HSTS options on the GCE ingress the same way it's possible to do it with the ingress-nginx:

https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#hsts

**Comment by rramkumar1** [comment]
@pedropregueiro We don't support HSTS but we do support something similar via the annotation kubernetes.io/ingress.allow-http: "false"

This will ensure clients can only talk HTTPS to the Google LB frontend.

**Comment by pedropregueiro** [comment]
In that case, I can't control the HSTS header `Strict-Transport-Policy` options (max-age, preload, sub-domains), so I'll just move to ingress-nginx instead.

thanks for the answer though @rramkumar1, closing this one now.
