### ISSUE TITLE
jobs failing with "unknown flag: --verbose"

### ISSUE THREAD

**Issue by MrHohn** [kubernetes/ingress-gce#700]
Ref https://k8s-testgrid.appspot.com/sig-network-ingress-gce-e2e#ingress-gce-e2e-scale, GLBC is crashlooping with ([this error](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-ingress-gce-e2e-scale/1579/artifacts/e2e-1579-886f8-master/glbc.log)):
```
unknown flag: --verbose
```

Should probably cleanup manifest somewhere to stop using the recently deleted flags.

cc @rramkumar1

**Comment by rramkumar1** [comment]
@MrHohn Flag issue is fixed but now tests are still failing. I'm looking into why...

**Comment by rramkumar1** [comment]
The above PR fixed everything but the release-1.[3,4,5] jobs. Still need to figure out what is going on with those.

**Comment by rramkumar1** [comment]
/close

This is fixed.
