### ISSUE TITLE
Add tests for multi cluster ingresses

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/ingress-gce#71]
Tasks:
- [x] Add an e2e test to ensure that instance groups annotation is added to an ingress with the multicluster ingress class annotation.
- [ ] Ensure that the instance groups annotation is added for each zone in a multi zonal cluster.

cc @nicksardo @G-Harmon

**Comment by nikhiljindal** [comment]
I have https://github.com/kubernetes/kubernetes/pull/55047 for the first with a TODO for the second :)

@nicksardo Do you know if we have any ingress tests for multi-zone clusters?
I am not sure how much extra work it is to set up infra for multi zone clusters.
@bowei Is this something you are looking at as part of improving test coverage for ingress?

**Comment by nikhiljindal** [comment]
/remove-lifecycle stale

cc @MrHohn do we have ingress tests for multi-zone clusters?

**Comment by MrHohn** [comment]
> cc @MrHohn do we have ingress tests for multi-zone clusters?

Not that I know of, I was also thinking of a test case that requires adding a new zone to the cluster. But not works have been done at this point.

**Comment by nikhiljindal** [comment]
ok. Do you plan to add another job that brings up a multizone cluster and then run (all or some selected) existing tests?
Or add a zone to a cluster as part of the existing e2e test job?

**Comment by MrHohn** [comment]
> Do you plan to add another job that brings up a multizone cluster and then run (all or some selected) existing tests?
Or add a zone to a cluster as part of the existing e2e test job?

I was thinking about the second case --- adding a zone to a cluster, but it seems like the fist case is something we should add first. I maybe able to take a look later if no ones plan to work on that.

**Comment by nikhiljindal** [comment]
Sounds great!
Yes doing first will enable us to run existing tests in multicluster setup which will be a huge benefit.

**Comment by nikhiljindal** [comment]
@MrHohn Any update on multi-zonal cluster support for testing ingresses?

**Comment by MrHohn** [comment]
@nikhiljindal Sorry this fell off the radar. I will see if I can do something this week.

**Comment by bowei** [comment]
zihong is filing a separate issue for tracking adding multi-zonal tests

**Comment by rramkumar1** [comment]
@nikhiljindal We just added a new test job which runs against a multi-zonal cluster. 

See https://k8s-testgrid.appspot.com/sig-network-ingress-gce-e2e#ingress-gce-e2e-multi-zone

So you should be able to now modify the existing e2e test to check that the annotation has been added for each zone. The code to get the cluster zones can be found at https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/util.go#L5245:6
