### ISSUE TITLE
Configuring SSL Policies

### ISSUE THREAD

**Issue by artefactop** [kubernetes/ingress-gce#716]
I want to configure a different SLL Policy than the default one in my GKE ingresses. In theory, `ingress-gce` has support for it, see https://github.com/kubernetes/ingress-gce/pull/291/files, but I have no idea how to do it.

Could I get some example?

**Comment by rramkumar1** [comment]
Closing since this is a duplicate of #246

**Comment by rdkr** [comment]
@artefactop the PR files you linked look like they set Cloud Armor Security Policies not Load Balancing SSL Policies, unfortunately.
