### ISSUE TITLE
Split CRD creation out of GLBC 

### ISSUE THREAD

**Issue by dekkagaijin** [kubernetes/ingress-gce#744]
Creation of CRDs should be split from the implementation of the controller itself:
https://github.com/kubernetes/ingress-gce/blob/4918eb2f0f484f09ac9e5a975907a9b16ed2b344/cmd/glbc/main.go#L93

/assign rramkumar1

**Comment by freehan** [comment]
I am wondering what is the benefit of doing this?

**Comment by swetharepakula** [comment]
We currently do not plan on making this change.
