### ISSUE TITLE
Update GKE self managed script

### ISSUE THREAD

**Issue by KatrinaHoffert** [kubernetes/ingress-gce#758]
Kinda a follow up to #755, I noted a few other issues I had with the flow described in `docs/deploy/gke/README.md`. Firstly, the readme doesn't mention the need to update `glbc.yaml` for your custom image location. Secondly, the command flags are outdated and prevent the controller from running.

I want to also look into automating more of this or at least improving the documentation.

* We already get the project name from `gcloud`
* Network and subnetwork name are easily determined from `gcloud container cluster describe` (the cluster name is already provided to the setup script)
* The node-instance-prefix should be determinable from the cluster name and we strangly don't even allow the user to continue if it doesn't make that expectation!
* Node tags are a little harder. Get the instance groups from `describe cluster`, list instances, and describe those instances to get the network tags.

Zone should just be asked by the script. Should take the image URL in, too, so it can be just one command to set everything up.

I'll look into this. I already did the work of figuring out how to get that script to work for me and confirmed its working.

**Comment by rramkumar1** [comment]
Closing since relevant PR has been merged. 

Thanks @KatrinaHoffert !
