### ISSUE TITLE
NEG controller should create NEG for default backend when enabled

### ISSUE THREAD

**Issue by freehan** [kubernetes/ingress-gce#767]
NEG controller currently ignores default backend service even it has NEG enabled. This is because default backend service is not explicitly referenced in the ingress spec.

https://github.com/kubernetes/ingress-gce/blob/master/pkg/neg/controller.go#L309

**Comment by rafi-greenberg** [comment]
@freehan  Just curious - does #789  only apply to ILB?

It seems that all our NEG-enabled services create default backends as instance groups.

![image](https://user-images.githubusercontent.com/3811209/90044484-8d239500-dc82-11ea-8188-c6588bbb1882.png)

**Comment by spencerhance** [comment]
@rafi-greenberg right now this only applies to ILB.  @freehan are we planning on supporting this for ELB with neg default?
