### ISSUE TITLE
examples/websocket/server.go: concurrent write to socket

### ISSUE THREAD

**Issue by JordanP** [kubernetes/ingress-gce#77]
In the `handleWSConn` function, the goroutine calls `c.WriteMessage` and the other for loop also calls `c.WriteMessage`. But according to Gorilla WS doc, `WriteMessage` is not goroutine safe. We need to use a mutex to protect concurrent writes.

I saw a couple of goroutine panics because of this while doing some light stress tests.

**Comment by nicksardo** [comment]
Could you send a PR?

**Comment by nicksardo** [comment]
Correction, I'll do it. Need to add a license to it.
