### ISSUE TITLE
Migrate Ingress type to networking.k8s.io/v1beta1

### ISSUE THREAD

**Issue by cmluciano** [kubernetes/ingress-gce#770]
The deprecation process for the Ingress extensions type is almost complete and 1.15 will persist Ingress types in the new networking.k8s.io/v1beta1 . This report is to track ingress-gce moving to the new api group similar to the [ingress-nginx](https://github.com/kubernetes/ingress-nginx/pull/4127) PR.

cc @bowei @freehan

**Comment by snebel29** [comment]
Hi,
I'm working in a tool that uses controller machinery and I was about to implement the ingress resource when realize that from `1.14` the new api groupfor ingress is available, and `extensionsv1beta1` is deprecated, of course you still can use the deprecated api group but at some point this will be removed.

I was wondering how others are dealing with such cases to be as transparent as possible for users and came here... I wonder if `go-client` offers a way to discover the cluster version at runtime and then you just use conditionals for using the old and/or new api group types, or a strict new version of the controller has to be deployed is required, etc..

I will keep digging on my own, but out of curiosity do you have any plan already in mind?

Thanks

**Comment by aledbf** [comment]
@snebel29 we (ingress-nginx) check the k8s version https://github.com/kubernetes/ingress-nginx/blob/master/internal/ingress/controller/store/store.go#L270 for the informer and switched everything to networking.k8s.io internally in the ingress controller using a helper https://github.com/kubernetes/ingress-nginx/blob/930e37a0b520cfde5f880cca809d1b7cbe300db5/internal/ingress/controller/store/store.go#L910 for clusters running k8s < 1.14.0

**Comment by snebel29** [comment]
Oh, this is great @aledbf !
thank you so much for such a good and quick answer.

Saludos y gracias

**Comment by rramkumar1** [comment]
This was completed this in #806. bowei@ can this be closed?

**Comment by cmluciano** [comment]
I think this should be good to go

/close
