### ISSUE TITLE
Ingress not Working With Websocket

### ISSUE THREAD

**Issue by JanisOrlovs** [kubernetes/ingress-gce#793]
Hello,
I'm running applications on GKE

```bash 
kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.6-gke.13", GitCommit:"fcbc1d20b6bca1936c0317743055ac75aef608ce", GitTreeState:"clean", BuildDate:"2019-06-19T20:50:07Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
```

OS versions: COS

and I have got SpringBoot service with UI built with Vaadin. I have got problem, that websocket is not working thru GCE ingress (same solution works well thru nginx ingress). And I want use IAP for auth.

Current configuration: using GCE ingress, nodeport, backend configs and managed certificates
```bash
---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: my-backend-config
  namespace: preprod
spec:
  timeoutSec: 720000
---

apiVersion: v1
kind: Service
metadata:
  name: ppkebo
  namespace: preprod
  annotations:
    cloud.google.com/app-protocols: '{"portbo":"HTTPS","portboplain":"HTTP"}'
    beta.cloud.google.com/backend-config: '{"ports": {"portbo" :"my-backend-config","portboplain" :"my-backend-config"}}'
spec:
  type: NodePort
  ports:
  - name: portbo
    protocol: TCP
    port: 443
    targetPort: 443
  - name: portboplain
    port: 8090
    targetPort: 8090
  selector:
   app: bo
   environment: preprod

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ppkebo
  namespace: preprod
  annotations:
    kubernetes.io/ingress.global-static-ip-name: preprod-ip	
    networking.gke.io/managed-certificates: example-certificate
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - host: xx.example.com
    http:
      paths:
      - path: /*
        backend:
          servicePort: portboplain
          serviceName: ppkebo          
---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: example-certificate
  namespace: preprod
spec:
  domains:
  - xx.example.com
```
From request perspective it looks like this: 
![image](https://user-images.githubusercontent.com/7012337/60871038-a9146600-a23a-11e9-92c3-658294068d0f.png)

On nginx ingress it works fine.

**Comment by rramkumar1** [comment]
@JanisOrlovs Can you please clarify what exact issue you are running into? It's not clear to me from your screenshot.

**Comment by JanisOrlovs** [comment]
Hello,
Websocket breaks after 30 seconds

**Comment by rramkumar1** [comment]
@JanisOrlovs The default setting for backend service timeout is 30 sec so its possible your BackendConfig settings were not applied. 

Can you check if there are any K8s events on your Ingress?

**Comment by JanisOrlovs** [comment]
Hello,
There are no ingress events only setup certs eg normal events. 
How can I check default timeouts? In LBL ui/gcloud console everything all looks as it should

**Comment by rramkumar1** [comment]
@JanisOrlovs So if you look at the associated Backend Service in the UI, it shows the timeout as 720000?

**Comment by JanisOrlovs** [comment]
yes of course

**Comment by rramkumar1** [comment]
@JanisOrlovs Can you send me an email with your project ID, cluster name and cluster zone? I can take a closer look on our end.

**Comment by giladsh1** [comment]
@JanisOrlovs I think you're encountering this issue since you're using the port name and not the actual number (that was the case for me).
try setting the service annotation to something like this - 
```
beta.cloud.google.com/backend-config: '{"ports": {"443" :"my-backend-config","80" :"my-backend-config"}}'
```

**Comment by vinicyusmacedo** [comment]
@giladsh1 judging by this [code](https://github.com/kubernetes/ingress-gce/blob/ab3d9e5cf9935595aad5c471901dfc5afb6d5e51/pkg/backendconfig/utils.go#L172), it actually accepts both port name and port number. 

@JanisOrlovs can you check the Service events?

**Comment by giladsh1** [comment]
@vinicyusmacedo from my testing, I've encountered several issue while using the port name.
specifically, NEG groups didn't work.
see #832 for more info

**Comment by masus04** [comment]
Was there ever a solution to this?

**Comment by borisevstratov** [comment]
> Was there ever a solution to this?

Yup, there you go:

https://github.com/kubernetes/ingress-gce/tree/b0603c69382a39d097063eab8e3d9e30ca1cdf7b/examples/websocket#change-backend-timeout
