### ISSUE TITLE
Backend syncer should not block syncing if one backend fails GC

### ISSUE THREAD

**Issue by spencerhance** [kubernetes/ingress-gce#797]
Currently backendSyncer.GC() will break out of the GC loop if one backend fails.  It should collect all of the errors into a slice and return that instead.

https://github.com/kubernetes/ingress-gce/blob/master/pkg/backends/syncer.go#L135

**Comment by rramkumar1** [comment]
@shance Sounds reasonable, you mind fixing it?

**Comment by spencerhance** [comment]
sounds good /assign @spencerhance

**Comment by rramkumar1** [comment]
@spencerhance Can this be closed?

/kind cleanup
