### ISSUE TITLE
Recently , I have same issue on both clusters....

### ISSUE THREAD

**Issue by stinger-forever** [kubernetes/ingress-gce#801]
Recently , I have same issue on both clusters.... 
I have some GCE ingresses and have several nginx.class ingresses on the same cluster. 
Now when I create new nginx class controller, service implementing successfully, get proper IP address, but the nginx class annotaion is ignored during deploy and new L7 balancer is creating.

_Originally posted by @stinger-forever in https://github.com/kubernetes/ingress-gce/issues/476#issuecomment-513746382_

**Comment by bowei** [comment]
Which L7 is being provisioned? (ingress-gce or nginx)

**Comment by bowei** [comment]
@rramkumar1

**Comment by stinger-forever** [comment]
Yes definitely it's a ingress-gce L7, as it creates 3 riles 
Load balancer: 
k8s-um-default-reducted-5a9cf192f8bf54dd
Target proxy	
k8s-tp-default-0-reducted--5a9cf192f8bf54dd
Forwarding rule	
k8s-fw-default-0-reducted--5a9cf192f8bf54dd
Besides, during deployment I noticed that at some moment it attached IP from the other nginx class for about 5 seconds and later proceed with absolutely new IP and load balancer, later I noticed that ingress behavior works like I do not provided annotation for ingress type. 
This is how my typical Ingress rule look like. 
Maybe this could be helpful. My configs were working for sure on Kubernetes 1.12, maybe problem is related to 1.13 version? 
`apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: 0-company_name
  annotations:
    kubernetes.io/ingress.class: nginx-company_name
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: true
    certmanager.k8s.io/acme-http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/limit-rps: "20"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Project "company_name";
spec:
  rules:
  - host:
    http:
      paths:
      - backend:
          serviceName: testing5-service
          servicePort: 80
  `

**Comment by stinger-forever** [comment]
I have found resolutition: 
The cause of Ingresses classes conflict was below annotation 
**kubernetes.io/tls-acme: true**
It was added by my colleague and I didn't noticed it at first glance. 
But is it normal behavior?

**Comment by rramkumar1** [comment]
@stinger-forever FWIW, Ingress-GCE does not respect the kubernetes.io/tls-acme annotation.

Did this happen recently? Can you send me an email with your GCP project ID, cluster name and cluster location?

**Comment by stinger-forever** [comment]
Thank you, already sent, check email from Armen Gasparyan.
