### ISSUE TITLE
Unable to use TLS 1.3

### ISSUE THREAD

**Issue by gijo-varghese** [kubernetes/ingress-gce#817]
So I created a load balancer with GKE Ingress and enabled SSL using [gke-managed-certs](https://github.com/GoogleCloudPlatform/gke-managed-certs). However, an issue that I face is that TLS 1.3 is not supported

Digging deep, I found that [SSL Policies](https://cloud.google.com/load-balancing/docs/ssl-policies-concepts) only support up to TLS 1.2

Is there any way to upgrade to TLS 1.3?

Similar issue in managed-certs: https://github.com/GoogleCloudPlatform/gke-managed-certs/issues/33

**Comment by rramkumar1** [comment]
Support for SSL policies is tracked in #246. I will close this since its a duplicate.
