### ISSUE TITLE
Websocket not working with HTTP2 backend

### ISSUE THREAD

**Issue by mcfedr** [kubernetes/ingress-gce#855]
When I added the annotation for http2 to the backend websockets got a `502` response.

```yaml
annotations:
    cloud.google.com/app-protocols: '{"https":"HTTP2"}'
```

When I reverted to http for the backend connection everything works.

**Comment by rramkumar1** [comment]
@mcfedr Are you still encountering this? If so, would be helpful to paste the full Service & Ingress specification for both scenarios.
