### ISSUE TITLE
Missing Changelog for 1.6

### ISSUE THREAD

**Issue by michaelbannister** [kubernetes/ingress-gce#857]
[GKE release notes 12 September](https://cloud.google.com/kubernetes-engine/docs/release-notes#september_16_2019) states that 
>Ingress Controller v1.6, which was previously available in beta, is generally available for clusters running v1.13.7-gke.5 and higher.

It'd be good to see a changelog for this version.

**Comment by inductor** [comment]
```
Correction: This note was incorrectly published early. Ingress Controller v1.6 became generally available on September 20, 2019.
```

😂

**Comment by thomas-riccardi** [comment]
The changelog is also missing for 1.7

**Comment by rramkumar1** [comment]
@michaelbannister Sorry bout that. This is now fixed by #887

**Comment by thomas-riccardi** [comment]
@rramkumar1, @spencerhance thanks!

What about https://github.com/kubernetes/ingress-gce/releases?
I subscribe to notifications of github releases and proper content there is useful!

**Comment by rramkumar1** [comment]
1.6 had no user-facing changes, it was mostly a maintenance release (I will add a note about this though). 1.7 is releasing on GKE as well speak and I am working on the formal release notes for that now and I hope to have it out today.
