### ISSUE TITLE
How to enable authentication for GKE ingress

### ISSUE THREAD

**Issue by naidu571** [kubernetes/ingress-gce#914]
I am using the below annotations to enable basic authentication on gke ingress for getting into one of the application workload but its not working as its not asking for credentials when I hit the ingress IPAddress.
I even enabled the tls termination for this. Let me know how authentication works for ingress in GKE.

annotations:
    kubernetes.io/ingress.class: gce
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/auth-secret: secret
    ingress.kubernetes.io/auth-realm: "Authentication Required"

**Comment by samcgardner** [comment]
I don't believe ingress-gce supports that annotation. If you want authentication for your GKE ingress, I'd recommend looking at https://cloud.google.com/iap/docs/enabling-kubernetes-howto

**Comment by naidu571** [comment]
> I don't believe ingress-gce supports that annotation. If you want authentication for your GKE ingress, I'd recommend looking at https://cloud.google.com/iap/docs/enabling-kubernetes-howto

Thanks for the reply. I am good with this details.
