### ISSUE TITLE
GCE resource leak with v1 frontend namer 

### ISSUE THREAD

**Issue by skmatti** [kubernetes/ingress-gce#965]
v1 frontend namer leaks GCE loadbalancer forntend resources for the following ingress names,
Examples: `ingress--1, ingress--2`
Basically, when there exist two consecutive hyphens in namespace or name.

Few of the other cases are (in `<namespace>/<name>` format),
`namespace-/ing1, namespace/-ing2`

The current workflow for v1 frontend namer parses load-balancer name incorrectly. 
For example, 
URL map `k8s-um-default-my--ingress--260743b4176675c7` is parsed as `default-my-260743b4176675c7` which should have been parsed as `default-my--ingress-260743b4176675c7`.

**Comment by rramkumar1** [comment]
@skmatti What is the status of this issue?

**Comment by skmatti** [comment]
Discussed with @freehan and decided that we are not going to fix this special case. May be this should be marked as one of the known issues.

Also, v1.8.1 and above will not run into this issue.

**Comment by bowei** [comment]
@skmatti did you update the known issues if this is closed?
