### ISSUE TITLE
GCE Ingress multi-namespace routing

### ISSUE THREAD

**Issue by vsychov** [kubernetes/ingress-gce#973]
Hi guys, is exists any possible way, to create multi namespace ingress in GCE ingress?
I found related issue - https://github.com/kubernetes/kubernetes/issues/17088 but it's seems not resolved yet.

**Comment by RammusXu** [comment]
Any news? or suggestions?
I have same question with: https://github.com/kubernetes/kubernetes/issues/17088#issuecomment-495034468

**Comment by rramkumar1** [comment]
@vsychov Multi-namespace ingress is being looked at for the V2 Ingress APIs (e.g Gateway). The initial design proposal is here: https://docs.google.com/document/d/1BxYbDovMwnEqe8lj8JwHo8YxHAt3oC7ezhlFsG_tyag

Let me know if you need more information on how to keep progress on this effort but the API is being worked on here: https://github.com/kubernetes-sigs/service-apis

**Comment by Berndinox** [comment]
@rramkumar1 - is there actually a way to use this (api-gateway) in gke cluster?

**Comment by rramkumar1** [comment]
@Berndinox Not yet, but look out for it very soon. We plan to have a public launch within the next couple months.

**Comment by Andrewangeta** [comment]
> @Berndinox Not yet, but look out for it very soon. We plan to have a public launch within the next couple months.

Any news or updates on this 👀 ?

**Comment by Jojoooo1** [comment]
About to launch ?
